### ISSUE TITLE
Jsonb assertions for gregorian calendar does not check for value

### ISSUE THREAD

**Issue by rmannibucau** [eclipse-ee4j/jakartaee-tck#102]
Issue is detailled at https://github.com/eclipse-ee4j/jsonb-api/issues/177#issuecomment-521190402

A jsonb tck uses equals between gregorian calendars making the value assertions not validated properly - it validates the way/method the calendar is built which is not required by the spec since it is opaque to the user.

**Comment by jansupol** [comment]
In the case of test exclusion, the test exclusion is needed to be done for:
-  full [JakartaEETCK](https://github.com/eclipse-ee4j/jakartaee-tck/blob/60f5315215196e51a6fc3eb986149b2ff1c6d91f/install/jakartaee/bin/ts.jtx#L164)
- [JSON-B TCK](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jsonb/bin/ts.jtx#L164)

Note the name of the tests. For full Jakarta EE CTS, 4 [vehicles](https://github.com/eclipse-ee4j/jakartaee-tck/blob/60f5315215196e51a6fc3eb986149b2ff1c6d91f/install/jakartaee/other/vehicle.properties#L298) are used: 
 - _from_appclient
 - _from_ejb
 - _from_jsp
 - _from_servlet

The JSON-B uses one [vehicle](https://github.com/eclipse-ee4j/jakartaee-tck/blob/60f5315215196e51a6fc3eb986149b2ff1c6d91f/install/jsonb/other/vehicle.properties#L52):
 -  _from_standalone or _from_servlet
