### ISSUE TITLE
No reason com.sun.ts.tests.jsonb.defaultmapping.collections.CollectionsMappingTest#testEnumMap fails deserialization

### ISSUE THREAD

**Issue by rmannibucau** [eclipse-ee4j/jakartaee-tck#103]
com.sun.ts.tests.jsonb.defaultmapping.collections.CollectionsMappingTest#testEnumMap expects EnumMap can't be unmarshalled, there is no technical reason for that, was even in the spec: https://github.com/javaee/jsonb-spec/blob/dc81f781f490e26ca545f98c50a7319551f724e2/examples/runtime/src/main/java/examples/mapping/DefaultMapping.java#L460

edit: same for EnumSet test

**Comment by jansupol** [comment]
In the case of test exclusion, the test exclusion is needed to be done for:
-  full [JakartaEETCK](https://github.com/eclipse-ee4j/jakartaee-tck/blob/60f5315215196e51a6fc3eb986149b2ff1c6d91f/install/jakartaee/bin/ts.jtx#L164)
- [JSON-B TCK](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jsonb/bin/ts.jtx#L164)

Note the name of the tests. For full Jakarta EE CTS, 4 [vehicles](https://github.com/eclipse-ee4j/jakartaee-tck/blob/60f5315215196e51a6fc3eb986149b2ff1c6d91f/install/jakartaee/other/vehicle.properties#L298) are used: 
 - _from_appclient
 - _from_ejb
 - _from_jsp
 - _from_servlet

The JSON-B uses one [vehicle](https://github.com/eclipse-ee4j/jakartaee-tck/blob/60f5315215196e51a6fc3eb986149b2ff1c6d91f/install/jsonb/other/vehicle.properties#L52):
 -  _from_standalone or _from_servlet

**Comment by jansupol** [comment]
@m0mus The question is: If the Spec, Section 3.11 does not mention EnumMap and EnumSet, is it possible for the implementation to support it? If so, the tests should be excluded.

**Comment by m0mus** [comment]
I don't remember any particular reason why we are not supporting it. We should remove the negative test.

**Comment by rmannibucau** [comment]
@jansupol everything unexplicit is not forbidden as a general rule, only the opposite is true (what is explicitly required must be supported). This let vendors propose custom features on top of the specs instead of locking them.

**Comment by rmannibucau** [comment]
@bshannon it is not the case for most specs and most TCK (thinking out loud, CDI, Bean validtaion, jsonp, jsonb, ejb, jsp, servlet, jbatch, jaxws, jaxrs, inject, jpa, jta, ...), so I assume this is the common way even if not stated explicitly ;). Specs never define what they don't know so vendors generally do what they want/need and it is sane to not limit impls when there is no reason, in particular on such trivial features. User does not get guarantees though on extensions but if often enables use cases not yet covered by the spec as cyclic references for jsonb for ex.

**Comment by rmannibucau** [comment]
@bshannon factually this is not what is done even if the intent - guess vendors either take care of it or find ways to solve it.

Anyway 3.11 states it MUST be supported so the  test is actually wrong.

**Comment by jansupol** [comment]
+1 for excluding the test
