### ISSUE TITLE
TCK runner Jobs for new Standalone TCKs against Glassfish 7

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#1032]
**Is your feature request related to a problem? Please describe.**
Create TCK runner jobs for separated TCKs - Faces, Security, Authentication, Jaxrs, JSONB/P, Batch, Concurrency - as mentioned in wiki https://github.com/eclipse-ee4j/jakartaee-tck/wiki/New-EE-10-Standalone-TCKs-and-CI-used-to-test-each-with-GlassFish 

**Describe the solution you'd like**
Create TCK runner scripts/CI jobs to execute the separated TCKs at https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/glassfish-runner to run them against Glassfish 7 for Platform compatibility.   

**Additional context**
Update https://github.com/eclipse-ee4j/jakartaee-tck/wiki/New-EE-10-Standalone-TCKs-and-CI-used-to-test-each-with-GlassFish with the details of new jobs.

Below TCKs need to be covered for this.

- [x] Faces
- [x] Authentication
- [x] Security
- [x] REST
- [x] JSONB
- [x] JSONP
- [x] Concurrency
- [x] Batch

CC @gurunrao @scottmarlow

**Comment by alwin-joseph** [comment]
Status for below 3 : 

> 
>     * [ ]  Faces
> 
CI job https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish-run/ is updated to run Faces TCK against Glassfish 7 full profile.
Issues to be resolved : Test failures in websocket module when using Glassfish M4. 
>     * [ ]  Authentication
> 
CI job https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-authentication-tck-glassfish-run/ created to run the TCK against Glassfish 7 full profile.
Action pending : Need to update the summary.txt to get the final result of tests run.

The new Authentication TCK has a runner for the Authentication tests in jakartaee-tck. Those will be skipped in standalone run and will be part of platform TCK only. There are 2 sets of Authentication tests  - platform TCK and standalone TCK.

>     * [ ]  Security
> 
CI job https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run/ created to run the TCK against Glassfish 7 full profile.
Issues pending : Need to update the summary.txt to get the final result of tests run.


All above jobs are running the TCKs against Glassfish 7 - M4. The same will be done for web profile runs also.

**Comment by gurunrao** [comment]
CI jobs for batch, jsonb, jsonp, rest, concurrency TCK:
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-batch-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-jsonb-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-jsonp-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-rest-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-concurrency-tck-glassfish-run/

^ job needs update for Web Profile and JDK 17 runs.

**Comment by alwin-joseph** [comment]
> Status for below 3 :
> 
> > ```
> > * [ ]  Faces
> > ```
> 
> CI job https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish-run/ is updated to run Faces TCK against Glassfish 7 full profile. Issues to be resolved : Test failures in websocket module when using Glassfish M4.
> 

Hi @arjantijms 

We have setup https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish-run by referring to run logs of successful faces tck run of https://ci.eclipse.org/faces/job/2_faces_run_tck_against_staged_build/13/ . 

1. Can you please confirm below are correct way to execute the faces tests. 

```
# To run old tck: 
cd $WORKSPACE/jakarta-faces-tck-4.0.0
mvn clean install -DskipOldTCK=true -DskipAssembly=true -Pstaging,glassfish-ci-managed -Dglassfish.version=7.0.0-M5 -Dmojarra.version=4.0.0-M7 surefire-report:failsafe-report-only -Daggregate=true

tee $WORKSPACE/run.log

# To run new tests:
cd $WORKSPACE/jakarta-faces-tck-4.0.0/faces-tck
mvn clean install -Dglassfish.version=7.0.0-M5 -Dmojarra.version=4.0.0-M7
tee $WORKSPACE/run_old.log

```

2. I could see test failures in "Mojarra 4.0.0 - Test - Faces 2.3 - websocket" when run with Glassfish M4 (https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish-run/4/) 
and 
test failures in "Mojarra 4.0.0 - Test - Faces 2.2 - Ajax" when run with Glassfish M5 (https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish-run/5/) below exception.

```
[ERROR] ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT.testAjaxUIRepeat  Time elapsed: 0.105 s  <<< ERROR!
com.gargoylesoftware.htmlunit.ScriptException: Error: faces.ajax.request: Form has no view state element (http://localhost:8080/test-faces22-ajax14837877953232646671/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#1)
	at ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT.testAjaxUIRepeat(Issue1817IT.java:45)
Caused by: net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: Error: faces.ajax.request: Form has no view state element (http://localhost:8080/test-faces22-ajax14837877953232646671/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#1)
	at ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT.testAjaxUIRepeat(Issue1817IT.java:45)
```

3. Can you share the steps to generate the final summary of tests as put in summary.txt

**Comment by arjantijms** [comment]
Regarding the web socket failure, we've been getting some reports of intermittant failures. It may be a timing issue, since running it again usually resolves. But it probably means we have to exclude it for now. /cc @BalusC

**Comment by arjantijms** [comment]
From:
https://ci.eclipse.org/faces/job/2_faces_run_tck_against_staged_build/configure

```
stage ("Run TCK tests") {
        env.TCK_BUNDLE_NAME2 = "${TCK_BUNDLE_NAME2}"
        sh '''#!/bin/bash -x
         
            ls -altrh
            echo ${TCK_BUNDLE_NAME2}
            cd ${TCK_BUNDLE_NAME2}
        
            mvn clean install -DskipOldTCK=true -DskipAssembly=true -Pstaging,glassfish-ci-managed -Dglassfish.version=7.0.0-M4 -Dmojarra.version=4.0.0-M7 surefire-report:failsafe-report-only -Daggregate=true | tee ${WORKSPACE}/run.log
        
            cd faces-tck
        
            mvn clean install -Dglassfish.version=7.0.0-M4 -Dmojarra.version=4.0.0-M7 | tee ${WORKSPACE}/run_old.log
        
        
           '''       
    } 
    
    stage ("Create summary.txt, API, and run.log artifacts") {
        env.TCK_BUNDLE_NAME = "${TCK_BUNDLE_NAME}"
        env.TCK_BUNDLE_NAME2 = "${TCK_BUNDLE_NAME2}"
        sh '''#!/bin/bash -ex
        
            cd ${WORKSPACE}/${TCK_BUNDLE_NAME2}
        
           
            mvn org.apache.maven.plugins:maven-site-plugin:3.12.0:site -DskipOldTCK=true -DskipAssembly=true  -Pstaging surefire-report:failsafe-report-only -Daggregate=true -Dglassfish.version=7.0.0-M4 -Dmojarra.version=4.0.0-M7 -Dmaven.test.skip=true -DskipTests=true
            
            cd ${WORKSPACE}
            ls -altrh
            
            ls ${TCK_BUNDLE_NAME2}
            ls ${WORKSPACE}/${TCK_BUNDLE_NAME2}
            ls ${WORKSPACE}/${TCK_BUNDLE_NAME2}/target
            
            cat ${TCK_BUNDLE_NAME2}/target/site/failsafe-report.html
            
            cat ${TCK_BUNDLE_NAME2}/target/site/failsafe-report.html | sed '/table/,/table/!d;//d' | sed '/Package/q' | sed -n 's:.*<td.*>\\(.*\\)</td>.*:\\1:p' > tmp_result.txt
            
            PASSED_COUNT=`cat tmp_result.txt |  sed '1q;d'`
            ERROR_COUNT=`cat tmp_result.txt |  sed '2q;d'`
            FAILED_COUNT=`cat tmp_result.txt |  sed '3q;d'`
            
            
            
            echo "********************************************************************************"  >> summary.txt
            echo "Completed running ${PASSED_COUNT} tests."                                          >> summary.txt
            echo "Number of Tests Failed      = ${FAILED_COUNT}"                                     >> summary.txt
            echo "Number of Tests with Errors = ${ERROR_COUNT}"                                      >> summary.txt
            echo "********************************************************************************"  >> summary.txt
            
            cat run_old.log | sed -e '1,/Completed running/d' >> summary.txt
            
            echo ${TCK_BUNDLE_NAME2}/target/glassfish7/glassfish/modules/${IMPL_JAR_NAME}.jar
            ls ${TCK_BUNDLE_NAME2}/target/
            ls ${TCK_BUNDLE_NAME2}/target/glassfish7/
            ls ${TCK_BUNDLE_NAME2}/target/glassfish7/glassfish/modules/
            
            
            SHA256_IMPL=`sha256sum ${TCK_BUNDLE_NAME2}/target/glassfish7/glassfish/modules/${IMPL_JAR_NAME}.jar | awk '{print $1}'`
            SHA256_TCK=`sha256sum ${WORKSPACE}/download/${TCK_BUNDLE_NAME}.zip | awk '{print $1}'`
            
            echo ERROR_COUNT=${ERROR_COUNT}
            echo FAILED_COUNT=${FAILED_COUNT}
            echo PASSED_COUNT=${PASSED_COUNT}
            
            echo ----
            
            echo SHA256_IMPL=${SHA256_IMPL} | tee -a summary.txt
            echo SHA256_TCK=${SHA256_TCK}  | tee -a summary.txt
         
            echo ----
         
            echo TCK_download=${TCK_BUNDLE_URL} | tee -a summary.txt
            
            echo ----
            
            OS1=`lsb_release -a || true`
            OS2=`cat /etc/issue.net || true`
            OS3=`cat /etc/*_version || true`
            OS4=`cat /etc/*-release || true`
            
            if [ ! -z "${OS1}" ]; then
                echo OS1=${OS1} | tee -a summary.txt
            fi
            if [ ! -z "${OS2}" ]; then
                echo OS2=${OS2} | tee -a summary.txt
            fi
            if [ ! -z "${OS3}" ]; then
                echo OS3=${OS3} | tee -a summary.txt
            fi
            if [ ! -z "${OS4}" ]; then
                echo OS4=${OS4} | tee -a summary.txt
            fi
           
            JDK_VERSION=$(java -version 2>&1 || true)
            
            echo JDK_VERSION=${JDK_VERSION} | tee -a summary.txt
            
           '''
    }
```

**Comment by alwin-joseph** [comment]
Test Failures in Glassfish M5 Full Profile: 
Faces TCK : 

Failing modules : ajax, websocket(intermittent)
Java Version : JDK11
CI : Glassfish Full profile M5 
Jenkins Job : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-faces-tck-glassfish-run/5/ 

failure log for ajax: 
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.188 s <<< FAILURE! - in ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT
[ERROR] ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT.testAjaxUIRepeat  Time elapsed: 0.105 s  <<< ERROR!
com.gargoylesoftware.htmlunit.ScriptException: Error: faces.ajax.request: Form has no view state element (http://localhost:8080/test-faces22-ajax14837877953232646671/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#1)
	at ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT.testAjaxUIRepeat(Issue1817IT.java:45)
Caused by: net.sourceforge.htmlunit.corejs.javascript.JavaScriptException: Error: faces.ajax.request: Form has no view state element (http://localhost:8080/test-faces22-ajax14837877953232646671/jakarta.faces.resource/faces.js.xhtml?ln=jakarta.faces#1)
	at ee.jakarta.tck.faces.test.servlet30.ajax.Issue1817IT.testAjaxUIRepeat(Issue1817IT.java:45)
```

**Comment by alwin-joseph** [comment]
https://github.com/eclipse-ee4j/glassfish/issues/23960 to track test failure in faces-tck 
https://github.com/eclipse-ee4j/glassfish/issues/23959 to track test failure in security tck.

**Comment by gurunrao** [comment]
CI jobs for batch, jsonb, jsonp, rest, concurrency TCK, have been updated for Web Profile runs, job links:
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-batch-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-jsonb-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-jsonp-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-rest-tck-glassfish-run/
https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-concurrency-tck-glassfish-run/

**Comment by gurunrao** [comment]
JSONB TCK failure issue - https://github.com/eclipse-ee4j/jsonb-api/issues/326
Concurrency testsuite Platform TCK Web profile issue: https://github.com/eclipse-ee4j/glassfish/issues/23963
Concurrency TCK failures - https://github.com/eclipse-ee4j/jakartaee-tck/issues/1053

**Comment by alwin-joseph** [comment]
CI jobs for Security TCK :
JDK11 : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run/  
GF Full profile run : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run/17/ 
GF Web profile Run : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run/18/

JDK17 : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run-jdk17/
GF Full profile run : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run-jdk17/1/
GF Web profile Run : https://ci.eclipse.org/jakartaee-tck/job/10/job/jakarta-security-tck-glassfish-run-jdk17/2/

**Comment by gurunrao** [comment]
JSONP, JAXRS, Batch TCK are passing with latest GF 7 nightly build(have been check marked in the issue description).
