### ISSUE TITLE
GlassFish is failing 4 of the RESTful Web Services Platform TCK tests

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#1052]
See discussion on [GlassFish mailing list ](https://www.eclipse.org/lists/glassfish-dev/msg01297.html).

Failing tests:

[jakartaeetck-run / jaxrs / com.sun.ts.tests.jaxrs.platform.container.completioncallback.JAXRSClient.argumentContainsExceptionInTwoCallbackClassesTest_from_standalone](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1859/testReport/com.sun.ts.tests.jaxrs.platform.container.completioncallback/JAXRSClient/jakartaeetck_run___jaxrs___argumentContainsExceptionInTwoCallbackClassesTest_from_standalone/)

https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1859/testReport/com.sun.ts.tests.jaxrs.platform.container.completioncallback/JAXRSClient/jakartaeetck_run___jaxrs___argumentContainsExceptionInTwoCallbackInstancesTest_from_standalone/

https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1859/testReport/com.sun.ts.tests.jaxrs.platform.container.completioncallback/JAXRSClient/jakartaeetck_run___jaxrs___argumentContainsExceptionTest_from_standalone/

https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1859/testReport/com.sun.ts.tests.jaxrs.platform.container.completioncallback/JAXRSClient/jakartaeetck_run___jaxrs___argumentContainsExceptionWhenSendingIoExceptionTest_from_standalone/

**Comment by gurunrao** [comment]
closing, not seen with latest GF nightly build.
