### ISSUE TITLE
Deprecate jakarta.annotation.ManagedBean change needs to be reflected in signature tests for Platform + Common Annotation TCK

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#1059]
Deprecate jakarta.annotation.ManagedBean in Jakarta EE 10 Platform TCK signature tests by running `bash docker/build_signatures.sh` after updating docker/pom.xml to reference updated common annotations artifact that has ^ deprecated.

Then we need to build common annotations TCK + Platform TCK to reflect that change and update GlassFish via pull request as well.

**Comment by starksm64** [comment]
Ok, got it, thanks

**Comment by scottmarlow** [comment]
Comment here when we are ready to build the Platform TCK + Common Annotations TCK (service release).  

We will need to increment the `deliverable.tck.version` from `2.1.0` to `2.1.1` via https://github.com/eclipse-ee4j/jakartaee-tck/blame/master/release/tools/caj.xml#L25 

Then we need to enable https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/ and update the `TCKS_TO_RUN` to include `caj` for `choose source for value` + `choose source for default value`.

**Comment by scottmarlow** [comment]
The TCK tests that depend on `jakarta.annotation.ManagedBean` should be removed when the `jakarta.annotation.ManagedBean` annotation is removed in a later EE release.
