### ISSUE TITLE
5 async timeout Servlet test regression in Full Platform TCK run with nightly GlassFish build on JDK11 on Jun 9, 2022, 3:29 PM (EST?)

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#1065]
This was first noticed yesterday via https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/92/ + https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1872 (which would of run against the previous nights [GlassFish 7 build](https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip).

The failure was not occurring [in our June 7 run](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-10.0-TCK-results#date--2022-06-07 which was started Jun 6, 2022, 8:28 AM and likely using the Sunday night [GlassFish 7 build](https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip).  

So something likely changed between  June 5 - 8 if my determination of when GlassFish nightly build was done for each involved TCK run).

From https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/93/ + https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport:

> 
> Test Result (5 failures  / ±0)
> 
> [Test Result](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport/) (5 failures / ±0)
> [com.sun.ts.tests.servlet.api.jakarta_servlet.asynccontext.URLClient.timeOutTest2](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport/junit/com.sun.ts.tests.servlet.api.jakarta_servlet.asynccontext/URLClient/timeOutTest2/)
>     [com.sun.ts.tests.servlet.api.jakarta_servlet.asynccontext.URLClient.timeOutTest4](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport/junit/com.sun.ts.tests.servlet.api.jakarta_servlet.asynccontext/URLClient/timeOutTest4/)
>     [com.sun.ts.tests.servlet.api.jakarta_servlet_http.asynccontext.URLClient.timeOutTest1](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport/junit/com.sun.ts.tests.servlet.api.jakarta_servlet_http.asynccontext/URLClient/timeOutTest1/)
>     [com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.asynccontext.URLClient.timeOutTest2](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport/junit/com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.asynccontext/URLClient/timeOutTest2/)
>     [com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.asynccontext.URLClient.timeOutTest4](https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/testReport/junit/com.sun.ts.tests.servlet.pluggability.api.jakarta_servlet.asynccontext/URLClient/timeOutTest4/)

The below file attachments are copied from (too big to attach) https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1873/artifact/servlet-results.tar.gz:
 
[Test run output run_jakartaeetck.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/8879122/run_jakartaeetck.zip)

[serverlog.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/8879128/serverlog.zip)

**Comment by dmatej** [comment]
Could we repeat the build? Yesterday were some issues with Jenkins, seems we pushed too many things and the build server was quite bussy so even PR builds had to wait quite long. I will try to reproduce it locally for sure, but on wednesday servlet TCK passed locally (except one test depending in mail service which I did not set locally).
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/

**Comment by scottmarlow** [comment]
:+1: on the possibility that Jenkins is at fault, I like that theory and hope that is the case.  I did see the test failure happen in two Jenkins test runs already but that doesn't mean much.

Just started https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/94/ + https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1874/

**Comment by scottmarlow** [comment]
https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/96/ + https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/97/ both passed the Servlet tests (and other Platform TCK tests as well!).  This covered both JDK11 + JDK17.  Thanks @dmatej for the fix!
