### ISSUE TITLE
cts-base Docker image port 8080 collides with GlassFish

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/jakartaee-tck#11]
Following the instructions on the Wiki, the cts-base Docker image opens a server on port 8080. That port collides with GlassFish when it's being tested.

The UUID registry should ideally expose a different port.

**Comment by anajosep** [comment]
In my latest [commit](https://github.com/eclipse-ee4j/jakartaee-tck/commit/1e206b988f94ed7957b316643e46027bc19fc222), I have provided an option to override the UDDI_REGISTRY_URL through environment variable. I have updated the run instructions in [this ](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Instructions-for-building-and-running-JakartaEE-TCK-bundle)wiki page as well.

**Comment by ggam** [comment]
Thanks, I think the updated Wiki makes it clear enough.
