### ISSUE TITLE
Change to run jaxr signature tests and functional tests together

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#114]
jaxr signature test is now run by a separate ant task unlike other TCKs line : https://github.com/eclipse-ee4j/jakartaee-tck/blob/4687f0a79e3ce4f25b8505a7281b603de6455ae9/docker/jaxrtck.sh#L87 .

We need to make changes to jaxr run.all target to include signature test too.

**Comment by andymc12** [comment]
This can probably be closed since JAXR is being removed from the TCK - see issue #209

**Comment by scottmarlow** [comment]
Thanks @andymc12, closing due to reason you stated (JAXR (javax.xml.registry) being pruned from Jakarta EE 9).
