### ISSUE TITLE
Remove jwsdp dependency on jaxr test runs.

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#115]
We use jwsdp-1.3 as a UDDI Registry Server which requires JavaSE1.4 to work.

We should be able to use any registry server. Need to experiment  with jUDDI (http://juddi.apache.org/) or anything that works.

**Comment by gurunrao** [comment]
closing current issue, since  https://github.com/eclipse-ee4j/jakartaee-tck/issues/606 has been raised to remove jwsdp dependency.
