### ISSUE TITLE
Create new branch for Jakartaee8

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#117]
The existing EE4J_8 branch is currently stale and is not used for any developments or job execution from jenkins CI.

The latest changes for jakartaee8 are all in master branch. We need to create a separate branch for jakartaee8 release or use the current EE4J_8 by merging all the new changes from master.

**Comment by scottmarlow** [comment]
What would we like to use for the jakartaee8 branch name?  Perhaps branch name "jakartaee8"?

IMO, EE4J_8 sounds okay for a branch name that we will actively maintain in the future, as well.  If we do that, I am thinking we could rename the current EE4J_8 to EE4J_8_SOMETHING (EE4J_8_OLD or better), then create a new EE4J_8 from master.

**Comment by bshannon** [comment]
All the EE4J_8 branches should've been merged and deleted long ago.  I know some projects
haven't done that yet, but it's time.

We don't need a branch for Jakarta EE 8, but we do need a tag for the 8.0.0 release of the TCK.
Going forward, we need to decide whether master will be used for 8.0.x maintenance releases,
or whether it will be used for advanced 9.0.0 development.  In the latter case, we can create a
branch from the 8.0.0 tag to do more 8.0.x releases.

**Comment by alwin-joseph** [comment]
@gurunrao FYI

Current status: 
1. I have removed the old(stale) EE4J_8 branch.
2. New branch  8.0.0 created , changes released as JakartaEE TCK 8.0.0.

3. New branch 8.0.1 created which has the jsonb 1.0.1 changes in addition to 8.0.0, released as Jakarta EE TCK 8.0.1  & jsonb tck 1.0.1 also generated from this branch.

4. Will continue making future changes in master until decided otherwise.

As Bill suggested we can have tags instead of 8.0.0 & 8.0.1 branches , if required.

**Comment by bshannon** [comment]
Everything in the branches is in master as well, right?

As long as there's a simple linear history, I prefer tags.

**Comment by gurunrao** [comment]
@bshannon - we have created v8.0.1 and v8.0.0 tags and deleted corresponding branches.

**Comment by bshannon** [comment]
The convention we're using is to name the tags without the "v", e.g., "8.0.0" and "8.0.1".

**Comment by gurunrao** [comment]
@bshannon - have renamed according convention "8.0.0" and "8.0.1" without v.

**Comment by alwin-joseph** [comment]
> Everything in the branches is in master as well, right?
Yes
> 
> As long as there's a simple linear history, I prefer tags.

Now that we have tags for 8.0.0 & 8.0.1 releases, we will continue to use the master branch for post 8.0.1 changes. I am assuming that no more changes are required in 8.0.1 version.

**Comment by bshannon** [comment]
> I am assuming that no more changes are required in 8.0.1 version.

That's correct.  I've released the 8.0.1 version.  Further changes would go in an 8.0.2 version.
