### ISSUE TITLE
Create revised CTS bundle to pick up changes in JSON B test challenge

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-tck#118]
Please build new version of Jakarta EE 8 CTS release that includes changes required by probable accepted test challenge [jsonb-api#180](https://github.com/eclipse-ee4j/jsonb-api/issues/180). As a working presumption, this will be Jakarta EE CTS 8.0.1.

**Comment by gurunrao** [comment]
New CTS 8.0.1 has been created based on JSONB test challenge.
EPL bundles: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8/promoted/
EFTL bundles: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/promoted/
