### ISSUE TITLE
CTS on JDK11

### ISSUE THREAD

**Issue by gengyanyu** [eclipse-ee4j/jakartaee-tck#145]
This is a request from Steve:

We recently figured out that no one had run the CTS on JDK11 and that’s the one that we will initially certify.
I made a minor change to fix the local set-up on Linux.

The next big steps are the following.
1. We need for the RI to run on JDK8 all the time while the vendor implementation (WLS) runs on whatever JV is set to (defaults to JDK8).  I know that we have multiple JDK’s for doing functional build/test and in the old days we had dual compilers for JDK3/JDK4 but I don’t think we have anything now to handle this.  We could introduce a new RI_JDK_HOME or RI_JV or something.  I’ll leave that to the infra team.

2. The RI uses $endorsed.dirs.ri to set the endorsed directory option for the JVM and the vendor implementation uses $endorsed.dirs.  However for JDK11, it’s a fatal error to provide the endorsed directory option.  So if we detect that we are running on JDK11+, we need for all scripts to not use the endorsed directory command line option at all.  The porting layer is under src123100/wls/tools/weblogic/qa/tests/cts8.vi.  JDK11 should not need the endorsed directory because the JDK has removed Java EE classes from Java SE and we have our own copies of these jar files.

We need these two steps completed before we can see what else is broken.

**Comment by gengyanyu** [comment]
I have set $RI_JAVA_HOME by running devenv, and update command.testExecuteAppClient2 and command.testExecute2 in my local ts.jte to use $RI_JAVA_HOME instead of $JAVA_HOME, but I don't know if other part of TCK also need to update to use $RI_JAVA_HOME.

About part2, I guess Steve means the vi endorsed.dirs need to remove when vi using JDK11.

**Comment by gurunrao** [comment]
CTS runs on JDK11 as of Jakarta EE 9.1
