### ISSUE TITLE
Convert batch (jbatch) TCK tests from javax.* -> jakarta.* packages, and from JCP -> Jakarta targetNamespace

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/jakartaee-tck#162]
As part of EE 9 release plan: eclipse-ee4j/batch-api#7:
- [X] Java package rename (#161)
- [ ] XML namespace rename

**Comment by scottmarlow** [comment]
@scottkurz [https://github.com/eclipse-ee4j/jakartaee-tck/pull/161] contains some changes [for batch](https://github.com/eclipse-ee4j/jakartaee-tck/pull/161/commits/297da38b41963987e272131e1a2393b3a61ae8a6).

**Comment by scottkurz** [comment]
More discussion in the #161 PR

**Comment by scottmarlow** [comment]
@scottkurz I'm going to close this, as I think you completed the change needed.  Please reopen if more changes are needed.  Thanks again for helping!

**Comment by scottkurz** [comment]
It looks like we never completed moving the batch job XMLs to the new Jakarta schema, even though we have changes like e50d9d447 that updated some of the "vehicle" XMLs.   Re-opening.
