### ISSUE TITLE
com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java#leapYears failed due to wrong expected timeout

### ISSUE THREAD

**Issue by chengfang** [eclipse-ee4j/jakartaee-tck#163]
When running with WildFly, the following 4 tests failed due to the wrong expected next timeout value computed by the test:

```
com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java\#leapYears_from_ejblitejsf 
com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java\#leapYears_from_ejblitejsp 
com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java\#leapYears_from_ejbliteservlet 
com/sun/ts/tests/ejb32/lite/timer/schedule/expire/Client.java\#leapYears_from_ejbliteservlet2 
```

The relevant part of the test output shows that a timer is created to expire on Feb 29, 2028 **2:31:27**, and the test expects the next timeout to be Feb 29, 2028 **03:31:27**, but the actual next timeout is Feb 29 **02:31:27**.

The test timer has a time (Feb 29 02:31:27) that falls in US Standard Time, while the test execution date (Mar 12) is in US Daylight Saving Time, which is one hour ahead of US Standard Time. The test computes the expected timeout value based on the test execution time by setting year, month and day field, hence resulting in one hour ahead of the configured hour.

```
Mar 12, 2020 2:31:27 AM com.sun.ts.tests.common.vehicle.ejbliteshare.EJBLiteWebVehicleRunner run
INFO: Connecting http://localhost:8080/ejb32_lite_timer_schedule_expire_ejblitejsf_vehicle_web/faces/ejblitejsf_vehicle.jsp?testName=leapYears
<html>
    <head><title>leapYears_from_ejblitejsf</title></head>
    <body>
        [TEST FAILED] testName=leapYears 
Created a timer with expression year=2025-2028 month=2 dayOfMonth=29, 29 dayOfWeek=* hour=2 minute=31 second=27 start=null end=null timezone=null
Compare expected nextTimeout Tue Feb 29 03:31:27 EST 2028, and actual nextTimeout Tue Feb 29 02:31:27 EST 2028
```

**Comment by bshannon** [comment]
Can you submit a Pull Request to fix these tests?

**Comment by chengfang** [comment]
Sure, I'll give it a try.

**Comment by scottmarlow** [comment]
Cheng, thanks for the fix, since your change is merged now to master, I will close this issue.
