### ISSUE TITLE
Test depending on annotations scanning but web.xml has version="2.5"

### ISSUE THREAD

**Issue by olamy** [eclipse-ee4j/jakartaee-tck#177]
The test com.sun.ts.tests.servlet.api.javax_servlet_http.httpservletrequestwrapper#changeSessionIDTest1 need the HttpSessionIdListener from TCKHttpSessionIDListener activated via annotations https://github.com/eclipse-ee4j/jakartaee-tck/blob/c457c40af61d307b0dea0e0489fed7ab4c3e8490/src/com/sun/ts/tests/servlet/api/javax_servlet_http/httpservletrequestwrapper/TCKHttpSessionIDListener.java#L27
But the web.xml file has version="2.5" https://github.com/eclipse-ee4j/jakartaee-tck/blob/c457c40af61d307b0dea0e0489fed7ab4c3e8490/src/com/sun/ts/tests/servlet/api/javax_servlet_http/httpservletrequestwrapper/servlet_jsh_HSReqWrapper_web.xml#L20

Annotations are available only >= 3.0
I'm happy to provide a pr. The simple fix is maybe to change version to 3.0. 
WDYT?

**Comment by markt-asf** [comment]
I recommend resolving this as invalid based on the text in section 1.6.1 of the Servlet 4.0 specification.

> The version of the descriptor MUST not affect which annotations the container scans for
in a web application. An implementation of a particular version of the specification
MUST scan for all annotations supported in that configuration, unless metadata-
complete is specified.

(I can't close this issue as I'm not a TCK committer.)

**Comment by janbartel** [comment]
As the spec does now contain this text, I agree this issue can be closed:  I disagree that this particular text should have been added to the spec in the first place, however that is beyond the scope of this issue.

**Comment by bshannon** [comment]
Annotations are available independent of the web app descriptor syntax version.
(Think of the descriptor version as similar to the charset - it tells you how to interpret
the format of the descriptor, it says nothing about the semantics of the content nor
of the associated APIs.)

If the test has a web app 2.5 version description and does not set metadataComplete,
then the app is expecting annotations to be processed.

@olamy @markt-asf   Why do you think the test is invalid?

**Comment by janbartel** [comment]
@bshannon in servlet 2.5 metadata-complete=false or missing just meant that the webapp could use a few common annotations like @Resource etc etc.  It did not imply scanning of the whole webapp: that is a container implementation detail - some containers did not scan but just introspected individual servlet artifacts before putting them into service.

Thus, a webapp that had not changed _at all_ but deployed to a more updated version of the container was suddenly subjected to a possibly lengthy forced scan of the whole webapp, impacting startup time. Moreover, sometimes servlet 3.0 annotations were discovered that were lurking in 3rd party libs in the webapp that conflicted with the webapp itself. The webapp could not set metadata-complete=true to prevent scanning without losing the ability to use @Resource etc.

After these complaints jetty took the position that if web.xml < 3.0 then the webapp would largely get 2.5 behaviour, except for ServletContainerInitializers that were present on the _container's classpath_.  We made this behaviour configurable via a container-specific mechanism.

**Comment by bshannon** [comment]
> @bshannon in servlet 2.5 metadata-complete=false or missing just meant that the webapp could use a few common annotations like @resource etc etc. It did not imply scanning of the whole webapp: that is a container implementation detail - some containers did not scan but just introspected individual servlet artifacts before putting them into service.

There's a separate description of which files need to be scanned, but it comes down to
effectively every class because of the CDI requirements.

> Thus, a webapp that had not changed _at all_ but deployed to a more updated version of the container was suddenly subjected to a possibly lengthy forced scan of the whole webapp, impacting startup time. Moreover, sometimes servlet 3.0 annotations were discovered that were lurking in 3rd party libs in the webapp that conflicted with the webapp itself. The webapp could not set metadata-complete=true to prevent scanning without losing the ability to use @resource etc.

Yes, this is a risk.  Most of the products have done work to optimize the scanning,
but given a very large legacy app that scanning can be non-trivial part of the
deployment time.

I have less sympathy for files that used the annotations and expected them to be
ignored.

> After these complaints jetty took the position that if web.xml < 3.0 then the webapp would largely get 2.5 behaviour, except for ServletContainerInitializers that were present on the _container's classpath_. We made this behaviour configurable via a container-specific mechanism.

Ya, that's not spec compliant.

I believe all these issues were discussed in the servlet and platform expert groups
and they led us to where we are today.  I don't really want to revisit them but if
you feel there's a need to introduce a new requirement for a container-specific
mechanism for more fine grained control of the behavior in this area, that could
be considered for any Servlet spec revision, although it's probably outside the
bounds of what were were expecting for Jakarta EE 9.  Still, you're free to bring
it up with the platform team if you think it's critically important, but otherwise
you expect to implement it as currently specified.

**Comment by bshannon** [comment]
And to close the loop, we agree there's nothing wrong with the TCK test based
on the current spec, correct?

**Comment by janbartel** [comment]
Considering that the genie was already let out of the bottle and it's too late to stuff it back in, I agree that this test is spec compliant. I would personally rather see this test deleted as it highlights a less than stellar aspect of the spec, but I'm fine if consensus is to keep it.

**Comment by markt-asf** [comment]
To quote Jan Luehe quoting bshannon back in 2009 in the Servlet 3.0 EG:

>  The version number in a deployment descriptor does *not* mean "this is
>  the version of the platform I'm expecting".  It only means "this is the
 > version of the data file format you're about to read".  Changing the
 > behavior of the platform based on the data file format is a mistake.
> 
>  (Sadly, it's a mistake we've made a few times, but not one we should
>  keep making.)

I'd forgotten this and have just found it again. I'm adding it here as I think it is useful to have this sort of concept in mind as we continue to develop Jakarta EE as it helps us keep things consistent.

**Comment by bshannon** [comment]
Thanks @markt-asf, there's a continuing temptation to base program behavior on
the data file format and we need to resist that temptation.  As I also said above, it's
like changing the API behave based on the charset used to encode the data.  That
would be wrong.
