### ISSUE TITLE
jakarta.ejb.SessionContext#getMessageContext() was removed from API

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jakartaee-tck#184]
Tests that are using jakarta.ejb.SessionContext#getMessageContext() can't be build because `SessionContext` does not contain this method in current release.

I commented out those pieces of code in https://github.com/eclipse-ee4j/jakartaee-tck/pull/182 but it may require closer review.

**Comment by scottmarlow** [comment]
I found this first mentioned on [jakartaee-platform-dev/msg00895](https://www.eclipse.org/lists/jakartaee-platform-dev/msg00895.html) and it looks like the git commit that applied the change is [eclipse-ee4j/ejb-api commit 79e61326](https://github.com/eclipse-ee4j/ejb-api/commit/79e61326e4ae0c96d15a46bc38d302e29b0ab3fa#diff-cc86a6cd3329955fcef82986e55487db)

**Comment by scottmarlow** [comment]
We can cross reference the tally of the voting to remove Jakarta XML RPC  JSR 101 from Jakarta EE 9, to confirm this method should indeed be missing and the TCK updated to not test jakarta.ejb.SessionContext#getMessageContext()

**Comment by scottmarlow** [comment]
Yeah, https://blogs.oracle.com/javamagazine/transition-from-java-ee-to-jakarta-ee mentions that JAX_RPC is pruned.

**Comment by Tomas-Kraus** [comment]
Affected sources:
- src/com/sun/ts/tests/ejb/ee/bb/session/stateless/bm/allowedmethodstest/TestBeanEJB.java
- src/com/sun/ts/tests/ejb/ee/bb/session/stateless/cm/allowedmethodstest/TestBeanEJB.java
- src/com/sun/ts/tests/ejb/ee/webservices/allowedmethodstest/bm/TestBeanEJB.java
- src/com/sun/ts/tests/ejb/ee/webservices/allowedmethodstest/cm/TestBeanEJB.java
- src/com/sun/ts/tests/ejb30/common/allowed/Operations.java
- src/com/sun/ts/tests/ejb30/lite/ejbcontext/common/EJBContextBeanBase.java

**Comment by scottmarlow** [comment]
I believe that the expected changes have been made for this issue, so will close it.
