### ISSUE TITLE
Adopt jakarta.persistence in JPA tests.

### ISSUE THREAD

**Issue by Tomas-Kraus** [eclipse-ee4j/jakartaee-tck#195]

**Comment by Tomas-Kraus** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/196 is ready to be merged.

**Comment by scottmarlow** [comment]
Closing as pr is merged. thanks again @Tomas-Kraus!

**Comment by Tomas-Kraus** [comment]
Thanks. I'll setup EclipseLink job to verify if JPA tests works.
