### ISSUE TITLE
tracker for completion of Platform 9.0.0 TCK

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#207]
1. Complete the javax => jakarta class namespace changes  [done]
2. Complete the [javax => jakarta file name changes ](https://github.com/eclipse-ee4j/jakartaee-tck/issues/229)  [ 100% done ]
3. [Remove EJB interoperability](https://github.com/eclipse-ee4j/jakartaee-tck/issues/208)  [done ]
4.  [Remove Jakarta XML Registries](https://github.com/eclipse-ee4j/jakartaee-tck/issues/209)  [done ]
5.  [Remove Jakarta XML RPC](https://github.com/eclipse-ee4j/jakartaee-tck/issues/210) [ done]
6.  [Remove Jakarta Deployment](https://github.com/eclipse-ee4j/jakartaee-tck/issues/211)  [ done ]
7.  [Remove Jakarta Management](https://github.com/eclipse-ee4j/jakartaee-tck/issues/212)  [ done ]
7.1. [Resolve errors in jakartaee-tck build ](https://github.com/eclipse-ee4j/jakartaee-tck/issues/253) [ done ]
8.  [Update signature tests for JDK 8](https://github.com/eclipse-ee4j/jakartaee-tck/issues/219)  [ done ]
9.  Defer Update TCK tests for JDK 11, also work with JDK 8](https://github.com/eclipse-ee4j/jakartaee-tck/issues/213)  [defer to after 9.0.0 release]
10. [Update Jenkins CI jobs to release nightly build of 9.0.0 platform TCK (produce 9.0.0-SNAPSHOT or 9.0.0-b## artifacts)](https://github.com/eclipse-ee4j/jakartaee-tck/issues/271)  [done]
10.1. [Ensure that standalone TCK version numbers have been incremented](https://github.com/eclipse-ee4j/jakartaee-tck/issues/279)  [ done ]
11. [Update scripts to use final released Jakarta EE 9 SPEC API jars](https://github.com/eclipse-ee4j/jakartaee-tck/issues/270)  [done]
12. [After GlassFish 6.0 passes all standalone/Platform TCKs, run TCK release jobs](https://github.com/eclipse-ee4j/jakartaee-tck/issues/269)  [  ]
13. [Update TCK README.md + wiki](https://github.com/eclipse-ee4j/jakartaee-tck/issues/268) [  ]
14. [Run/pass TCK release CI jobs for Platform 9.0.0 TCK and all standalone TCKs](https://github.com/eclipse-ee4j/jakartaee-tck/issues/267)  [  ]
15. [Update lib/schemas references (e.g. install, release, tests under src) to use either EE 9 or Jakarta EE 8 schemas (as per Jan 21, 2020 VOTE: backward compatibility for descriptor schemas)](https://github.com/eclipse-ee4j/jakartaee-tck/issues/266) [ done ]
16. [Update configuration settings for GlassFish 6.0 configuration](https://github.com/eclipse-ee4j/jakartaee-tck/issues/239) [ done]

**Comment by scottmarlow** [comment]
@bshannon @jansupol what other EE 9 Platform TCK tasks do we need to add to this tracker issue?  Thanks! :)

**Comment by bshannon** [comment]
Hopefully #10 would produce 9.0.0-SNAPSHOT or 9.0.0-b## artifacts.

I don't understand #11.  The current platform API jar file job pulls the artifacts from Maven, not from GlassFish.

Depending on the magnitude of changes, the TCK Users Guide will probably also need to be updated.

Don't forget that everything needs to be "duplicated" for full platform and web profile.

**Comment by scottmarlow** [comment]
> I don't understand #11. The current platform API jar file job pulls the artifacts from Maven, not from GlassFish.

Currently, as per comment in [docker/build_jakartaeetck.sh#L98](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker/build_jakartaeetck.sh#L98), we are temporarily pulling the artifacts from Maven, until we have GlassFish v6 with new api jars.  

I like the idea of downloading API jars from Maven, instead of copying them from GlassFish.  Apparently, we didn't do that before.

**Comment by bshannon** [comment]
I think we should keep pulling them from Maven.  I'll see if I can find out the history of why
we didn't always do that.

**Comment by scottmarlow** [comment]
Should we block the Platform TCK 9.0.0 release on #15 being done?  I think yes, as per Platform mailing list vote on Jan 21 results that were in favor of:
```
3. Support for Jakarta EE 8 *but not* earlier schemas is *required* in
   Jakarta EE 9 products; support for schemas earlier than Jakarta EE 8
   is *optional* in Jakarta EE 9 products.
```

**Comment by edbratt** [comment]
Perhaps after (2) this project should start producing snapshot stand-alone TCKs for the API and Implementation teams to use in their work.

**Comment by edbratt** [comment]
Consider if this effort should change the stage names. In CI properties and in test output, these use legacy names (i.e. jaspic, jacc, etc.).
