### ISSUE TITLE
Remove test of Jakarta XML Registries 

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#209]
As per [release plan](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan), look for references to javax.xml.registry + javax.xml.registry.infomodel and remove tests.

**Comment by gerdogdu** [comment]
Can you please merge other package removal pull requests into upstream to work on this?

**Comment by scottmarlow** [comment]
Thanks again @gerdogdu!
