### ISSUE TITLE
Remove use of Jakarta Deployment 

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#211]
Look for use of Jakarta Deployment and remove use of: javax.enterprise.deploy.model, javax.enterprise.deploy.model.exceptions, javax.enterprise.deploy.shared, javax.enterprise.deploy.shared.factories, javax.enterprise.deploy.spi, javax.enterprise.deploy.spi.exceptions, javax.enterprise.deploy.spi.factories, javax.enterprise.deploy.spi.status

Also document impact on use of Platform TCK.

**Comment by scottmarlow** [comment]
Regarding the impact of removing javax.enterprise.deploy, src/com/sun/ts/lib/porting/TSDeploymentInterface2.java is based on the deployment model, which is likely used by some Jakarta EE server implementations for testing against the Platform TCK.

Investigate the below classes to help determine the impact of removing Deployment:
src/com/sun/ts/lib/deliverable/cts/deploy/OperationStatus.java
src/com/sun/ts/lib/deliverable/cts/deploy/DeployTestUtil.java
src/com/sun/ts/lib/deliverable/cts/deploy/StandardDeployment14.java
src/com/sun/ts/lib/implementation/sun/javaee/SunRIDeployment2.java

**Comment by arjantijms** [comment]
@dblevins mentioned a blocker here could be that the TCK uses Jakarta Deployment itself to deploy tests unrelated itself to Jakarta Deployment.

However, the web profile doesn't have Jakarta Deployment, so at least everything in that profile must be using something else to deploy tests. Maybe the tests that now use Jakarta Deployment to deploy tests can be updated to use whatever the web profile tests are using?

**Comment by scottmarlow** [comment]
True, GlassFish v6 will not likely include a JSR-88 implementation.  This will impact other EE implementations as well.

**Comment by scottmarlow** [comment]
> Maybe the tests that now use Jakarta Deployment to deploy tests can be updated to use whatever the web profile tests are using?

I need to refresh my memory on the TCK deployment interfaces.  I think your right but I forget what all of the options are.  

I wonder if it would be allowed to repackage some JSR-88 impl + api classes under a different package name, so they could be used for deployment (along with updated com.sun.ts.lib.deliverable.cts.deploy classes that also use the repackaged JSR-88 classes).

**Comment by scottmarlow** [comment]
Jakarta EE implementations may currently use an implementation of com.sun.ts.lib.porting.TSDeploymentInterface2 (JSR-88 based) + com.sun.ts.lib.porting.TSDeploymentInterface (not JSR-88 based), for running the Platform TCK.  

So, I think there are a few options to choose from that are worth raising on a mailing list for discussion:

- Least impact on setting up to run the Jakarta EE 9 Platform TCK by adding the JSR-88 classes to the Platform TCK (e.g. use release from https://github.com/eclipse-ee4j/management-api), so that the Platform TCK com.sun.ts.lib.porting.TSDeploymentInterface2 can continue to depend on JSR-88, as well as Jakarta EE 9 implementations.

- Update com.sun.ts.lib.porting.TSDeploymentInterface2 to somehow not depend on javax.enterprise.deploy.spi.  We could look into implementing a replacement for TSDeploymentInterface2 that doesn't use JSR-88 classes, which I'll leave as an option as well.

**Comment by scottmarlow** [comment]
Note feedback from [jakartaee-platform-dev ml discussion on April 22, 2020](https://www.eclipse.org/lists/jakartaee-platform-dev/threads.html#01700).  

Also [Platform meeting notes for April 28, 2020](https://eclipse-ee4j.github.io/jakartaee-platform/minutes/2020-04-28.html)

**Comment by scottmarlow** [comment]
Regarding deployment API, since EE 9 implementations can no longer depend on JSR-88, they will need to expose an equivalent facility in their EE implementations and have a Platform TCK replacement for the JSR-88 interfaces (e.g. the new TCK SPI for deployment) that they can adapt their EE server implementation to use, in their porting library.  

@starksm64 is ^ what you had in mind regarding a new TCK SPI for deployment?

cc @dblevins does ^ address your concern about dropping JSR-88 support from the Platform TCK?

**Comment by scottmarlow** [comment]
Perhaps the new TCK deployment SPI could be a fork of the JSR-88 interfaces, only without the javax package (e.g. switch for jakarta).

**Comment by scottmarlow** [comment]
> @dblevins mentioned a blocker here could be that the TCK uses Jakarta Deployment itself to deploy tests unrelated itself to Jakarta Deployment.
> 
> However, the web profile doesn't have Jakarta Deployment, so at least everything in that profile must be using something else to deploy tests. Maybe the tests that now use Jakarta Deployment to deploy tests can be updated to use whatever the web profile tests are using?

I'm guessing that @dblevins is talking about the com/sun/ts/tests/servlet/ee/platform/negdep tests calling Jakarta Deployment classes, with regard to the TCK using Jakarta Deployment itself to deploy tests unrelated to Jakarta deployment.  

Currently, the src/com/sun/ts/lib/harness/keyword.properties file has the negdep tests as javaee_web_profile_optional but that doesn't really help us, but thought I would mention it:
`com/sun/ts/tests/servlet/ee/platform/negdep = javaeedeploy javaeedeploy_optional javaee_optional javaee_web_profile_optional
`

IMO, if we replace use of Jakarta Deployment with a new Platform TCK porting layer SPI  (e.g. jakarta.enterprise.deploy.* or something), then we could update the com/sun/ts/tests/servlet/ee/platform/negdep tests to use that.  

Another (later) option could be removing the src/com/sun/ts/tests/servlet/ee/platform/negdep tests if we cannot get them to work.

**Comment by scottmarlow** [comment]
Regarding the tests that deploy tests unrelated itself to Jakarta Deployment, they appears to be under com/sun/ts/tests/servlet/ee/platform/negdep, which I think are technically Jakarta Deployment related as per how they are classified in keyword.properties:

`com/sun/ts/tests/servlet/ee/platform/negdep = javaeedeploy javaeedeploy_optional javaee_optional javaee_web_profile_optional`

So, if we pruned Jakarta Deployment from Jakarta EE 9, I think that we should also remove the negative deployment tests.

user_guides/jakartaee/src/main/jbake/content/using.adoc, shows the mapping of Jakarta Deployment to javaeedeploy_optional:
```
Table 7-1 Keyword to Technology Mappings for Full Profile Optional
|Jakarta Deployment |`javaeedeploy_optional` or `javaee_optional`
```
Based on this, I'll add a commit for removing the com/sun/ts/tests/servlet/ee/platform/negdep tests.

**Comment by scottmarlow** [comment]
Since GlassFish 6.0 is expected to remove the pruned Jakarta Deployment classes, what should the com.sun.ts.lib.implementation.sun.javaee.SunRIDeployment2 use instead of Jakarta Deployment?

**Comment by scottmarlow** [comment]
Could GlassFish 6.0 switch to use com.sun.ts.lib.porting.TSDeploymentInterface based deployment via com.sun.ts.lib.implementation.sun.javaee.glassfish.AutoDeployment?  

Some comments from AutoDeployment:
```
This class implements the TSDeploymentInterface. It does so by copying
to/from the V3 autodeploy directory and delegates out to ant build files
under bin/xml/glassfish/deploy.xml
```

**Comment by scottmarlow** [comment]
It seems to me that the Jakarta Platform TCK already has a standard SPI that can work without Jakarta Deployment and that is com.sun.ts.lib.porting.TSDeploymentInterface, so no new SPIs are needed.

Instead, I think that any user that depends on the current com.sun.ts.lib.porting.TSDeploymentInterface2 should be able to switch to com.sun.ts.lib.porting.TSDeploymentInterface which doesn't depend on Jakarta Deployment, which is fine since Jakarta EE 9 implementations will not have Jakarta Deployment implementation code any more.

I think that option C makes sense, we just need com.sun.ts.lib.porting.TSDeploymentInterface2 to be the same as com.sun.ts.lib.porting.TSDeploymentInterface (e.g. no Jakarta Deployment dependencies).
