### ISSUE TITLE
Update TCK tests for JDK 11

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#213]
Need to update TCK tests as needed for JDK 11.  See [Java SE Version](https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan) section:

> Java SE Version
> 
> For inclusion in Jakarta EE 9, specification’s APIs MUST be compiled at the Java SE 8 source level. However, compatible implementations of the Jakarta EE 9 Web Profile and Full Profile MUST certify compatibility on Java SE 11. Compatible Implementations MAY additionally certify and support Java SE 8.
>

**Comment by scottmarlow** [comment]
This looks like it may be a duplicate of [issue#145](https://github.com/eclipse-ee4j/jakartaee-tck/issues/145) but will leave it open for now.  If we do close it as a duplicate, we should update [top level tracker issue #207](https://github.com/eclipse-ee4j/jakartaee-tck/issues/207) to refer to issue#145.

**Comment by scottmarlow** [comment]
Another thing that we could do is determine whether its quicker to compare for the exact set of "javax..." sequences that we have to match against, versus matching against the set of "javax..." that we know do not match.

For example, the set of "javax..." sequences that we will match against, are shown in [ASM TransformerImpl.java#L304](https://github.com/wildfly-extras/batavia/blob/master/impl/asm-based-transformer/src/main/java/org/wildfly/transformer/asm/TransformerImpl.java#L304), has 34 entries in the set.  If the set of sequences that we don't want to match, has fewer entries (e.g. "javax.transaction.xa" + others), then its more efficient to only check for the smaller set of possible string values being passed to Class.forName().

**Comment by scottmarlow** [comment]
[Found ee4j_build mailing list conversation about switching jdk](https://www.eclipse.org/lists/ee4j-build/msg00217.html), we can try this soon.

**Comment by dmkavanagh** [comment]
Anything a newbie can do to help?

**Comment by scottmarlow** [comment]
Excellent question @dmkavanagh 
Once we know what the TCK failures are on JDK 11, help will be appreciated in updating (failing) tests to work on JDK 11 (as well as on JDK 8).

Thanks!
