### ISSUE TITLE
javax.jws => jakarta.jws Jakarta Web Services Metadata

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#228]
We still have references to javax.ws classes, as I noticed the following Platform TCK compile error:
```
metadatacomplete/testapp -wsdl:soap1.1 -r /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/appclient/deploy/metadatacomplete/testapp com.sun.ts.tests.appclient.deploy.metadatacomplete.testapp.HelloImpl
    [wsgen] Picked up JAVA_TOOL_OPTIONS: -Xmx6G
    [wsgen] Exception in thread "main" com.sun.xml.ws.model.RuntimeModelerException: A WebService annotation is not present on class: com.sun.ts.tests.appclient.deploy.metadatacomplete.testapp.HelloImpl
```
The src/ts/tests/appclient/deploy/metadatacomplete/testapp/HelloImpl.java is importing javax.jws.WebService, there are other references to javax.jws package as well.

Suggested action is search and replace, something like:
```
ag --ignore .git  -l javax.jws| xargs sed -i 's/javax\.jws/jakarta\.jws/g'
```
Be sure to revert changes to signaturetest folder and update Copyright date.

**Comment by RohitKumarJain** [comment]
required changes are present under: https://github.com/eclipse-ee4j/jakartaee-tck/commit/1ffee94c59a920907b3280a4fac2704252fc47e7

**Comment by alwin-joseph** [comment]
@RohitKumarJain I reviewed the commit, the changes look fine to me. Please create a PR from next time. 

+ @scottmarlow

**Comment by RohitKumarJain** [comment]
sure @alwin-joseph

**Comment by RohitKumarJain** [comment]
@alwin-joseph , do we have any pending work for this issue? IMO, required work has been done and it can be closed.

**Comment by RohitKumarJain** [comment]
@alwin-joseph , can we close this issue?
