### ISSUE TITLE
Complete the javax => jakarta file name changes

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#229]
Rename the folders (+ files) like src/com/sun/ts/tests/jsf/api/javax_faces after package change to jakarta namespace is done.

**Comment by alwin-joseph** [comment]
Folder name changes required for below to jakarta*:

src/com/sun/ts/tests/servlet/api/javax_servlet
src/web/jsp/api/javax_servlet
src/com/sun/ts/tests/jaxws/api/javax_xml_ws_handler_soap
src/com/sun/ts/tests/jaxws/api/javax_xml_ws_http
src/com/sun/ts/tests/jaxws/api/javax_xml_ws_handler
src/com/sun/ts/tests/jaxws/api/javax_xml_ws
src/com/sun/ts/tests/jaxws/api/javax_xml_ws_wsaddressing
src/com/sun/ts/tests/jaxws/api/javax_xml_ws_soap
src/com/sun/ts/tests/jaxws/se/api/javax_xml_ws
src/com/sun/ts/tests/internal/implementation/sjsas/saaj/com/sun/xml/messaging/saaj/api/javax_xml_soap
src/com/sun/ts/tests/jsp/api/javax_servlet
src/com/sun/ts/tests/saaj/api/javax_xml_soap
src/com/sun/ts/tests/servlet/pluggability/api/javax_servlet_http
src/com/sun/ts/tests/servlet/api/javax_servlet_http
src/com/sun/ts/tests/servlet/api/javax_servlet

The references of these directories need to be updated too.
The above list does not include pruned jaxr & jaxrpc.

**Comment by alwin-joseph** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/274 covers below 
 -src/com/sun/ts/tests/internal/implementation/sjsas/saaj/com/sun/xml/messaging/saaj/api/javax_xml_soap
 -src/com/sun/ts/tests/saaj/api/javax_xml_soap

Some of the *javax_servlet* replacing might covered in other changes. 
*javax_xml_ws* are pending, need to check if more javax file name changes.

**Comment by RohitKumarJain** [comment]
@alwin-joseph , would you like me to work on javax_xml_ws --> jakarta_xml_ws ? If it's not being taken care of by anyone?

**Comment by alwin-joseph** [comment]
> @alwin-joseph , would you like me to work on javax_xml_ws --> jakarta_xml_ws ? If it's not being taken care of by anyone?

Yea sure. Please check what are the pending javax_* filenames that can be changed to jakarta_* in the list.

**Comment by RohitKumarJain** [comment]
> > @alwin-joseph , would you like me to work on javax_xml_ws --> jakarta_xml_ws ? If it's not being taken care of by anyone?
> 
> Yea sure. Please check what are the pending javax_* filenames that can be changed to jakarta_* in the list.

Sure I'll check and update here while creating individual PRs for each change with respect to the above list.

**Comment by RohitKumarJain** [comment]
> > > @alwin-joseph , would you like me to work on javax_xml_ws --> jakarta_xml_ws ? If it's not being taken care of by anyone?
> > 
> > 
> > Yea sure. Please check what are the pending javax_* filenames that can be changed to jakarta_* in the list.
> 
> Sure I'll check and update here while creating individual PRs for each change with respect to the above list.




> > > @alwin-joseph , would you like me to work on javax_xml_ws --> jakarta_xml_ws ? If it's not being taken care of by anyone?
> > 
> > 
> > Yea sure. Please check what are the pending javax_* filenames that can be changed to jakarta_* in the list.
> 
> Sure I'll check and update here while creating individual PRs for each change with respect to the above list.

I have tried to compile below list based on the pending javax* to jakarta* files and references renaming of TCKs:
Completed:

javax_servlet to jakarta_servlet
javax_servlet_http to jakarta_servlet_http
javax_xml_soap to jakarta_xml_soap

Pending:

javax_xml_ws to jakarta _xml_ws
javax_xml_ws_handler to jakarta_xml_ws_handler
javax_xml_ws_handler_soap to jakarta_xml_ws_handler_soap
javax_xml_ws_http to jakarta_xml_ws_http
javax_xml_ws_soap to jakarta_xml_ws_soap
javax_xml_ws_wsaddressing to jakarta_xml_ws_wsaddressing

I’ll be taking care of pending javax* to jakarta* conversion and create PRs individually.

Please be noted in this conversion I am not taking care of pruned API's jaxr & jaxrpc.

**Comment by RohitKumarJain** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/278 covers below:

- jaxws/se/api/javax_xml_ws -----> jaxws/se/api/jakarta_xml_ws
- jaxws/api/javax_xml_ws      -----> jaxws/api/jakarta_xml_ws

**Comment by RohitKumarJain** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/280 covers below:

- jaxws/api/javax_xml_ws_handler -----> jaxws/api/jakarta_xml_ws_handler

**Comment by RohitKumarJain** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/281 cover below:

- javax_xml_ws_handler_soap -----> jakarta_xml_ws_handler_soap

**Comment by RohitKumarJain** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/282 covers below:

- javax_xml_ws_wsaddressing -----> jakarta_xml_ws_wsaddressing

**Comment by RohitKumarJain** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/283 cover below:

- javax_xml_ws_soap  -----> jakarta_xml_ws_soap

**Comment by RohitKumarJain** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/284 covers below:

- javax_xml_ws_http -----> jakarta_xml_ws_http

**Comment by RohitKumarJain** [comment]
Closing this as required work has been done and merged.

**Comment by RohitKumarJain** [comment]
Folder name and its reference (if applicable) change required in below locations from javax* to jakarta*:

1): src/com/sun/ts/tests/ejb30/lite/packaging/embed/provider/javax.ejb.spi.EJBContainerProvider
2): src/com/sun/ts/tests/jsf/spec/webapp/factoryfinder/META-INF/services/javax.faces.render.RenderKitFactory
3): src/web/jsf/api/javax_faces

**Comment by RohitKumarJain** [comment]
Covered below pending changes:

1): src/com/sun/ts/tests/ejb30/lite/packaging/embed/provider/javax.ejb.spi.EJBContainerProvider
2): src/com/sun/ts/tests/jsf/spec/webapp/factoryfinder/META-INF/services/javax.faces.render.RenderKitFactory
3): src/web/jsf/api/javax_faces

under https://github.com/eclipse-ee4j/jakartaee-tck/pull/298

**Comment by RohitKumarJain** [comment]
Closing this issue, as https://github.com/eclipse-ee4j/jakartaee-tck/pull/298 is merged and closed.
