### ISSUE TITLE
Some javax.persistence => jakarta.persistence changes are needed still

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#236]
Find and fix them

**Comment by RohitKumarJain** [comment]
To address this issue, I have raised a PR: https://github.com/eclipse-ee4j/jakartaee-tck/pull/249

**Comment by RohitKumarJain** [comment]
Closing this issue, as PR: https://github.com/eclipse-ee4j/jakartaee-tck/pull/249 has been merged and more pending action required.
