### ISSUE TITLE
Resolve errors in jakartaee-tck build

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#253]
The jakartaee-tck build needs to be fixed and the 12 sample tests need to pass.
This is run daily from the CI job to build jakartaee-tck 9 bundle : https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/ 

As more changes are made in the repo related to javax -> jakarta migration and removing pruned technologies, build will undergo further changes. This issue can track and report the build issues.

Below are the current compile errors in the platform TCK build.

1.  ant task do_java2wsdl_generate_server fails while using  wsgen
Stack trace:
    [wsgen] Exception in thread "main" java.lang.NoClassDefFoundError: jakarta/activation/DataSource
...
    [wsgen] Caused by: java.lang.ClassNotFoundException: jakarta.activation.DataSource
    [wsgen] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    [wsgen] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    [wsgen] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    [wsgen] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    [wsgen] 	... 35 more
[dosubdirs] The following error occurred while executing this line:
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/appclient/deploy/metadatacomplete/testapp/build.xml:71: The following error occurred while executing this line:
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/jaxws/common/xml/common.xml:1146: The following error occurred while executing this line:
[dosubdirs] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/jaxws/common/xml/common.xml:969: wsgen failed

Suggested temporary solution is to add the jakartaee-api.jar to the path of tools.jar in /install/jakartaee/bin/ts.jte . I also think this will be resolved once the glassfish with jakarta changes are available and used for building the TCK.

2. Issues similar to  below

-[ts.javac] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/ejb30/common/allowed/stateful/StatefulOperations.java:46: error: method does not override or implement a method from a supertype
 [ts.javac]   @Override
Can check once https://github.com/eclipse-ee4j/jakartaee-tck/issues/234 is resolved.

 -[ts.javac] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/securityapi/idstore/common/CustomHamForIDStore.java:35: error: CustomHamForIDStore is not abstract and does not override abstract method validateRequest(HttpServletRequest,HttpServletResponse,HttpMessageContext) in HttpAuthenticationMechanism
Due to refernce to javax.servlet.http.HttpServletRequest. Should be resolved by fixing https://github.com/eclipse-ee4j/jakartaee-tck/issues/223

-[ts.javac] /home/jenkins/agent/workspace/jakartaee-tck_master/src/com/sun/ts/tests/webservices/handlerEjb/HandlerLifecycle/ClientHandler.java:45:
error: incompatible types: javax.xml.soap.SOAPMessage cannot be converted to jakarta.xml.soap.SOAPMessage
This is due to the dependency of the test on javax.xml.rpc package. Should be fixed once https://github.com/eclipse-ee4j/jakartaee-tck/issues/210 is resolved.

**Comment by scottmarlow** [comment]
@alwin-joseph do you agree with [Bill's comment here](https://github.com/eclipse-ee4j/jakartaee-tck/issues/207#issuecomment-618078789) that we should download the SPEC API jars from Maven repo, instead of using the SPEC API jars contained in GlassFish?  

I updated the [top level tracker issue](https://github.com/eclipse-ee4j/jakartaee-tck/issues/207) and [issues/270](https://github.com/eclipse-ee4j/jakartaee-tck/issues/270), to reflect Bill Shannon's feedback.

**Comment by alwin-joseph** [comment]
> @alwin-joseph do you agree with [Bill's comment here](https://github.com/eclipse-ee4j/jakartaee-tck/issues/207#issuecomment-618078789) that we should download the SPEC API jars from Maven repo, instead of using the SPEC API jars contained in GlassFish?
> 
> I updated the [top level tracker issue](https://github.com/eclipse-ee4j/jakartaee-tck/issues/207) and [issues/270](https://github.com/eclipse-ee4j/jakartaee-tck/issues/270), to reflect Bill Shannon's feedback.

I think we should follow Bill's suggestion here to continue using the SPEC API jars from maven to get the TCK builds passing although I believe the latest glassfish jars will be same as getting from maven. We need the jars only for compiling the code during the TCK build. 
For building jaxws sources I see that wsgen tool require the api-jar in tools.jar path(in ts.jte)

**Comment by scottmarlow** [comment]
I'm not sure if https://ci.eclipse.org/jakartaee-tck/job/build-glassfish/ will build but the same maven command line worked locally for me, so it should.  

It basically clones https://github.com/eclipse-ee4j/glassfish.git and does "mvn -Pstaging install -DskipTests=true".

If that works, perhaps we should update it to run daily (and change the name to reflect that its daily/nightly, whatever).

**Comment by scottmarlow** [comment]
@alwin-joseph can you use help from others with this issue?  If yes, we should mention that on the TCK mailing list.  I'll mention this issue as well on the TCK status update I'm sending now to the TCK mailing list.

**Comment by scottmarlow** [comment]
> @scottmarlow
> It seems the change on file src/com/sun/ts/tests/ejb30/common/allowed/Operations.java in d604236#diff-264e5a615267e0bae53017cb95c50932 to remove the runMessageContext caused this. Considering that this method is removed due to deprecated jaxrpc, I think the solution is to remove the "runMessageContext" method from src/com/sun/ts/tests/ejb30/common/allowed/stateful/StatefulOperations.java which does not have any implementation.

Thanks, I'll make this change.

> I think we should follow Bill's suggestion here to continue using the SPEC API jars from maven to get the TCK builds passing although I believe the latest glassfish jars will be same as getting from maven. We need the jars only for compiling the code during the TCK build.
> For building jaxws sources I see that wsgen tool require the api-jar in tools.jar path(in ts.jte)
> 
On this, I wonder if it would be easier to first focus on using the latest glassfish jars (from either our build or glassfish project nightly build when available).

**Comment by alwin-joseph** [comment]
> > I think we should follow Bill's suggestion here to continue using the SPEC API jars from maven to get the TCK builds passing although I believe the latest glassfish jars will be same as getting from maven. We need the jars only for compiling the code during the TCK build.
> > For building jaxws sources I see that wsgen tool require the api-jar in tools.jar path(in ts.jte)
> 
> On this, I wonder if it would be easier to first focus on using the latest glassfish jars (from either our build or glassfish project nightly build when available).

I will try to use the glassfish bundle with the latest jars for the build and check if the wsgen issue get resolved by this. Otherwise the api jar we use is sufficient to get the build passing. 

As of now, we would need below issues to be fixed for resolving the compilation errors in the platform TCK build : 
https://github.com/eclipse-ee4j/jakartaee-tck/issues/210 
https://github.com/eclipse-ee4j/jakartaee-tck/issues/285 

To start running the tests we would need the glassfish bundle with jakarta jars. I hear that the glassfish bundle generated now fails to start. So will not try to get the sample tests passing now although some of the tests may run without starting glassfish.

**Comment by alwin-joseph** [comment]
> > On this, I wonder if it would be easier to first focus on using the latest glassfish jars (from either our build or glassfish project nightly build when available).
> 
> I will try to use the glassfish bundle with the latest jars for the build and check if the wsgen issue get resolved by this. Otherwise the api jar we use is sufficient to get the build passing.

PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/290 for this. The wsgen issues are resolved. I had to update the tools.jar in ts.jte to have webservices-tools.jar & webservices-api.jar in glassfish6. The tools.jar was initially set in install/jakartaee/bin/ts.jte  as "${jdk.home}/lib/tools.jar"  which has old apis in jdk8. So I think we need to use gf bundle and not jakartaee-api jar for building.

**Comment by scottmarlow** [comment]
@alwin-joseph should this issue also track updating build_standalone-tcks.sh also?

**Comment by alwin-joseph** [comment]
> @alwin-joseph should this issue also track updating build_standalone-tcks.sh also?

I think we can track the standalone tck build in a separate issue : https://github.com/eclipse-ee4j/jakartaee-tck/issues/293

**Comment by alwin-joseph** [comment]
I see that the wsgen failures have reappeared in https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/647/ ( https://github.com/eclipse-ee4j/jakartaee-tck/commit/366be6783ae90c3a486e29c2ba0997d9ee970126 )

There were no wsgen failures in https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/637/ (https://github.com/eclipse-ee4j/jakartaee-tck/commit/11e933e2af2f7147481d259c6e69f25bae5b4e49 )

Checking if the PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/289 caused any issues or the glassfish bundle used in these jobs. 

Also I can see the wsgen failures are not present in my local testing.

**Comment by alwin-joseph** [comment]
> I see that the wsgen failures have reappeared in https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/647/ ( [366be67](https://github.com/eclipse-ee4j/jakartaee-tck/commit/366be6783ae90c3a486e29c2ba0997d9ee970126) )
> 
> There were no wsgen failures in https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/637/ ([11e933e](https://github.com/eclipse-ee4j/jakartaee-tck/commit/11e933e2af2f7147481d259c6e69f25bae5b4e49) )
> 
> Checking if the PR #289 caused any issues or the glassfish bundle used in these jobs.
> 
> Also I can see the wsgen failures are not present in my local testing.

The current wsgen failures are due to the updated glassfish bundle with new metro jar (jaxb-osgi.jar)

from the logs : 
    [wsgen] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/nav/Navigator
    [wsgen] 	at com.sun.tools.javac.main.Main.compile(Main.java:553)
    [wsgen] 	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    [wsgen] 	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    [wsgen] 	at com.sun.tools.ws.wscompile.WsgenTool.buildModel(WsgenTool.java:167)
    [wsgen] 	at com.sun.tools.ws.wscompile.WsgenTool.run(WsgenTool.java:98)
    [wsgen] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    [wsgen] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    [wsgen] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    [wsgen] 	at java.lang.reflect.Method.invoke(Method.java:498)
    [wsgen] 	at com.sun.tools.ws.Invoker.invoke(Invoker.java:123)
    [wsgen] 	at com.sun.tools.ws.WsGen.main(WsGen.java:26)
    [wsgen] Caused by: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/nav/Navigator
    [wsgen] 	at com.sun.tools.ws.processor.modeler.annotation.WebServiceAp.process(WebServiceAp.java:140)
    [wsgen] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
    [wsgen] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
    [wsgen] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
    [wsgen] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
    [wsgen] 	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
    [wsgen] 	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    [wsgen] 	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
    [wsgen] 	at com.sun.tools.javac.main.Main.compile(Main.java:523)
    [wsgen] 	... 10 more
    [wsgen] Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.nav.Navigator
    [wsgen] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
    [wsgen] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    [wsgen] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
    [wsgen] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    [wsgen] 	... 19 more

The class com.sun.xml.bind.v2.model.nav.Navigator seems to be renamed in the current glassfish/modules/jaxb-osgi.jar.

**Comment by alwin-joseph** [comment]
> > I see that the wsgen failures have reappeared in https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/647/ ( [366be67](https://github.com/eclipse-ee4j/jakartaee-tck/commit/366be6783ae90c3a486e29c2ba0997d9ee970126) )
> > There were no wsgen failures in https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/637/ ([11e933e](https://github.com/eclipse-ee4j/jakartaee-tck/commit/11e933e2af2f7147481d259c6e69f25bae5b4e49) )
> > Checking if the PR #289 caused any issues or the glassfish bundle used in these jobs.
> > Also I can see the wsgen failures are not present in my local testing.
> 
> The current wsgen failures are due to the updated glassfish bundle with new metro jar (jaxb-osgi.jar)
> 
> from the logs :
> [wsgen] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/nav/Navigator
> [wsgen] at com.sun.tools.javac.main.Main.compile(Main.java:553)
> [wsgen] at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
> [wsgen] at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
> [wsgen] at com.sun.tools.ws.wscompile.WsgenTool.buildModel(WsgenTool.java:167)
> [wsgen] at com.sun.tools.ws.wscompile.WsgenTool.run(WsgenTool.java:98)
> [wsgen] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [wsgen] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [wsgen] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [wsgen] at java.lang.reflect.Method.invoke(Method.java:498)
> [wsgen] at com.sun.tools.ws.Invoker.invoke(Invoker.java:123)
> [wsgen] at com.sun.tools.ws.WsGen.main(WsGen.java:26)
> [wsgen] Caused by: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/nav/Navigator
> [wsgen] at com.sun.tools.ws.processor.modeler.annotation.WebServiceAp.process(WebServiceAp.java:140)
> [wsgen] at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
> [wsgen] at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
> [wsgen] at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
> [wsgen] at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
> [wsgen] at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
> [wsgen] at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
> [wsgen] at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
> [wsgen] at com.sun.tools.javac.main.Main.compile(Main.java:523)
> [wsgen] ... 10 more
> [wsgen] Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.nav.Navigator
> [wsgen] at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> [wsgen] at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> [wsgen] at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> [wsgen] at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> [wsgen] ... 19 more
> 
> The class com.sun.xml.bind.v2.model.nav.Navigator seems to be renamed in the current glassfish/modules/jaxb-osgi.jar.

This issue seem to be fixed in the latest build job https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/186/console as the new glassfish bundle was used.

**Comment by alwin-joseph** [comment]
Current pending build issues : all related to pruned technologies.
Dirs:
src/com/sun/ts/tests/j2eetools
src/com/sun/ts/tests/ejb/ee/webservices/allowedmethodstest
src/com/sun/ts/tests/jaxr
src/com/sun/ts/tests/jaxrpc
src/com/sun/ts/tests/webservices

**Comment by scottmarlow** [comment]
I believe that this issue is resolved now since pruning is complete.  Please reopen if there are more build errors to be solved.
