### ISSUE TITLE
[releng] Cleanup https://ci.eclipse.org/jakartaee-tck/

### ISSUE THREAD

**Issue by mbarbero** [eclipse-ee4j/jakartaee-tck#259]
Hi,

Eclipse Foundation releng team here. We've noticed that your instance is using more than 500GB of disk space just for build history (logs+artifacts). See below the list of the 10 biggest jobs. Could you please run through them and clean up their build history (to keep less items)? Could you also please go through your other jobs and ensure that they are configured with a build discarder? We will eventually create a default one with reasonable defaults, but in the meantime, it would be great if you could define some by yourself.

Thanks.

12G	jakartaeetck-nightly-run-800
13G	standalonetck-nightly-build-run-master
19G	standalonetck-nightly-build-run-web-800
23G	jakartaeetck-certification
24G	jakartaeetck-nightly-run-master
25G	eftl-jakartaeetck-certification
50G	standalonetck-nightly-build-run-800
66G	jakartaeetck-nightly-build-800
189G	jakartaee-tck

**Comment by alwin-joseph** [comment]
1. Configured below active jobs to delete the tck bundles from their workspace after other actions
standalonetck-nightly-build-run-master
jakartaeetck-nightly-run-master
jakartaeetck-nightly-build-master

2. Manually deleted old build jobs from.
standalonetck-nightly-build-run-800
jakartaeetck-nightly-build-800
standalonetck-nightly-build-run-web-800
jakartaeetck-nightly-run-800

3. jakartaee-tck is configured with build discarder of 30 days. Will reduce both to 15.
buildDiscarder(logRotator(numToKeepStr: '30', artifactDaysToKeepStr: '30'))

**Comment by mbarbero** [comment]
Thanks indeed. JENKINS_HOME is down to 227G. Here are the 5 largest jobs:

28M	glassfish-docs-publish
30M	glassfish_build-and-publish-to-eclipse-download
37M	hk2
3.4G	jakartaee-tck
223G	glassfish_build-and-test-using-jenkinsfile

**Comment by mbarbero** [comment]
(whoops, ran the stats on glassfish instead of jarkartaee-tck, will come back soon with new stats)

**Comment by mbarbero** [comment]
Jenkins home is down to 408G. Here are the 10 largest jobs:

7.3G	eftl-standalonetck-build-run-800
8.6G	eftl-jakartaeetck-certification-web
8.7G	jakartaeetck-nightly-run-master
9.2G	jakartaeetck-nightly-run-web-800
9.3G	jakartaee-tck-alwin
12G	jakartaeetck-nightly-run-800
14G	jakartaeetck-certification
25G	eftl-jakartaeetck-certification
40G	jakartaee-tck-grao
212G	jakartaee-tck

It seems that jakartaee-tck is not yet down to 15. It should save ~100 more GB making the instance down to 300GB. This is a great start. Let me know once the change on jakartaee-tck is live, and I will run the stats again.

**Comment by alwin-joseph** [comment]
> Jenkins home is down to 408G. Here are the 10 largest jobs:
> 
> 7.3G eftl-standalonetck-build-run-800
> 8.6G eftl-jakartaeetck-certification-web
> 8.7G jakartaeetck-nightly-run-master
> 9.2G jakartaeetck-nightly-run-web-800
> 9.3G jakartaee-tck-alwin
> 12G jakartaeetck-nightly-run-800
> 14G jakartaeetck-certification
> 25G eftl-jakartaeetck-certification
> 40G jakartaee-tck-grao
> 212G jakartaee-tck
> 
> It seems that jakartaee-tck is not yet down to 15. It should save ~100 more GB making the instance down to 300GB. This is a great start. Let me know once the change on jakartaee-tck is live, and I will run the stats again.

Done with the change on jakartaee-tck. Also removed more job runs that were not required.
Will continue to do further cleanup.

**Comment by mbarbero** [comment]
Gain on jakartaee-tck is not as large as I was expecting. It's now 195G. Total usage is down to 324G though

Top 10 now:

5.6G	jakartaeetck-nightly-build-master
5.7G	jakartaeetck-nightly-run-800
6.4G	eftl-jakartaeetck-run-800
6.9G	jakartaeetck-nightly-run-master
7.3G	eftl-jakartaeetck-build-800
7.3G	eftl-standalonetck-build-run-800
8.6G	eftl-jakartaeetck-certification-web
12G	jakartaeetck-certification
22G	eftl-jakartaeetck-certification
195G	jakartaee-tck

Thanks for your efforts, it's well appreciated.

**Comment by scottmarlow** [comment]
Just deleted some more job results, so we could be lower now.  Please reopen if we need to reduce disk space further.
