### ISSUE TITLE
WebSocket TCK excessively slow and some tests unstable

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-tck#260]
Running the standalone WebSocket test suite a significant number of tests take 10s of seconds when, given the actions of the test, they would be expected to take a second or two.

Reviewing the code identified a number of tests that were using a `CountDownLatch` incorrectly to wait for messages to arrive. The calls to `await() ` were timing out rather than the latch being released. The time waiting for the timeout was causing the delay to the tests.

I have a fix and will submit a PR shortly.

Fixing the use of `CountDownLatch` also resolved a long standing issue with a couple of timeout tests where the results were not stable.

**Comment by scottmarlow** [comment]
+100 for this issue, will be nice to have a faster standalone WebSocket test run!  Thanks @markt-asf in advance for the correction!

**Comment by markt-asf** [comment]
See PR #261

**Comment by markt-asf** [comment]
PR applied. This issue has been fixed.
