### ISSUE TITLE
Exclude 2 WebSocket tests

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-tck#262]
There is an [open bug against WebSocket](https://github.com/eclipse-ee4j/websocket-api/issues/228) that can't be fixed until Jakarta EE 10. The short version is that the return value for `Session.getRequestURI()` is not clearly defined in the specification. The TCK currently tests for a return value that is inconsistent with the consensus view of the correct return value. Therefore, the two tests that check this value need to be excluded until the specification is clarified and the TCK updated.

I'll provide a PR shortly.

**Comment by scottmarlow** [comment]
Ah, interesting, is this targeted for Jakarta EE 9?

**Comment by markt-asf** [comment]
Yes, we would like to get this test excluded in Jakarta EE 9. That will allow implementations to provide (or continue to provide in a number of cases) a "correct" / "better" return value and still pass the TCK. We don't want to change the test because that would create backwards compatibility issues for the implementations that currently pass the TCK.
