### ISSUE TITLE
Update scripts to copy final Jakarta EE 9 spec api jars from GlassFish

### ISSUE THREAD

**Issue by cesarhernandezgt** [eclipse-ee4j/jakartaee-tck#270]

**Comment by scottmarlow** [comment]
Updated description here and in top level tracker, to instead use final released SPEC API jars.

**Comment by scottmarlow** [comment]
Note that we are moving away from having a Jakarta EE reference implementation and will instead have one or more compatible implementations, so we definitely need to stop copying SPEC API artifacts (into the Jakarta EE Platform TCK) from the GlassFish server that we test with.

**Comment by scottmarlow** [comment]
We have been copying the Jakarta EE 9 SPEC API jar files from the GlassFish version that we are building the TCK from which I think will address this issue.
