### ISSUE TITLE
Can't run Batch signature tests

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/jakartaee-tck#275]
I would like to understand this area better since Batch has its own standalone TCK that I'd also like to produce the signature tests for, in addition to helping, if possible, with the platform TCK.

I thought a simple first step would be to just try running the Java 11 Batch sig tests against the platform milestone API JAR and eventually the batch CI... however I was unable to get this to work.
I'm not clear how to run the tests.

If I take the  **jakarta.batch.sig_1.0_se11** committed to the repo now and run (Java 11):

```bash
REPO_ROOT= # .. git clone here
cd $REPO_ROOT
java -jar $REPO_ROOT/lib/sigtest.jar   SignatureTest -static -package jakarta.batch -filename   src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.batch.sig_1.0_se11   -classpath  jakarta.jakartaee-api-9.0.0-RC1.jar
```

it fails with 39 errors.  This gives me a clue that it's pretty clear that the problem is that the java.lang.* classes are not on the classpath.  I say that because it's the Exception classes and the abstract classes (extending java.lang.Object) which result in failure.     

OK, so I look at these instructions:
https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Signature-Tests-in-JakartaEE-TCK-for-JDK11

and it suggests I should be using `jimage` to extract the modules, such as `java.base`, which should be on my classpath.

However, I've tried a bunch of variants of classpaths and have tried Open JDK and Oracle JDK, but can not build a classpath and get it to work.   Everything I try results in this unhelpful error message:

`STATUS:Error.Class path not specified or incorrect in the static mode.`

with no clue what the problem is or the next step.

True, there a couple READMEs to look at but also warnings with issues like: https://github.com/eclipse-ee4j/jakartaee-tck/issues/181  saying these may be outdated.

Appreciate any advice on the next step.  Thanks,

**Comment by markt-asf** [comment]
When running the standalone EL and WebSocket tests I used soemthing like this:
```
# Java 8 & 11
sigTestClasspath=${java.home}/lib/modules${pathsep}${java.home}/lib/rt.jar${pathsep}${websocket.classes}${pathsep}${websocket.api}
```

In short, I added `${java.home}/lib/modules${pathsep}` to the start of `sigTestClasspath`. This then works with both Java 8 and Java 11.

Looking at your call above I think you need to make a similar adjustment to the class path you use.

**Comment by scottkurz** [comment]
I figured it out.. It wasn't the path to the modules that was the issue, it was the relative path to the API jar that I messed up !  

I was using "api.jar"  but it needed to be "./api.jar". (Or I could have used an absolute pathname).  Maybe classic mistake but haven't built a classpath in awhile.

So what worked (for Open JDK) was:

## JDK 11 
```bash

JDK11_CLASSES=   # Extract here using `jimage extract $JAVA_HOME/lib/modules`
REPO_ROOT=   # .. git clone here
cd $REPO_ROOT

java -jar $REPO_ROOT/lib/sigtest.jar   SignatureTest -static -package jakarta.batch -filename   src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.batch.sig_1.0_se11   -classpath  ./jakarta.jakartaee-api-9.0.0-RC1.jar:/$JDK11_CLASSES/java.base/
```

## JDK 8
```bash

JDK11_CLASSES=   # Extract here using `jimage extract $JAVA_HOME/lib/modules`
REPO_ROOT=   # .. git clone here
cd $REPO_ROOT

java -jar $REPO_ROOT/lib/sigtest.jar   SignatureTest -static -package jakarta.batch -filename   src/com/sun/ts/tests/signaturetest/signature-repository/jakarta.batch.sig_1.0_se8   -classpath  ./jakarta.jakartaee-api-9.0.0-RC1.jar:$JAVA_HOME/jre/lib/rt.jar
```

@markt-asf appreciate your suggestion.

**Comment by alwin-joseph** [comment]
Hi @scottkurz : Ideally Mark's suggestion should work. If it doesn't can you try to extract the jdk11 modules as below and use that in the classpath for jdk11.
-jimage extract --dir ${java.home}/extract/classes ${java.home}/lib/modules
-Use ${java.home}/extract/classes in the classpath to run the test.

On another note, the current sig file  jakarta.batch.sig_1.0_se11 would need some correction as it also contains other jakarta api method references. It was generated using the [wiki](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Signature-Tests-in-JakartaEE-TCK-for-JDK11)  but this might need a change where we are using the entire jakartaee-api jar in the sigtestclasspath. It was suggested that we need to use only the batch jar and the dependent jars(jakarta.inject-api jar) for generating the sig file for jbatch. 
I am working on updating this sig file and others. Meanwhile you could try the above for jbatch.

**Comment by alwin-joseph** [comment]
> Hi @scottkurz : Ideally Mark's suggestion should work. If it doesn't can you try to extract the jdk11 modules as below and use that in the classpath for jdk11.
> -jimage extract --dir ${java.home}/extract/classes ${java.home}/lib/modules
> -Use ${java.home}/extract/classes in the classpath to run the test.
> 
> On another note, the current sig file jakarta.batch.sig_1.0_se11 would need some correction as it also contains other jakarta api method references. It was generated using the [wiki](https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Signature-Tests-in-JakartaEE-TCK-for-JDK11) but this might need a change where we are using the entire jakartaee-api jar in the sigtestclasspath. It was suggested that we need to use only the batch jar and the dependent jars(jakarta.inject-api jar) for generating the sig file for jbatch.
> I am working on updating this sig file and others. Meanwhile you could try the above for jbatch.

I see that you were able to run the test. Please ignore my comments on running the test.

**Comment by scottkurz** [comment]
> On another note, the current sig file jakarta.batch.sig_1.0_se11 would need some correction as it also contains other jakarta api method references. It

Thx @alwin-joseph for the suggestion.  I will take a look at the above next change I get.

(BTW, I would open a bug/issue on the sigtest repo but I don't have an OpenJDK id registered so didn't bother.   It'd be nice, if it's going to complain about an invalid classpath entry, if it would say which one is invalid.   Just thinking out loud here.)
