### ISSUE TITLE
Remaining javax.xml.ws -> jakarta.xml.ws and javax_xml_ws -> jakarta_xml_ws changes

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#285]
Looks like the javax.xml.ws -> jakarta.xml.ws changes are pending for sources outside the jaxws TCK folder.

**Comment by RohitKumarJain** [comment]
This has been addressed in https://github.com/eclipse-ee4j/jakartaee-tck/pull/289

Thanks

**Comment by scottmarlow** [comment]
@alwin-joseph @RohitKumarJain 

Repeating here what I commented on the PR:

> I get a little confused sometimes on which javax.* class shouldn't be transformed, as some classes are in the Java SE 8 but also in Jakarta EE 9.
> 
> To check javax.xml.ws, I looked in my local JDK 1.8, in the src.zip, I see javax/xml/ws classes, meaning that they are part of Java SE 8.
> 
> In my local copy of https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-api/9.0.0-RC1/jakarta.jakartaee-api-9.0.0-RC1.jar, I only see jakarta/xml/soap classes but no jakarta/xml/ws.  :(
> 

So I think the javax.xml.ws references should be okay, make sense?

**Comment by alwin-joseph** [comment]
> @alwin-joseph @RohitKumarJain
> 
> Repeating here what I commented on the PR:
> 
> > I get a little confused sometimes on which javax.* class shouldn't be transformed, as some classes are in the Java SE 8 but also in Jakarta EE 9.
> > To check javax.xml.ws, I looked in my local JDK 1.8, in the src.zip, I see javax/xml/ws classes, meaning that they are part of Java SE 8.
> > In my local copy of https://repo1.maven.org/maven2/jakarta/platform/jakarta.jakartaee-api/9.0.0-RC1/jakarta.jakartaee-api-9.0.0-RC1.jar, I only see jakarta/xml/soap classes but no jakarta/xml/ws.  :(
> 
> So I think the javax.xml.ws references should be okay, make sense?

Oh sorry, this is my mistake. I did not verify this. @RohitKumarJain Apologies that I created this issue.

**Comment by alwin-joseph** [comment]
I found in the PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/224 that javax.xml.ws was replaced with jakarta.xml.ws  within the jaxws sources. cc @Tomas-Kraus 
The  https://repo1.maven.org/maven2/jakarta/xml/ws/jakarta.xml.ws-api/3.0.0-RC1/jakarta.xml.ws-api-3.0.0-RC1.jar was downloaded to fix the jaxws & platform tck build too. Shouldn't we be doing the same for other occurrences too.

**Comment by scottmarlow** [comment]
Good find @alwin-joseph, so it sounds like we do need the update.

In a local glassfish6 build I also see the jakarta.xml.ws classes in glassfish/modules/webservices-api-osgi.jar.

**Comment by RohitKumarJain** [comment]
Closing this issue, as https://github.com/eclipse-ee4j/jakartaee-tck/pull/289 is merged and closed.
