### ISSUE TITLE
Successfully build standalone TCKs that are generated from this repo

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#293]
The standalone TCKs that are build from jakartaee-tck repo needs This is built and run from the CI job  : https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/. The TCKs of pruned techs will not be generated.

1. The script docker/build_standalone-tcks.sh is used to build all those TCKs.  Currently there are compilation issues for several TCKs. Will update the issues and track them here. 
2. The TCKs generated will be copied to the directory https://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/. Need to also cleanup this directory by removing obsolete bundles.
2. Once the build is successful the standalone TCK test runs should also pass.

**Comment by alwin-joseph** [comment]
Created https://github.com/eclipse-ee4j/jakartaee-tck/pull/297 to fix most of the standalone TCK builds. 

Pending tasks : 

1.  jaspic tck fails to build due to due to wsgen failure
jaspic standalone TCK build failure logs :  
    [wsgen] Exception in thread "main" java.lang.RuntimeException: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/nav/Navigator
    [wsgen] Caused by: java.lang.NoClassDefFoundError: com/sun/xml/bind/v2/model/nav/Navigator
    [wsgen] Caused by: java.lang.ClassNotFoundException: com.sun.xml.bind.v2.model.nav.Navigator
[dosubdirs] The following error occurred while executing this line:
[dosubdirs] /home/jenkins/agent/workspace/aee-tck-alwin_standalonetckbuild/src/com/sun/ts/tests/jaspic/spi/authstatus/authexception/build.xml:46: The following error occurred while executing this line:
[dosubdirs] /home/jenkins/agent/workspace/aee-tck-alwin_standalonetckbuild/src/com/sun/ts/tests/jaxws/common/xml/common.xml:1146: The following error occurred while executing this line:
[dosubdirs] /home/jenkins/agent/workspace/aee-tck-alwin_standalonetckbuild/src/com/sun/ts/tests/jaxws/common/xml/common.xml:969: wsgen failed

I think this can be fixed by adding the correct jaxb jars in tools.jar in install/jaspic/bin/ts.jte

2. javax.enterprise.deploy-api-1.7.jar & deployment-client-5.1.0-RC2.jar jars are temporarily downloaded to resolve errors where javax.enterprise packages are used. This will be removed after https://github.com/eclipse-ee4j/jakartaee-tck/issues/211 is resolved.

**Comment by scottmarlow** [comment]
[jakartaee-tck-dev/msg00570.html](https://www.eclipse.org/lists/jakartaee-tck-dev/msg00570.html) mentions the reason why our freestyle [standalonetck-nightly-build-run-master](https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master) job is running out of memory.  Eclipse CI defaults to small JNLP memory size as they don't know how big to make it (a small JNLP size may work for some jobs but not all).  

To address this, we need to create a pipeline job for building the standalone TCKs, that specifies larger JNLP memory settings similar to [Jenkinsfile#L130](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/Jenkinsfile#L130).

**Comment by alwin-joseph** [comment]
Current status : 

All the standalone TCKs are built without errors. The failures in the latest job run https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/52/junit-reports-with-handlebars/testSuitesOverview.html should be fixed.

**Comment by scottmarlow** [comment]
@alwin-joseph do you recall if the messages about the following being [unresolved](https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master), indicates a real problem?

    Unresolved
    jakartaee-tck/master

    Unresolved
    debugging-support-for-other-languages-tck/master

    Unresolved
    cditck-porting/master

    Unresolved
    ditck-porting/master

    Unresolved
    bvtck-porting/master

**Comment by alwin-joseph** [comment]
> @alwin-joseph do you recall if the messages about the following being [unresolved](https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master), indicates a real problem?
> 
> ```
> Unresolved
> jakartaee-tck/master
> 
> Unresolved
> debugging-support-for-other-languages-tck/master
> 
> Unresolved
> cditck-porting/master
> 
> Unresolved
> ditck-porting/master
> 
> Unresolved
> bvtck-porting/master
> ```

Scott - i dont suppose this _unresolved_ is a problem for us. The subprojects are running as expected.

**Comment by alwin-joseph** [comment]
Based on the latest job run for standalone TCK build and run: https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/54/  around 400 failures in all of these need to be looked up
Below are the failure count  for those : 

1. jaxws (xml-ws-tck) : 1 signature test failure/1703 (Alwin)
2. websocket - 3/732 - 1 sig test failure(Alwin) + 2
3. jta (transactions) - 2/72 failures - 2 sig tests failing(Alwin)
connectors - 138/139  issue : Deployment Failed:  whitebox-mdcomplete.rar 
 saaj(soap) - 8/450 failures 
 servlet  - 4/1691 failures
 security - 83/85 failures
 jax-rs (restful-ws-tck) - 59/2664 failures
 jsf(faces-tck) - 16/5525 failures
 jacc(authorization-tck)  - 10/34 failures Deployment Failed: jacc_ejb_mr_ejblitesecuredjsp_vehicle_web.war
 jaspic(authentication-tck) - 107/107 failures

**Comment by alwin-joseph** [comment]
Closing this issue as the standalone TCK builds are successfully completed. Can create separate issues to track the test failures in each TCKs.
