### ISSUE TITLE
Update lib/*jars in the repo

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#296]
JAXB jars in jakartaee-tck repo : 

There are 4 jaxb jars - jaxb-api.jar, jaxb-core.jar, jaxb-impl.jar & jaxb-xjc.jar committed to the jakartaee-tck repo at https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/lib . From what I understand the latest replacement of these 4 jars with jakarta changes are at [1] , [2], [3] & [4]. They are all present in https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-ri/3.0.0-M3/jaxb-ri-3.0.0-M3.zip.

[1] https://repo1.maven.org/maven2/jakarta/xml/bind/jakarta.xml.bind-api/3.0.0-RC3/jakarta.xml.bind-api-3.0.0-RC3.jar
[2] https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-core/3.0.0-M3/jaxb-core-3.0.0-M3.jar
[3] https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/3.0.0-M3/jaxb-impl-3.0.0-M3.jar
[4] https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-xjc/3.0.0-M3/jaxb-xjc-3.0.0-M3.jar

We need to check how to replace the old jars (jaxb-api.jar, jaxb-core.jar, jaxb-impl.jar & jaxb-xjc.jar) in this repo with the latest from the above. I saw there are differences in the classes for new jars with the old ones in the class/folder names. 
We could also think about downloading the latest jars in the runtime. 

Other jars : Need to check if any of them can be updated with the jakarta version.

**Comment by scottmarlow** [comment]
So, one question is whether the jars were produced by Eclipse Jakarta projects, I think that they were and have been approved for release (before being pushed to the Maven repo), as per project release plan links which I checked for these jars and you probably did as well.

Imo, we could replace the current ones in lib (e.g. use the current names) with the [1][2][3][4] jars as they do appear to be the latest releases.  And ensure that we have an open issue for replacing them again with the final jars when available.

**Comment by alwin-joseph** [comment]
Fixed by https://github.com/eclipse-ee4j/jakartaee-tck/pull/299 .

 -DenableExternalEntityProcessing=true was added to ANT_OPTS to fix below parse issues with the latest xjc jar.
[xjc] Compiling file:/scratch/alwjosep/jakarta9/jakartaee-tck/lib/dtds/sun-application_6_0-0.dtd
   [xjc] [ERROR] External parsing is disabled. Cannot parse URI: file:/scratch/alwjosep/jakarta9/jakartaee-tck/lib/dtds/sun-application_6_0-0.dtd
   [xjc] unknown location
   [xjc] 
   [xjc] failure in the XJC task. Use the Ant -verbose switch for more details
