### ISSUE TITLE
EDP violation: Sign-Off missing for initial commit

### ISSUE THREAD

**Issue by mkarg** [eclipse-ee4j/jakartaee-tck#3]
According to the EDP all commits MUST contain a Sign-Off.

**Comment by mkarg** [comment]
@waynebeaton Exception by EMO?

**Comment by waynebeaton** [comment]
Thanks for checking

According to the handbook,

> Commits that are provided by **non-committers** must have a Signed-off-by field in the footer indicating that the author is aware of the terms by which the contribution has been provided to the project. The **non-committer** must additionally have an Eclipse Foundation Account and must have a signed Eclipse Contributor Agreement (ECA) on file.

The author/committer of the initial contribution commit is a committer on the project. No Signed-Off-By is required.

Splitting hairs: The Signed-off-by requirement is not baked into the EDP. It's more of an implementation detail driven by the Eclipse IP Policy. The fundamental requirement is that we have confidence that a (non-committer) contributor understands and consents to the terms defined in the [ECA and DCO](https://www.eclipse.org/legal/ECA.php).

For completeness, as a committer this contribution is covered by their committer agreement.

**Comment by mkarg** [comment]
Thanks for the detailed explanation! I assume a lot of us misinterpreted this, because most of us sign *our own* commits all of the time. So we can stop that now. Great! :-)
