### ISSUE TITLE
Convert batch (jbatch) TCK test job XMLs from JCP -> Jakarta targetNamespace

### ISSUE THREAD

**Issue by scottkurz** [eclipse-ee4j/jakartaee-tck#320]
Continuing #162 , we still need to update 

`xmlns="http://xmlns.jcp.org/xml/ns/javaee"`
  => 
`xmlns="https://jakarta.ee/xml/ns/jakartaee"`

for the batch job XMLs, e.g.
 **src/com/ibm/jbatch/tck/testJobXml/META-INF/batch-jobs/testMetricCount.xml**

**Comment by scottmarlow** [comment]
Thanks @scottkurz for noticing the remaining references!  For the Platform TCK batch tests, will you create a pull request to address those?  I added a list of the batch test files that contain ```http://xmlns.jcp.org/xml/ns/javaee``` to [jakartaee-tck/issues/266](https://github.com/eclipse-ee4j/jakartaee-tck/issues/266#issuecomment-644335205)

**Comment by scottkurz** [comment]
Thanks @scottmarlow .. Fixed batch in https://github.com/eclipse-ee4j/jakartaee-tck/pull/337
