### ISSUE TITLE
Platform TCK milestone release 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#328]
Steps that can be followed (Edited): 

1. Create new directory to have the bundles for jakartaee9
http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/
http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/

2. Run the https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/ to build the platform TCK from master (at http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/jakartaeetck-9.0.0.zip) and run sample tests.

3. Run the https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/ job to verify http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/jakartaeetck-9.0.0.zip.
Will also try to use the https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/ job to verify this bundle to selectively run suites.

4. Copy the http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/jakartaeetck-9.0.0.zip to http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/jakartaeetck-9.0.0-M1.zip

The new platform tck bundle should be jakartaeetck-9.0.0-M1.zip and will be available as http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/jakartaeetck-9.0.0-M1.zip

Open to suggestions.

**Comment by scottmarlow** [comment]
@kwsutter do we need to release a Milestone 1 Platform TCK?

**Comment by kwsutter** [comment]
I think it would be consistent to have a Milestone artifact for the Platform TCK.  We will then corresponding artifacts for the Specs, APIs, TCKs, and CIs. Thanks!

BTW, the name of the Milestone should be 9.0.0-M1 (not MS1).  We decided on the use of the -B, -M, and -RC suffixes at a recent Platform call.  And, they are documented in this wiki:
https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules (under section "Version numbers for non-final specifications")

**Comment by alwin-joseph** [comment]
Thanks Kevin. I will work to release a Milestone 1 Platform TCK bundle with the open pending issues.  We can have the **9.0.0-M1** bundle by later this week as per the steps. 

@scottmarlow @gurunrao Can you please review and provide your comments.  This will cover only the platform TCK, not sure if we need to extend this to standalone TCKs too.

**Comment by scottmarlow** [comment]
@alwin-joseph I think it makes sense.  I assume it will only take a few days (mostly just building + running the Platform TCK with a hack to create the new folder + copy to it), do you agree?

The longer path would be to move all of our jobs that build things for master branch, to target http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly but that sounds more like a 3-5 day task.  We could do that, but that might even take longer to do.

**Comment by alwin-joseph** [comment]
> @alwin-joseph I think it makes sense. I assume it will only take a few days (mostly just building + running the Platform TCK with a hack to create the new folder + copy to it), do you agree?
> 
Yes Scott. 
> The longer path would be to move all of our jobs that build things for master branch, to target http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly but that sounds more like a 3-5 day task. We could do that, but that might even take longer to do.

Yes, We can move the https://download.eclipse.org/ee4j/jakartaee-tck/master/nightly/ to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/ . That should be followed by modifying the job configurations to use this new location. I was trying to skip this for now and do this for final release. But it is possible to have this done now itself. I will try to do this also for M1 release.

**Comment by scottmarlow** [comment]
@alwin-joseph could we do this by Thursday June 18?  If not, when could we?

**Comment by scottmarlow** [comment]
@alwin-joseph also, as mentioned above, I think the new download name would be http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestone/jakartaeetck-9.0.0-M1.zip.

Nice, I see the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/ folder, so almost done :).

**Comment by alwin-joseph** [comment]
> @alwin-joseph could we do this by Thursday June 18? If not, when could we?

Yes. Will do this by Thursday.

**Comment by alwin-joseph** [comment]
> @alwin-joseph also, as mentioned above, I think the new download name would be http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestone/jakartaeetck-9.0.0-M1.zip.
> 
Got it.

> Nice, I see the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/ folder, so almost done :).

For later reference, since this is a one time task, created the directories using below commands from a CI job.

ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null genie.jakartaee-tck@build.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly

ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null genie.jakartaee-tck@build.eclipse.org mkdir -p /home/data/httpd/download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones

I will alter the previous steps mentioned to build the nightly platform TCK bundle at jakartaee9/nightly from here on instead of master/nightly.

**Comment by alwin-joseph** [comment]
> Steps that can be followed (Edited):
> 
>     1. Create new directory to have the bundles for jakartaee9
>        http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestone/
>        http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/
> 
Done.

>     2. Run the https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-build-master/ to build the platform TCK from master (at http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/jakartaeetck-9.0.0.zip) and run sample tests.
> 
Done. There are failures in sample tests currently.

Will continue the next steps and complete by tomorrow(Thursday)

**Comment by alwin-joseph** [comment]
We will be releasing only the EPL licenced platform TCK bundle for this milestone release. I assumed EFTL bundles (eclipse-jakartaeetck-*) can be skipped for M1. Please correct me if it is required too.

**Comment by kwsutter** [comment]
Correct.  EPL only.  Thanks!

**Comment by scottmarlow** [comment]
@alwin-joseph I see that you started jakartaeetck-certification, what is that running for?  jakartaeetck-certification appears to be be setting GF_FULL_BUNDLE_URL to GlassFish 5.1.  

Should we update the promote_jakartaee8_epl_bundles job to scp http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/jakartaeetck-9.0.0.zip to http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestone/jakartaeetck-9.0.0-M1.zip (with actual local mapped drives referenced)?  Or will we do that via a different job?

What can I do to help with remaining steps?

**Comment by scottmarlow** [comment]
@alwin-joseph FYI I updated https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/ to use the new http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly destination.  I'll start that after we are done with copying to http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/jakartaeetck-9.0.0-M1.zip (we use "milestones" + "milestone" above, I assume "milestones" is correct).

**Comment by alwin-joseph** [comment]
> @alwin-joseph FYI I updated https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master/ to use the new http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly destination. I'll start that after we are done with copying to http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/jakartaeetck-9.0.0-M1.zip (we use "milestones" + "milestone" above, I assume "milestones" is correct).

Thanks. Sorry, "milestones" is correct

**Comment by alwin-joseph** [comment]
> @alwin-joseph I see that you started jakartaeetck-certification, what is that running for? jakartaeetck-certification appears to be be setting GF_FULL_BUNDLE_URL to GlassFish 5.1.
> 
> Should we update the promote_jakartaee8_epl_bundles job to scp http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/jakartaeetck-9.0.0.zip to http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestone/jakartaeetck-9.0.0-M1.zip (with actual local mapped drives referenced)? Or will we do that via a different job?
> 
> What can I do to help with remaining steps?

Can you please review : https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_epl_bundles/

**Comment by alwin-joseph** [comment]
> > @alwin-joseph I see that you started jakartaeetck-certification, what is that running for? jakartaeetck-certification appears to be be setting GF_FULL_BUNDLE_URL to GlassFish 5.1.
> 
> I ran jakartaeetck-certification to only run servlet & websocket which were failing in jakartaeetck-nightly-run-master run due to glassfish restart issue. I think I set the GF_FULL_BUNDLE_URL separately to use glassfish6, Ill check again.
> 
Also the platform TCK bundle got updated at jakartaee9/nightly with a servlet related PR after the jakartaeetck-nightly-run-master started.

**Comment by scottmarlow** [comment]
> Can you please review : https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_epl_bundles/
Reviewing, I'll make some updates, we can delete the references to:
-     Jakarta XML Registries
-     Jakarta XML RPC
-     Jakarta Deployment
-     Jakarta Management
-

**Comment by alwin-joseph** [comment]
> > Can you please review : https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_epl_bundles/
> 
> Reviewed and removed references to:
> 
>     * XML_REGISTRIES_TCK (Jakarta XML Registries)
> 
>     * XML_RPC_TCK (Jakarta XML RPC)

Thanks. We can run this job once the below jobs complete:
https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/89/ (servlet & websocket) 
https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/45/  

We do have around 50% test failures overall.

I have commented the scp on standalone tcks for now. 
We would need below changes to this job for later.
1. Change name of standalone TCKs with correct versions.
2. Change name of platform TCK for next releases/run of this job.

**Comment by scottmarlow** [comment]
@alwin-joseph just to confirm, are you okay with me running https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_epl_bundles once the two jobs you mentioned above complete?  I would like to push it today, as we do not need any further changes for this milestone.

Good to see test failures down to 50%!

**Comment by alwin-joseph** [comment]
> @alwin-joseph just to confirm, are you okay with me running https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_epl_bundles once the two jobs you mentioned above complete? I would like to push it today, as we do not need any further changes for this milestone.
> 
Sure. Thank you.

> Good to see test failures down to 50%!

**Comment by alwin-joseph** [comment]
> > @alwin-joseph just to confirm, are you okay with me running https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_epl_bundles once the two jobs you mentioned above complete? I would like to push it today, as we do not need any further changes for this milestone.
> 
> Sure. Thank you.
> 
I see the https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-nightly-run-master/45/ is still stuck with the servlet & websocket failing tests, but the https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/89/  completed. So I think it would be ok to even stop the jakartaeetck-nightly-run-master/45/ .

**Comment by scottmarlow** [comment]
I stopped jakartaeetck-nightly-run-master/45, will start promote_jakartaee9_epl_bundles with JAKARTAEE_TCK option enabled.

**Comment by scottmarlow** [comment]
@alwin-joseph excellent!  promote_jakartaee9_epl_bundles worked!  Thanks for taking care of this!

@kwsutter https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/milestones/jakartaeetck-9.0.0-M1.zip is pushed!

**Comment by scottmarlow** [comment]
Closing as milestone 1 is complete.
