### ISSUE TITLE
WebSocket TCK basic batchingAllowed* tests fail if container supports batching

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-tck#35]
Full path of failing tests:

- com/sun/ts/tests/websocket/ee/javax/websocket/remoteendpoint/basic/WSClient.java#batchingAllowedOnClientTest
- com/sun/ts/tests/websocket/ee/javax/websocket/remoteendpoint/basic/WSClient.java#batchingAllowedOnServerTest

The tests fail because after enabling batching, the batched messages are not flushed so the client never receives them causing the test to fail.

PR to follow.

**Comment by ankitoracle** [comment]
Could you please give more details about your setup and environment?I was able to run all the tests in the TCK successfully in an Oracle Linux environment

**Comment by markt-asf** [comment]
I was running the tests against Apache Tomcat 9.0.x which implements batching. 
Setup details here:
https://cwiki.apache.org/confluence/display/TOMCAT/Servlet+TCK

**Comment by markt-asf** [comment]
I'm guessing that you are running the TCK against Glassfish. My expectation from the TCK is that Glassfish doesn't support batching so you won't see these failures. A quick look at the source confirms that:
https://github.com/tyrus-project/tyrus/blob/master/core/src/main/java/org/glassfish/tyrus/core/cluster/RemoteSession.java#L415
https://github.com/tyrus-project/tyrus/blob/master/core/src/main/java/org/glassfish/tyrus/core/cluster/RemoteSession.java#L593
https://github.com/tyrus-project/tyrus/blob/master/core/src/main/java/org/glassfish/tyrus/core/cluster/RemoteSession.java#L593

These failures will only be observed when running on a container, like Tomcat, that supports batching.
