### ISSUE TITLE
Keep certification jobs ready for Jakartaee9 test runs 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#361]
The EFTL & EPL certification jobs in the CI should be updated to provide option to run the jakartaee9 promoted TCK bundles.

Below jobs will be updated to use the Jakartaee9 bundles.
https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-certification/
https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-certification-web/
https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-certification/
https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification/
https://ci.eclipse.org/jakartaee-tck/job/jakartaeetck-certification-web/
https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/

The process we followed for jakartaee8 release:

1. copy nightly/staged EPL/EFTL bundles to promoted directory when the tests are passing in nightly/staged.
2. Trigger the EPL & EFTL certification jobs to use the corresponding bundles at promoted directory. Save the results and send them for review.  For eg: https://ci.eclipse.org/jakartaee-tck/job/standalonetck-certification/70/ was triggered with technologies in Wave 1.

Hence the jobs must be updated to pick the right bundles for Jakartaee9 test runs.

**Comment by scottmarlow** [comment]
+1
