### ISSUE TITLE
Userguide updates & review for JakartaEE 9

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#362]
The userguides and other docs need to be updated and reviewed before promoting the nightly bundles.

/user_guides has the UG related files.

Majorly the TCK versions need to be appended for most of the technologies.

**Comment by scottmarlow** [comment]
+1

**Comment by arjantijms** [comment]
Hi, what's the exact procedure here?

I've been using the Servlet TCK at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-servlet-tck-5.0.0.zip, but the user guides and release notes etc still contain all the Jakarta EE 8 and Servlet 4 references. 

Did this slip through, or is it simply something that still needs to be done? The ballot for Servlet is already starting, so not sure if we are allowed to update this later. cc @kwsutter

**Comment by alwin-joseph** [comment]
@arjantijms The TCK bundles at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ are not the final. Majorly the userguide and doc updates are pending which this issue is created for. Later the reviewed bundles will be moved to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted folder hence freezing changes to the TCK.

Issue https://github.com/eclipse-ee4j/jakartaee-tck/issues/384  created for JMS TCK describes the steps to be followed.
We hope each spec team can volunteer in to update the UG and other documentation in each TCK (I see you already created https://github.com/eclipse-ee4j/jakartaee-tck/pull/389 for this, Thanks.) , other tasks of TCK promotion will be taken care by platform TCK dev team.

**Comment by arjantijms** [comment]
@alwin-joseph Okay, that's clear. Thanks! :)

**Comment by arjantijms** [comment]
@alwin-joseph One more question, do you have any estimate when the first TCKs will be moved to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted at the earliest?

**Comment by alwin-joseph** [comment]
> @alwin-joseph One more question, do you have any estimate when the first TCKs will be moved to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted at the earliest?

I was hoping that we promote the wave 0 & wave 1 standalone TCKs before the end of this week, but that will also depend on how soon the doc/UG work is done.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/526 + https://github.com/eclipse-ee4j/jakartaee-tck/pull/525 can be associated with this issue via this comment :-)

**Comment by scottmarlow** [comment]
I am going to start a new issue for further updates/review of the Platform TCK user guide as it probably deserves its own issue.
