### ISSUE TITLE
TCKs in https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900 have unexpected "eclipse" prefix

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#363]
For example I think that https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/eclipse-expression-language-tck-4.0.0.zip should instead be https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/expression-language-tck-4.0.0.zip

I'm not sure why "eclipse-" prefix was added.

https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/790/artifact/ root folder contains files like "expression-language-tck-4.0.0.version", however, https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/790/artifact/standalone-bundles has files like https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/790/artifact/standalone-bundles/eclipse-expression-language-tck-4.0.0.zip.

This doesn't seem to happen with https://ci.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run-master, so it must be something different in https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900.

**Comment by scottmarlow** [comment]
It looks like the "eclipse-" [prefix is on purpose as per](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker/build_standalone-tcks.sh#L243):
```
    if [[ "$LICENSE" == "EFTL" || "$LICENSE" == "eftl" ]]; then
      echo "copying ${WORKSPACE}/release/${UPPER_TCK}_BUILD/latest/$entry to ${WORKSPACE}/standalone-bundles/eclipse-${strippedEntry}.zip"
      cp ${WORKSPACE}/release/${UPPER_TCK}_BUILD/latest/$entry ${WORKSPACE}/standalone-bundles/eclipse-${strippedEntry}.zip
    else
      echo "copying ${WORKSPACE}/release/${UPPER_TCK}_BUILD/latest/$entry to ${WORKSPACE}/standalone-bundles/${strippedEntry}.zip"
      cp ${WORKSPACE}/release/${UPPER_TCK}_BUILD/latest/$entry ${WORKSPACE}/standalone-bundles/${strippedEntry}.zip
    fi
```

**Comment by scottmarlow** [comment]
@alwin-joseph please do close this issue if you agree the "eclipse-" prefix is okay in the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900

**Comment by alwin-joseph** [comment]
> @alwin-joseph please do close this issue if you agree the "eclipse-" prefix is okay in the TCKs contained in https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900.

Yes , the "eclipse-" was intentional for the EFTL bundles.
Another difference between EFTL & EPL bundles bundles is the LICENSE file present in them.

**Comment by alwin-joseph** [comment]
@dblevins Sorry, are you suggesting that "eclipse-" is not required for EFTL TCK bundles. We were told to rename the EFTL bundles(with EFTL License file) with this prefix for Jakartaee8 release and I did not check if there is a difference for Jakartaee9 now. Can you please help clarify.

**Comment by dblevins** [comment]
Just reopening briefly as "jakarta" is actually the preferred prefix for all the TCKs.  If they do begin with "eclipse-" they will be renamed to "jakarta-" prior to being published by the specification committee tooling:

 - https://github.com/jakartaee/specification-tools/blob/master/promotion/promote-release.sh#L73

That line was added to the script after discussion in the Specification Committee during the end of Jakarta EE 8 when we were mid-voting.  We used that hack as it wasn't reasonable to ask everyone to redo their releases.  Ideally for Jakarta EE 9 the tcks come in with the preferred prefix.

Note there was another recent discussion in the Specification Committee around the name of the project for the Jakarta EE TCK project which currently is "Eclipse Jakarta EE TCK" 

 - https://projects.eclipse.org/projects/ee4j.jakartaee-tck

This is getting renamed to simply "Jakarta EE TCK."   Those minutes should be available soon.

**Comment by dblevins** [comment]
@alwin-joseph Correct and the confusion is very understandable.  It's well agreed the correct trademark is "Jakarta EE" with no proceeding "Eclipse."  However, when it comes to actually applying it there are some cases where confusion has occurred.  We're slowly working through them as we find them.

For reference, here are the official Jakarta EE 8 TCKs:

 - https://download.eclipse.org/jakartaee/platform/8/jakarta-jakartaeetck-8.0.2.zip
 - https://download.eclipse.org/jakartaee/mail/1.6/jakarta-mail-tck-1.6.0.zip

**Comment by alwin-joseph** [comment]
@dblevins Thanks for the details. 

So the https://download.eclipse.org/jakartaee/mail/1.6/eclipse-mail-tck-1.6.0.zip was renamed to https://download.eclipse.org/jakartaee/mail/1.6/jakarta-mail-tck-1.6.0.zip but only  jakarta-mail-tck-1.6.0.zip is actually required and considered as official.

When you have the information, please let us know if we should regenerate the TCK bundles with prefix "jakarta-" instead of "eclipse-".

**Comment by dblevins** [comment]
We should regenerate the TCK bundles with the prefix "jakarta-" and discontinue the "eclipse-" prefix.

**Comment by alwin-joseph** [comment]
> We should regenerate the TCK bundles with the prefix "jakarta-" and discontinue the "eclipse-" prefix.

Thanks, I have made the change and the new bundles with "jakarta-" prefix will be generated in the staged directory.

**Comment by alwin-joseph** [comment]
PR for jakartaee-tcks : 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/365

Commit for debugging TCK: https://github.com/eclipse-ee4j/debugging-support-for-other-languages-tck/commit/80f7bd54cea30be96d9ce8979de4d20fa8e36c2d

Bundles regenerated at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/
