### ISSUE TITLE
Review and promote Jakarta Annotations TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#382]
1. Complete userguide/documentation changes  for Jakarta Annotations TCK.

2. Review the jakarta-annotations-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/  (or annotations-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.

3. Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-annotations-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.

4. Remove the boolean parameter (ANNOTATIONS_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by alwin-joseph** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/372 was 

>     1. Complete userguide/documentation changes  for Jakarta Annotations TCK.
> 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/372 was made for UG changes.

**Comment by scottmarlow** [comment]
- [ ] In jakartaee-tck/user_guides/caj/src/main/jbake/content/config.adoc replace ```Eclipse EE4J Jakarta EE 8``` with ```Jakarta EE 9```.
- [ ] In jakartaee-tck/user_guides/caj/pom.xml, replace ```Jakarta Annotations for Jakarta EE, Release 1.3``` with ```Jakarta Annotations Release 2.0```
- [ ] In jakartaee-tck/install/caj/docs/CAJ2.0-ReleaseNotes.html, remove the list entries under ```The Jakarta Annotations TCK tests have been run on the following platforms``` and include only one entry for ```CentOS 7```.
- [ ]  In jakartaee-tck/install/caj/docs/CAJ2.0-ReleaseNotes.html, change from ```Jakarta Annotations TCK, Version 1.3 Release Notes, September 2019``` to ```Jakarta Annotations TCK, Version 2.0 Release Notes, September 2020```.  This content is different than what shows in the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-annotations-tck-2.0.0.zip, not sure why.

**Comment by alwin-joseph** [comment]
>     * [ ]  In jakartaee-tck/user_guides/caj/src/main/jbake/content/config.adoc replace `Eclipse EE4J Jakarta EE 8` with `Jakarta EE 9`.
> 
>     * [ ]  In jakartaee-tck/user_guides/caj/pom.xml, replace `Jakarta Annotations for Jakarta EE, Release 1.3` with `Jakarta Annotations Release 2.0`
> 
>     * [ ]  In jakartaee-tck/install/caj/docs/CAJ2.0-ReleaseNotes.html, remove the list entries under `The Jakarta Annotations TCK tests have been run on the following platforms` and include only one entry for `CentOS 7`.
> 
>     * [ ]   In jakartaee-tck/install/caj/docs/CAJ2.0-ReleaseNotes.html, change from `Jakarta Annotations TCK, Version 1.3 Release Notes, September 2019` to `Jakarta Annotations TCK, Version 2.0 Release Notes, September 2020`.  This content is different than what shows in the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-annotations-tck-2.0.0.zip, not sure why.

https://github.com/eclipse-ee4j/jakartaee-tck/pull/400 covers above comments.

**Comment by alwin-joseph** [comment]
> This content is different than what shows in the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-annotations-tck-2.0.0.zip, not sure why.

I think we could trigger the build job https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/ only for annotations after the above PR merge.

**Comment by scottmarlow** [comment]
```
I think we could trigger the build job https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/ only for annotations after the above PR merge.
```
:+1:

**Comment by scottmarlow** [comment]
Since https://github.com/eclipse-ee4j/jakartaee-tck/pull/400 is merged, I started https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/27 to build/run Jakarta Annotations TCK.

**Comment by alwin-joseph** [comment]
Thanks. I will be promoting the jakarta-annotations-tck-2.0.0.zip soon. FYI, I had corrected the README for signature tests  (https://github.com/eclipse-ee4j/jakartaee-tck/pull/407) and regenerated the bundle.

**Comment by scottmarlow** [comment]
Thanks @alwin-joseph, I emailed ca-dev@eclipse.org again and asked for +1 or -1 on promoting jakarta-annotations-tck-2.0.0.zip.  I mentioned that will promote jakarta-annotations-tck-2.0.0.zip first thing (your time) on August 4th, so please do promote jakarta-annotations-tck-2.0.0.zip tomorrow when you have time.

If we do get feedback that more changes are needed before you promote it, we can delay for ca-dev@eclipse.org team to create a pull request.

**Comment by scottmarlow** [comment]
@m0mus Could you please confirm that you done with making Annotations TCK changes and are ready to consider the TCK frozen?

If your not planning to make any TCK changes, please us know that as well.

CC @alwin-joseph

**Comment by m0mus** [comment]
@scottmarlow If the only signature test is updated (which I think it is) it's all good.

**Comment by alwin-joseph** [comment]
The caj tck at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-annotations-tck-2.0.0.zip will be regenerated and released to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-annotations-tck-2.0.0.zip soon.

**Comment by alwin-joseph** [comment]
> 
>     3. Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-annotations-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
> 
>     4. Remove the boolean parameter (ANNOTATIONS_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

Completed the above steps and promoted the Annotations TCK bundle. The latest bundle is available at  https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-annotations-tck-2.0.0.zip  now.
