### ISSUE TITLE
Review and promote Jakarta Concurrency TCK for JakartaEE 9 release 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#383]
1. Complete userguide/documentation changes  for Jakarta Concurrency TCK.

2. Review the jakarta-concurrency-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/  (or concurrency-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.

3. Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-concurrency-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.

4. Remove the boolean parameter (CONCURRENCY_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by smillidge** [comment]
@alwin-joseph what user guide changes are typically needed?

**Comment by alwin-joseph** [comment]
@smillidge 
I see Ed already made the changes for concurrency : https://github.com/eclipse-ee4j/jakartaee-tck/pull/411

**Comment by scottmarlow** [comment]
@smillidge Could you please confirm that you done with making Concurrency TCK changes and are ready to consider the TCK frozen?  

CC @alwin-joseph @edbratt

**Comment by smillidge** [comment]
Yes current concurrency passes the TCK

**Comment by edbratt** [comment]
The question I would ask is: Does the TCK archive (ZIP), meet the 
requirements of the API committer team? (Does the CI pass? [yes], are 
the Docs. updated and correct?) Since this is part of the Specification, 
the TCK dev. team needs a green light to promote to the next level of 
Stability.

I think the Doc. updates are correct (I made them and they were 
approved). @smillidge <https://github.com/smillidge> does anyone else 
from the API team need (or want) to weigh in?

**Comment by scottmarlow** [comment]
:+1: Thanks Ed

**Comment by smillidge** [comment]
@edbratt I will put a mail out onto the concurrency-dev list pointing to this issue.

**Comment by smillidge** [comment]
Please promote the TCK

**Comment by alwin-joseph** [comment]
> Please promote the TCK

The concurrency tck is now promoted to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-concurrency-tck-2.0.0.zip
