### ISSUE TITLE
Review and promote Jakarta Messaging TCK for JakartaEE 9 release 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#384]
1. Complete userguide/documentation changes  for Jakarta Messaging TCK.

2. Review the jakarta-messaging-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/  (or messaging-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.

3. Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-messaging-tck-3.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.

4. Remove the boolean parameter (MESSAGING_TCK)  and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the bundle is not promoted again.

**Comment by scottmarlow** [comment]
@arjantijms Could you please confirm when you are done with making Messaging TCK changes and are ready to consider the TCK frozen?

I think this is pending https://github.com/eclipse-ee4j/jakartaee-tck/pull/415 being merged and possibly Alwin making changes to platform.mode via https://github.com/eclipse-ee4j/jakartaee-tck/pull/417.

CC @alwin-joseph @edbratt

**Comment by edbratt** [comment]
https://github.com/jakartaee/specifications/pull/256

**Comment by alwin-joseph** [comment]
The messaging TCK is updated at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-messaging-tck-3.0.0.zip with latest documentation changes.

**Comment by scottmarlow** [comment]
The messaging TCK will be updated pending https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/76 completing and passing all tests.

**Comment by scottmarlow** [comment]
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-messaging-tck-3.0.0.zip is updated to address https://github.com/eclipse-ee4j/jakartaee-tck/issues/549#issuecomment-713401797.

Please do let us know when it is time to copy that TCK to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted

**Comment by arjantijms** [comment]
Thanks! I'll do a run here right away with the new TCK.

**Comment by arjantijms** [comment]
https://ci.eclipse.org/openmq/job/2_openmq-run-tck-against-staged-build/9/ is now running.

**Comment by arjantijms** [comment]
The TCK just finished, and passed:

```
[javatest.batch] Number of Tests Passed      = 904
[javatest.batch] Number of Tests Failed      = 0
[javatest.batch] Number of Tests with Errors = 0
[javatest.batch] ********************************************************************************
```

@scottkurz I think you already copied the TCK to promoted in the mean time?

**Comment by edbratt** [comment]
If I could get a review and/or approval for my TCK Summary PR 
<https://github.com/eclipse-ee4j/glassfish/pull/23249>, it could be 
merged and we could fix the 404 in the CCR issue 
<https://urldefense.com/v3/__https://github.com/eclipse-ee4j/jsp-api/issues/190__;!!GqivPVa7Brio!Ni1Jp2bmM5OaqiHehz9MnEklHS9zLtHENqNPlQb1VAHgIks6W2oVUrt7847z8Q8$>.

Thanks,

-- Ed

**Comment by scottmarlow** [comment]
@arjantijms 
> The TCK just finished, and passed:
> 
> ```
> [javatest.batch] Number of Tests Passed      = 904
> [javatest.batch] Number of Tests Failed      = 0
> [javatest.batch] Number of Tests with Errors = 0
> [javatest.batch] ********************************************************************************
> ```

+100

> 
> @scottkurz I think you already copied the TCK to promoted in the mean time?

No, https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted does not yet contain the jakarta-messaging-tck-3.0.0.zip.  We are waiting for your okay to copy the TCK there.  

Can we copy the TCK to promoted now?

**Comment by arjantijms** [comment]
@scottmarlow I say the messaging TCK here:

https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0.zip

**Comment by scottmarlow** [comment]
> @scottmarlow I say the messaging TCK here:
> 
> https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0.zip

Thanks, I see that now also.

**Comment by alwin-joseph** [comment]
The promoted tck https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0.zip  is outdated as we rebuilt the staged bundle. Can we update the promoted tck.

Check the dates for below:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-messaging-tck-3.0.0-tckinfo.txt
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0-tckinfo.txt

**Comment by arjantijms** [comment]
@alwin-joseph I see, thx!

To re-promote, I guess we just run the initial promotion script again?

**Comment by alwin-joseph** [comment]
> @alwin-joseph I see, thx!
> 
> To re-promote, I guess we just run the initial promotion script again?

Yes  and I see you already did it! Thanks

**Comment by arjantijms** [comment]
> Yes and I see you already did it! Thanks

Indeed, it's now available with the correct date: 

https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-messaging-tck-3.0.0-tckinfo.txt

I removed the messaging boolean again from the script.
