### ISSUE TITLE
Review and promote JAXWS TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#386]
1. Complete userguide/documentation changes  for JAXWS TCK.

2. Review the jakarta-xml-ws-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/  (or xml-ws-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.

3. Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-xml-ws-tck-3.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.

4. Remove the boolean parameter (XML_WS_TCK)  and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by alwin-joseph** [comment]
>     1. Complete userguide/documentation changes  for JAXWS TCK.
> 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/380 is under review.

**Comment by scottmarlow** [comment]
@alwin-joseph does #5 look correct?

**Comment by alwin-joseph** [comment]
> @alwin-joseph does 5 look correct?

Yes that is what I had in mind. Bit naive but would serve the purpose I think.

**Comment by scottmarlow** [comment]
@alwin-joseph please do reword if you like. :-)

**Comment by alwin-joseph** [comment]
> @alwin-joseph please do reword if you like. :-)

I meant the step of commenting out the job config is naive, no issue with the wordings. :)

**Comment by lukasj** [comment]
see #435

**Comment by alwin-joseph** [comment]
FYI JAXWS tck needs namespace updates before promoting them.

**Comment by alwin-joseph** [comment]
Jaxws tck is now promoted to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-xml-ws-tck-3.0.0.zip
