### ISSUE TITLE
Review and promote Jakarta Expression Language 4.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#387]
1. Complete userguide/documentation changes for Jakarta Expression Language TCK.
1. Review the jakarta-expression-language-tck-4.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or expression-language-tck-4.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
1. Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-expression-language-tck-4.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
1. Remove the boolean parameter (EL_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
Pending review of https://github.com/eclipse-ee4j/jakartaee-tck/pull/367 by @markt-asf + @edbratt

**Comment by alwin-joseph** [comment]
>     1. Complete userguide/documentation changes for Jakarta Expression Language TCK.
> 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/367 is merged.

**Comment by scottmarlow** [comment]
Thanks @alwin-joseph, I asked for [feedback from the el-dev](https://www.eclipse.org/lists/el-dev/msg00064.html) community on promoting jakarta-expression-language-tck-4.0.0.zip.

**Comment by alwin-joseph** [comment]
> Thanks @alwin-joseph, I asked for [feedback from the el-dev](https://www.eclipse.org/lists/el-dev/msg00064.html) community on promoting jakarta-expression-language-tck-4.0.0.zip.

Just checking the email, I think you put annotations instead of EL and the link to the bundle has extra '_' in between.

**Comment by arjantijms** [comment]
Thanks for all the work here @scottmarlow and others!

At a glance the TCK itself works, and the staged TCK passes with the staged 4.0.0 versions of the Expression Language Api and impl, and the latest GF snapshot here: https://ci.eclipse.org/el/job/2_expression-language-run-tck-against-staged-build

**Comment by scottmarlow** [comment]
@arjantijms Could you please confirm that you done with making TCK changes and are ready to consider the TCK frozen?

CC: @alwin-joseph

**Comment by arjantijms** [comment]
@scottmarlow I'm done making TCK changes, and I think it can be frozen.

**Comment by alwin-joseph** [comment]
Thanks. I have promoted the tck at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-expression-language-tck-4.0.0.zip.

**Comment by arjantijms** [comment]
Changed the standalone job at https://ci.eclipse.org/el/job/2_expression-language-run-tck-against-staged-build/ over to the Promoted TCK.

**Comment by scottmarlow** [comment]
Closing, please reopen this issue if needed again.
