### ISSUE TITLE
Review and promote Jakarta JSON Processing 2.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#390]
1.  Complete userguide/documentation changes for Jakarta JSON Processing TCK.
1.  Review the jakarta-jsonp-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or jsonp-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
1.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-jsonp-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
1.  Remove the boolean parameter (JSONP_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
CC @alwin-joseph

**Comment by alwin-joseph** [comment]
>     1. Complete userguide/documentation changes for Jakarta JSON Processing TCK.
> 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/373 under review

**Comment by alwin-joseph** [comment]
> > ```
> > 1. Complete userguide/documentation changes for Jakarta JSON Processing TCK.
> > ```
> 
> #373 under review

https://github.com/eclipse-ee4j/jakartaee-tck/pull/373 merged and latest bundles generated.

**Comment by lukasj** [comment]
see #433

**Comment by alwin-joseph** [comment]
The issues mentioned in https://github.com/eclipse-ee4j/jakartaee-tck/issues/433 was corrected by https://github.com/eclipse-ee4j/jakartaee-tck/pull/437 and latest Jsonp-tck refreshed at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-jsonp-tck-2.0.0.zip

**Comment by lukasj** [comment]
minor fix in #473

**Comment by lukasj** [comment]
#475 should be the last change. @alwin-joseph  Once that is integrated and bundle refreshed we should consider it done.

cc @edbratt

**Comment by m0mus** [comment]
@alwin-joseph please promote

**Comment by alwin-joseph** [comment]
#475 merged and jsonp tck refreshed at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-jsonp-tck-2.0.0.zip.

**Comment by alwin-joseph** [comment]
The staged bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-jsonp-tck-2.0.0.zip will be promoted to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jsonp-tck-2.0.0.zip soon.

**Comment by alwin-joseph** [comment]
@m0mus @lukasj The jsonp tck 2.0.0 has been promoted to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jsonp-tck-2.0.0.zip.

**Comment by scottmarlow** [comment]
Closing, please reopen this issue if needed again.
