### ISSUE TITLE
Review and promote Jakarta Websocket 2.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#395]
1.  Complete userguide/documentation changes for Jakarta Websocket TCK.
2.  Review the jakarta-websocket-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or websocket-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-websocket-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
4.  Remove the boolean parameter (WEBSOCKET_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by gabrielbussolo** [comment]
@alwin-joseph can u exemplify what type of changes I can search across jakarta-websocket-tck-2.0.0.zip?
thanks

**Comment by scottmarlow** [comment]
There may be more version updates than you made in your pull request:
```
wget https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-websocket-tck-2.0.0.zip
unzip jakarta-websocket-tck-2.0.0.zip
grep -ril Websocket.*Version.*1.
websocket-tck/docs/staging/rules.html:for Jakarta WebSocket Version 1.1.</p></td>
websocket-tck/docs/staging/intro.html:<p>WebSocket Version: The WebSocket 1.1 TCK
websocket-tck/docs/staging/intro.html:<p>WebSocket TCK version 1.1, which includes:</p>
websocket-tck/docs/staging/install.html:<p>WebSocket TCK version 1.1, which includes:</p>
websocket-tck/docs/assertions/WebSocketJavadocAssertions.html:</font></TD><TD align="left" valign="center"><font size="1PT">Returns the version of the websocket protocol currently being used. This is taken as the value of the Sec-WebSocket-Version header used in the opening handshake. i.e. "13".</font></TD><TD align="center" valign="center"><font size="1PT">true</font></TD><TD align="center" valign="center"><font size="1PT">
websocket-tck/docs/WebSocketTCK1.1-ReleaseNotes.html:<h1>Jakarta WebSocket Technology Compatibility Kit, Version 1.1<br>
websocket-tck/docs/WebSocketTCK1.1-ReleaseNotes.html:<p>The Jakarta WebSocket, Version 1.1 Technology Compatibility Kit (TCK) includes the following items:</p>
websocket-tck/docs/WebSocketTCK1.1-ReleaseNotes.html:     <li><strong>Signature test</strong> that checks that all of the public APIs are supported in the Jakarta WebSocket Version 1.1 implementation that is being tested</li>
websocket-tck/docs/WebSocketTCK1.1-ReleaseNotes.html:<li>Eclipse Compatible Implementation for WebSocket  Version 1.1</li>
```

I also searched for ```Java EE``` and see a lot of that (some of which is in Java sources that are also included in other TCKS (e.g. signature, deployment handling)  and a reference to ```JSR-88``` via websocket-tck/src/com/sun/ts/tests/signaturetest/SigTest.java.

A big lesson is that we should update TCK documention earlier in the development process, as some of these references could of been updated globally sooner.

**Comment by edbratt** [comment]
Most textual changes are made in the .inc files (in 
src/main/jbake/content). Most of the version change details will be 
corrected by updating the properties in 
src/main/jbake/content/attributes.conf

Look for any text that is javax and it should probably be changed to jakarta

I don't think we should be modifying anything in the signature test 
material. OR, maybe differently: we should file an issue and ask Alwin 
to look into fixing that.

**Comment by scottmarlow** [comment]
```
I don't think we should be modifying anything in the signature test
material. OR, maybe differently: we should file an issue and ask Alwin
to look into fixing that.
```
I opened https://github.com/eclipse-ee4j/jakartaee-tck/issues/420 for any documentation changes that we want to make post EE 9, like the signature test material.

**Comment by m0mus** [comment]
@alwin-joseph Can you please re-stage Websocket TCK?

**Comment by alwin-joseph** [comment]
> @alwin-joseph Can you please re-stage Websocket TCK?

Done now.

**Comment by markt-asf** [comment]
@alwin-joseph The TCK that was staged appears to be incomplete. The /dist directory (containing the WARs) is empty.

**Comment by alwin-joseph** [comment]
> @alwin-joseph The TCK that was staged appears to be incomplete. The /dist directory (containing the WARs) is empty.

I see it now. Let me fix it and restage.

**Comment by alwin-joseph** [comment]
> > @alwin-joseph The TCK that was staged appears to be incomplete. The /dist directory (containing the WARs) is empty.
> 
> I see it now. Let me fix it and restage.

I have restaged the websocket tck now at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-websocket-tck-2.0.0.zip after the fix. Thanks for pointing the issue.

**Comment by markt-asf** [comment]
Thanks for the updated TCK. I've downloaded and run it successfully against Apache Tomcat 10. I skimmed the documentation very quickly. I didn't notice any major issues although the number of tests in the release notes looks wrong (I see 731 + 2 skipped + 1 signature = 734 in total).

**Comment by alwin-joseph** [comment]
> Thanks for the updated TCK. I've downloaded and run it successfully against Apache Tomcat 10. I skimmed the documentation very quickly. I didn't notice any major issues although the number of tests in the release notes looks wrong (I see 731 + 2 skipped + 1 signature = 734 in total).

 This was updated and the TCK refreshed at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-websocket-tck-2.0.0.zip. Please let us know if any more changes required for the websocket TCK. If not shall we proceed to promote it to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-websocket-tck-2.0.0.zip?

**Comment by markt-asf** [comment]
Looks good to me.

**Comment by edbratt** [comment]
Please promote the current staged WebSocket TCK.

**Comment by alwin-joseph** [comment]
> Please promote the current staged WebSocket TCK.

Done.  websocket tck is now available at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-websocket-tck-2.0.0.zip.
