### ISSUE TITLE
Review and promote Jakarta Servlet 5.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#396]
1.  Complete userguide/documentation changes for Jakarta Servlet TCK.
2.  Review the  jakarta-servlet-tck-5.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or servlet-tck-5.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-servlet-tck-5.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
4.  Remove the boolean parameter (SERVLET_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by alwin-joseph** [comment]
>     1. Complete userguide/documentation changes for Jakarta Servlet TCK.
> 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/389 under review

**Comment by arjantijms** [comment]
No more changes are needed. I think the TCK can now be promoted.

**Comment by alwin-joseph** [comment]
> No more changes are needed. I think the TCK can now be promoted.

Done. servlet tck now available at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-servlet-tck-5.0.0.zip

**Comment by arjantijms** [comment]
Thanks, I adjusted the standalone TCK to run from the promoted location: https://ci.eclipse.org/servlet/job/2_servlet-run-tck-against-staged-build/36/

**Comment by scottmarlow** [comment]
Closing, please reopen if needed again.
