### ISSUE TITLE
Review and promote Jakarta SOAP 2.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#397]
1.  Complete userguide/documentation changes for Jakarta SOAP 2.0.0 TCK.
2.  Review the jakarta-soap-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or soap-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-soap-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
4.  Remove the boolean parameter (SOAP_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by alwin-joseph** [comment]
>     1. Complete userguide/documentation changes for Jakarta SOAP 2.0.0 TCK.
> 
https://github.com/eclipse-ee4j/jakartaee-tck/pull/376 under review

**Comment by alwin-joseph** [comment]
> > ```
> > 1. Complete userguide/documentation changes for Jakarta SOAP 2.0.0 TCK.
> > ```
> 
> #376 under review

https://github.com/eclipse-ee4j/jakartaee-tck/pull/376 merged, latest bundle generated.

**Comment by lukasj** [comment]
see #434

**Comment by alwin-joseph** [comment]
SOAP TCK refreshed with latest changes at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-soap-tck-2.0.0.zip.

**Comment by lukasj** [comment]
#472 should address remaining issues

**Comment by lukasj** [comment]
and #476 should be the last one. Once those are in and new build is staged, this should be done (I hope) - at least till someone else finds a problem...

cc @edbratt

**Comment by alwin-joseph** [comment]
the last changes were merged soap tck refreshed now at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-soap-tck-2.0.0.zip.

**Comment by alwin-joseph** [comment]
As the new build is staged, please confirm if it can be promoted.

**Comment by lukasj** [comment]
looks good enough for me, thx!

**Comment by alwin-joseph** [comment]
The soap tck is now promoted to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-soap-tck-2.0.0.zip. Please note it has been regenerated recently to do more corrections. Please use the promoted bundle for Certification.

**Comment by lukasj** [comment]
done, thx

**Comment by scottmarlow** [comment]
Closing, please reopen if needed again.
