### ISSUE TITLE
Missing libraries

### ISSUE THREAD

**Issue by ggam** [eclipse-ee4j/jakartaee-tck#4]
There are some missing JAR libraries that need to be on the `/lib` folder. From what I see on https://github.com/eclipse-ee4j/jakartaee-tck/blob/febd0176d513a2b4d9b13354bf69b6d6c03d79a3/release/tools/common.xml#L78 they are:

* ant_sun.jar
* ant-contrib-1.0b3.jar
* javatest.jar
* tsharness.jar
* apiCheck.jar
* sigtest.jar
* tspackager.jar
* commons-httpclient.jar  (3.1 implied from NOTICE)
* commons-logging.jar (1.1.1 implied from NOTICE)
* jdom-1.1.3.jar
* jaxen-core-1.0.jar
* jaxen-1.1.6.jar
* saxpath.jar (1.0 implied from NOTICE)

Some of them are easy to find but others don't give much clues. Particularly the `ant_sun.jar`, that should have a class `com.sun.ant.taskdefs.common.PathTranslator` that I can't find on Google.

The code doesn't have any Ant task or so to download the needed dependencies.

**Comment by bhatpmk** [comment]
We are yet to include the archives, will include them as soon as we get the approval.

**Comment by ggam** [comment]
Thanks @bhatpmk

**Comment by vietk** [comment]
Hello

Any ideas about the availability of the missing lib folders ?
i.e:  Days, weeks or months  ? :D 

Thanks for your work guys

**Comment by bhatpmk** [comment]
The CQs are filed for the libraries and we are waiting for the approval. The libraries will be included as soon as we get the approval from Eclipse IP team. Unfortunately I don't know the date by which we can expect the approval.

**Comment by vietk** [comment]
Thanks for the update @bhatpmk

**Comment by SAPessi** [comment]
Anything new here @bhatpmk (sorry to bug you again)?

**Comment by bhatpmk** [comment]
There are only couple of libraries, pending for approval from Eclipse IP team. I will update here, once those libraries are approved and are part of the repository.

**Comment by anajosep** [comment]
The missing libraries are included now. The README contains wiki link which details the steps to build and run Jakarta EE TCK bundle from scratch. Closing this issue.
