### ISSUE TITLE
[spec]SpecAssertions.html appear in two locations

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#404]
Hi,

I noticed that the [spec]SpecAssertions.html files appear to be checked-in in two locations. E.g.

install/jacc/docs/assertions/spec/JACCSpecAssertions.html
internal/docs/jacc/JACCSpecAssertions.html
I think this is highly confusing and very error prone. Can we delete one of those?

**Comment by alwin-joseph** [comment]
I agree the same file appears at both locations, and looks like this is happening for most other TCKs too. 

From release/tools/jacc.xml I see that the install/jacc/docs/ is the one added to the TCK bundle, so I think better to retain  install/jacc/docs/assertions/spec/JACCSpecAssertions.html and remove internal/docs/jacc/JACCSpecAssertions.html unless I am missing something.
