### ISSUE TITLE
Servlet TCK serverpushInitTest uses case sensitive test for HTTP headers

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-tck#41]
HTTP header names are case insensitive. This test (full name below) performs case sensitive tests which will fail if the container uses, for example, all lower case HTTP header names.

`com/sun/ts/tests/servlet/spec/serverpush/Client.java#serverPushInitTest`

PR to follow shortly.

**Comment by bshannon** [comment]
This does sound like a valid bug, but...

We should consider whether this is the kind of change we should hold until after Jakarta EE 8,
to avoid divergence between the Java EE 8 TCK and the Jakarta EE 8 TCK.

**Comment by markt-asf** [comment]
The PR (when it arrives) will only be for master - not EE4J_8. It would be nice to get this in a nightly build but delaying merging the PR isn't going to cause me any great hassle.
