### ISSUE TITLE
Need JAX-RS TCK test case for handling arrays as parameters (query, cookie, header, etc.)

### ISSUE THREAD

**Issue by andymc12** [eclipse-ee4j/jakartaee-tck#413]
In Jakarta RESTful Web Services issue https://github.com/eclipse-ee4j/jaxrs-api/issues/890 (targeted for 3.1 / post EE-9), implementations are required to handle array types as various types of parameters to resource methods - ex:
```
@GET
public List<Widget> getWidgetByTypes(@QueryParam("types") String[] typeNames) { //...
```

The TCK should already test collections in https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxrs/ee/rs/queryparam/QueryParamTest.java - this class should probably add `@QueryParam` fields for array types.

**Comment by scottmarlow** [comment]
@andymc12 is this a TCK challenge or simply a TCK improvement for the future?

CC @spericas

**Comment by andymc12** [comment]
@scottmarlow This is a request for a new/updated test (improvement).  It is intended to test compatibility for a new function in RESTful WS 3.1 (EE 9.1?).  Thanks

**Comment by alwin-joseph** [comment]
Duplicate issue raised https://github.com/eclipse-ee4j/jaxrs-api/issues/1019 , now that the TCK is moved to new jaxrs-api.

**Comment by gurunrao** [comment]
closing duplicate issue.
