### ISSUE TITLE
Missing content from 'staging' folder in archives

### ISSUE THREAD

**Issue by edbratt** [eclipse-ee4j/jakartaee-tck#422]
In reviewing nightly build archive contents, I notice that the img and css folders from 'staging' (e.g. persistence-tck-3.0.0.zip: /persistence-tck/docs/staging/) are not being copied into the .zip archives.
I checked:
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/soap-tck-2.0.0.zip (date: 2020-08-11)
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly/persistence-tck-3.0.0.zip (date: 2020-08-11)

Please investigate and correct if necessary.

**Comment by alwin-joseph** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/424 fixes this.
