### ISSUE TITLE
Review and promote Jakarta Faces 3.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#428]
- [X] 1.  Complete userguide/documentation changes for Jakarta Faces 3.0.0 TCK
- [x] 2.  Review the jakarta-faces-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or faces-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-faces-tck-3.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (FACES_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
Note that https://github.com/eclipse-ee4j/jakartaee-tck/pull/474 changes Java EE DTDs references in JSF tests to use Jakarta EE 9 XSD.

**Comment by scottmarlow** [comment]
@arjantijms would you like us to stage a minor (tool doc versions corrected) update to the staged Faces 3.0.0 TCK?  More details are below.

https://github.com/eclipse-ee4j/jakartaee-tck/pull/525 is merged which corrects version numbers for tools:
- DOM
- Apache Commons HTTP Client
- Apache Commons Logging
- Apache Commons Codec

**Comment by arjantijms** [comment]
Especially if #474 hasn't been included in the current staged Faces 3.0.0 TCK that would be really important indeed. Otherwise nice to have.

**Comment by scottmarlow** [comment]
@alwin-joseph thanks!

@arjantijms http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-faces-tck-3.0.0.zip was updated via https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/80/console

**Comment by arjantijms** [comment]
@alwin-joseph @scottmarlow 

The TCK bundle is ready to be promoted. I anticipate no further changes.

**Comment by alwin-joseph** [comment]
> @alwin-joseph @scottmarlow
> 
> The TCK bundle is ready to be promoted. I anticipate no further changes.

Promote Faces TCK to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-faces-tck-3.0.0.zip. Thanks.

**Comment by arjantijms** [comment]
Thanks @alwin-joseph !
