### ISSUE TITLE
Review and promote Jakarta JSON Binding 2.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#429]
1.  Complete userguide/documentation changes for Jakarta JSON Binding 2.0.0 TCK.
2.  Review the jakarta-jsonb-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or jsonb-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-jsonb-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
4.  Remove the boolean parameter (JSONB_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by m0mus** [comment]
Documentation is fixed by https://github.com/eclipse-ee4j/jakartaee-tck/pull/439

**Comment by alwin-joseph** [comment]
jsonb tck is now promoted and available at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jsonb-tck-2.0.0.zip

**Comment by scottmarlow** [comment]
@m0mus I see that https://github.com/jakartaee/specifications/pull/253 is merged but still wanted to mention that we made a minor jsonb-tck zip update via https://github.com/eclipse-ee4j/jakartaee-tck/pull/525 which corrected the versions for tools:
- DOM
- Apache Commons HTTP Client
- Apache Commons Logging
- Apache Commons Codec

If there is anything that you would like us to do in terms of staging a new jsonb-tck-2.0.1.zip for this minor doc change, please do reopen this issue and comment here that you would like it a new TCK staged.

CC @alwin-joseph
