### ISSUE TITLE
JSONP TCK issues

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#433]
* assertion file for version 2.0 is missing
* assertion file for version 1.1 is not linked from `docs/index.html` (https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jsonp/docs/index.html)
* release notes lists `Oracle JSON-P Reference Implementation Version 2.0.0` as one compatible implementation - I do not think that is the correct name of the Eclipse/EE4J implementation project
* `Jakarta JSON Processing Technology Compatibility Kit, Version 2.0 User's Guide` in the `docs/index.html` should be clickable link to actual user guide contained in the tck zip

**Comment by alwin-joseph** [comment]
>     * assertion file for version 2.0 is missing
> 
>     * assertion file for version 1.1 is not linked from `docs/index.html` (https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jsonp/docs/index.html)
> 
>     * release notes lists `Oracle JSON-P Reference Implementation Version 2.0.0` as one compatible implementation - I do not think that is the correct name of the Eclipse/EE4J implementation project
> 
>     * `Jakarta JSON Processing Technology Compatibility Kit, Version 2.0 User's Guide` in the `docs/index.html` should be clickable link to actual user guide contained in the tck zip

Thanks for the review. The tck has both html & pdf usersguide. The clickable link can be to first page of the html guide I suppose.

https://github.com/eclipse-ee4j/jakartaee-tck/pull/437 will be addressing this.

**Comment by lukasj** [comment]
> The clickable link can be to first page of the html guide I suppose.

Yes, pointer to html toc is OK. Having additional `(pdf)` pointer is nice to have.

**Comment by alwin-joseph** [comment]
>     * assertion file for version 2.0 is missing
> 
>     * assertion file for version 1.1 is not linked from `docs/index.html` (https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jsonp/docs/index.html)
> 
Is it really required to link the older assertions. If the older assertion files does not have much relevance, we could remove it. I do see for most TCKs an older version is available but only the latest is linked to index.html

**Comment by lukasj** [comment]
> Is it really required to link the older assertions.

Depends on the point of view. If the file is present in the distribution then it should be reachable from docs somehow. If the "old" file gets removed, no link is needed and problem is solved too.

I would say that only versions required by TCK should be there, so EE 8 and EE 9 versions. (Read as latest is mandatory, EE 8 optional)
