### ISSUE TITLE
xml ws tck issues

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#435]
* ` Jakarta XML Web Services 3.0 Technology Compatibility Kit User's Guide` in the docs/index.html as well as in release notes should be clickable link to actual user guide contained in the tck distribution
* references to `Eclipse GlassFish Server 5.1` should be replaced with `6.0` (ie in release notes)
* release notes
  *  should be dated to `September 2020` instead of `September 2019`
  * API tests should probably include `jakarta.jws` and `jakarta.jws.soap` packages
  * references to `Jakarta EE 8` should be updated to `Jakarta EE 9`
* all references to and uses of `endorsed` mechanism should be removed since `jakarta` packages are not "overriding" APIs included in JDK
* It is unclear whether one should be using Apache Tomcat 8 or 10 - ie release notes in section `Quick Steps to Configure Apache Tomcat 8 for Jakarta XML Web Services TCK` describes steps `to configure Apache Tomcat 10`
* javadoc assertion file refers `javax.lang.IllegalStateException` but no such exception class exists - should be `java.lang.IllegalStateException` instead
* spec assertion has reference to `javax.activation.DataSource`, should be `jakarta.activation.DataSource` instead
* user guide, section 3.2, step 4
  * `jaxws-api.jar` and `jaxb-api.jar` are `jakarta.xml.ws-api.jar` and `jakarta.xml.bind-api.jar` and these are not expected to be put to `endorsed` folder
  * `jsr181.jar` is now `jakarta.jws-api.jar`
  * `policy.jar` is not there anymore (is included in `jaxws-rt.jar` file)
  * `resolver.jar` should be required only on non-Oracle/non-OpenJDK based JDKs
* Ant is not included in the TCK distribution, so all references to `<TS_HOME>/tools/ant/bin` should either be removed or updated appropriately (mostly in the user guide, section 4)

**Comment by m0mus** [comment]
I fixed `easy` issues in #440. Assigning it to @alwin-joseph to fix `endorsed` related and TomCat related issues.

**Comment by alwin-joseph** [comment]
> 
>     * Ant is not included in the TCK distribution, so all references to `<TS_HOME>/tools/ant/bin` should either be removed or updated appropriately (mostly in the user guide, section 4)

Looks like ant references need to be corrected throughout all the userguides and it would be ideal if we make the update uniformly, possibly with a single change. I think it should ideally list  under "3.2 Installing the Software" along with Java SE.  then set ANT_HOME, replace <TS_HOME>/tools/ant/bin with <ANT_HOME>/bin etc. I will correct these. Thanks.

**Comment by alwin-joseph** [comment]
> > ```
> > * Ant is not included in the TCK distribution, so all references to `<TS_HOME>/tools/ant/bin` should either be removed or updated appropriately (mostly in the user guide, section 4)
> > ```
> 
> Looks like ant references need to be corrected throughout all the userguides and it would be ideal if we make the update uniformly, possibly with a single change. I think it should ideally list under "3.2 Installing the Software" along with Java SE. then set ANT_HOME, replace <TS_HOME>/tools/ant/bin with <ANT_HOME>/bin etc. I will correct these. Thanks.

Ant references were corrected in the latest staged bundles.
