### ISSUE TITLE
xml binding tck issues

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#436]
* no release notes, spec/javadoc assertions in the tck distribution - all others I checked do have these, so I believe that at least release notes should be added
* user guide:
  * uses `javax.xml.bind` packages, should be `jakarta.xml.bind`
  * talks about `XML Binding 2.3`, should be `XML Binding 3.0` instead
  * copyright footer should probably be updated to `2018, 2020`
  * FAQ A3 should probably update `<TS_HOME>/lib/jaxb_tck23.jtx` to `<TS_HOME>/lib/jaxb_tck30.jtx`

**Comment by alwin-joseph** [comment]
jaxb-tck is built from separate repo https://github.com/eclipse-ee4j/jaxb-tck. The userguide and doc changes are pending. 

Moved this issue to jaxb-tck repo as https://github.com/eclipse-ee4j/jaxb-tck/issues/19 .
