### ISSUE TITLE
Servlet TCK denyUncovered tests depend on container specific behaviour

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-tck#45]
The tests in question are:

- `src/com/sun/ts/tests/servlet/spec/security/denyUncovered/*` (5 tests)

These tests are packaged in `servlet_sec_denyUncovered_web.war` which usually means a context path of `/servlet_sec_denyUncovered_web`.
However, these tests expect a contenxt path of `/servlet_sec_denyUncovered`. The TCK uses a container specific configuration file (https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/spec/security/denyUncovered/servlet_sec_denyUncovered_web.war.sun-web.xml) to ensure that these tests pass with Glassfish. This work-around does not work with other containers.

Possible solutions include:
- update the tests to use the actual context path
- align the name of the WAR file with the expected context path

I've no strong preference.
I'm happy to try and produce a PR for this once there is consensus on the desired approach.

**Comment by RohitKumarJain** [comment]
Hi Mark,

Is there any way to contact you regarding this issue, as I am unable to locate your email_id. I would like to take further inputs.

regards,
Rohit Jain
(rohit.ku.jain@oracle.com)

**Comment by markt-asf** [comment]
This issue will occur when running the TCK on any container that doesn't use the Glassfish specific sun-web.xml configuration file. That file is not part of the Servlet specification and should not be required in order to pass the TCK. I observed the issue running the Servlet TCK against Apache Tomcat.

To reproduce this issue, I suggest you simply remove that file and run the tests. They will then fail on all containers (including Glassfish) because the actual context path will be `/servlet_sec_denyUncovered_web` whereas the tests expect it to be `/servlet_sec_denyUncovered`

**Comment by RohitKumarJain** [comment]
Thanks, l have started investigating it, will update you with my findings.

**Comment by RohitKumarJain** [comment]
Hi Mark, 

As discussed over the email you were successfully able to deploy the war file in tomcat without any failure. For the same, I am creating the PR, could you please look into it?

PR details: https://github.com/eclipse-ee4j/jakartaee-tck/pull/126

Thanks,
Rohit

**Comment by alwin-joseph** [comment]
Closing this issue as the changes are merged

**Comment by olamy** [comment]
everything was fine until this revert https://github.com/eclipse-ee4j/jakartaee-tck/commit/c990b0279c5f3e30699d01ef435d33835198bb3c

**Comment by olamy** [comment]
@alwin-joseph @RohitKumarJain  please reopen or please revert the revert

**Comment by alwin-joseph** [comment]
Reverting the revert in https://github.com/eclipse-ee4j/jakartaee-tck/pull/251

**Comment by olamy** [comment]
Thanks!

**Comment by scottmarlow** [comment]
Hi,

Thanks for @olamy for mentioning this issue on the Platform TCK mailing list.  Is the concern that the mentioned test requires vendor specific web deployment descriptor files to be included when deploying the test?

With WildFly, we use an equivalent deployment descriptor:
```
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE jboss-web PUBLIC "-//JBoss//DTD Web Application 5.0//EN" "http://www.jboss.org/j2ee/dtd/jboss-web_5_0.dtd">
<jboss-web>
  <security-domain>cts</security-domain>
  <context-root>/servlet_sec_denyUncovered_web</context-root>
  <security-role>
    <role-name>Administrator</role-name>
    <principal-name>j2ee</principal-name>
  </security-role>
  <security-role>
    <role-name>Manager</role-name>
    <principal-name>javajoe</principal-name>
  </security-role>
  <security-role>
    <role-name>Employee</role-name>
    <principal-name>javajoe</principal-name>
    <principal-name>j2ee</principal-name>
  </security-role>
</jboss-web>
```

What changes would you prefer be made to this test?

**Comment by scottmarlow** [comment]
> This issue will occur when running the TCK on any container that doesn't use the Glassfish specific sun-web.xml configuration file. That file is not part of the Servlet specification and should not be required in order to pass the TCK. I observed the issue running the Servlet TCK against Apache Tomcat.

@markt-asf @stuartwdouglas 
While this issue is closed, now is a good time to discuss if you are still concerned about the Glassfish specific sun-web.xml (or vendor specific) deployment descriptors being needed in the test deployment.  

With Arquillian, do you see an existing mechanism that we could use instead of including vendor specific deployment descriptors in the test deployment?

**Comment by arjantijms** [comment]
@scottmarlow the security role assignments to the principals could (perhaps should) be done globally, in the GlassFish specific identity store (which glassfish calls loginmodule/realm). It already defines the required passwords in that realm anyway. I think this separate role mapping is from the time where GlassFish required roles to be mapped, whether this was actually needed or not. JBoss never required this, and neither did the spec. The spec however now does mandate a server can't require this, and GlassFish 5 and 6 indeed don't.

The problem however here is with the context root '/servlet_sec_denyUncovered_web'. The test should not depend on this, but just the default as specified by the spec.

**Comment by arjantijms** [comment]
> With Arquillian, do you see an existing mechanism that we could use instead of including vendor specific deployment descriptors in the test deployment?

Arquillian essentially works in the same way, and would in many cases include a verdor specific deployment descriptor.

Setting the context root in web.xml would be the theoretical solution for a new version of the spec, but this was proposed before (for Servlet 4, if I'm not mistaken) but rejected by the Servlet EG at the time.

**Comment by markt-asf** [comment]
I would always be concerned if a TCK test depended on non-specification, vendor specific behaviour. In this case my understanding is that this dependency has been removed in this test. Assuming that understanding is correct, I have no concerns.

Regarding specifying context root in web,xml we have `default-context-path` which I think is a bad idea but as long as the container can override it (which equates to ignoring it for Tomcat) I can live with it. Further discussion on that topic belongs on servlet-dev.

**Comment by arjantijms** [comment]
> Assuming that understanding is correct, I have no concerns.

Thanks @markt-asf !

**Comment by stuartwdouglas** [comment]
Lots of tests need vendor specific files, generally because they are doing security role mappings. We should not be requiring them for things like this though, where there is both a spec defined way to do it, and there is no real need for it anyway (the test can just use the default path).

**Comment by arjantijms** [comment]
@stuartwdouglas 
> Lots of tests need vendor specific files, generally because they are doing security role mappings

As the security role mappings were always implied, not mandated, I don't think there are tests that explicitly test that role "foo" is mapped to say role "bar".

Since Java EE 8 it's mandated that IFF containers support security role mapping (which not all do), then they must default to 1:1 role mapping. Although maybe we should be more clear about whether this is a platform requirement, a jakarta security requirement, and/or also a specific servlet requirement.

In the past some security requirements, such as as the `*` role were duplicated to 4 places (platform, servlet, ejb and authorization).
