### ISSUE TITLE
 Review and promote Jakarta RESTful Web Services 3.0.0 TCK for JakartaEE 9 release #432 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#457]
1.  Complete userguide/documentation changes for Jakarta RESTful Web Services 2.0.0 TCK.
2.  Review the jakarta-restful-ws-tck-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or restful-ws-3.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
4.  Remove the boolean parameter (RESTFUL_WS_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by spericas** [comment]
@alwin-joseph I reviewed the documentation for the TCK bundle an it LGTM. We can go ahead with the promotion.

**Comment by alwin-joseph** [comment]
Thanks @spericas . I have refreshed the staged bundle now at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip. The same will be promoted to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip soon

**Comment by alwin-joseph** [comment]
@spericas The TCK is now promoted and available at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip.

**Comment by alwin-joseph** [comment]
Hi @spericas - It seems we would have some updates for jaxrs tck with the parameters in keyword.properties to keep jaxb related tests as optional (https://github.com/eclipse-ee4j/jakartaee-tck/pull/511) . Do you think it is ok to refresh the https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip or do you expect a new version of jaxrs tck for this update.

**Comment by scottmarlow** [comment]
My preference is to not promote jakarta-restful-ws-tck-3.0.0.zip again with a different SHA, as we should instead stage a new jakarta-restful-ws-tck-3.0.1.zip and stage that if @spericas approves as an addition step after we stage.

**Comment by spericas** [comment]
I like @scottmarlow suggestion to stage a 3.0.1.

**Comment by scottmarlow** [comment]
@spericas @alwin-joseph fyi, sorry, I guess we can update the promoted https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip, so I will revert the version change that I made. :-)

**Comment by scottmarlow** [comment]
@spericas http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip has been updated to include the support for [xml_binding keyword](https://github.com/eclipse-ee4j/jakartaee-tck/pull/511).

CC @lukasj

**Comment by alwin-joseph** [comment]
> @spericas http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip has been updated to include the support for [xml_binding keyword](https://github.com/eclipse-ee4j/jakartaee-tck/pull/511).
> 

Sorry there is an issue with the current jaxrs tck http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip  (it is fixed in https://github.com/eclipse-ee4j/jakartaee-tck/pull/517/) . Let me restage the jaxrs tck once more and update please.

**Comment by scottmarlow** [comment]
The updated http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip is now available, thanks @alwin-joseph for catching that!

**Comment by alwin-joseph** [comment]
@spericas  FYI, the jaxrs tck at  https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip is outdated. We would update the promoted bundle when the staged bundle ( http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-restful-ws-tck-3.0.0.zip ) is ready.

**Comment by spericas** [comment]
@alwin-joseph Right, we should promote it. I don't believe any other issues have been reported.

**Comment by spericas** [comment]
@alwin-joseph I think we should go ahead and promote it now.

**Comment by scottmarlow** [comment]
@spericas I will take a look at that now.

**Comment by scottmarlow** [comment]
@spericas http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip is promoted and note that the [SHA is still the same 39081f393f495d2363ae66c487f83a171cb52a8038930bd1af7829f5757a9aa7](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0-tckinfo.txt).

**Comment by scottmarlow** [comment]
The `RESTFUL_WS_TCK` parameter is now removed from the https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles job.  I will close this issue now.  If any further changes are needed for http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-restful-ws-tck-3.0.0.zip, please reopen this issue.
