### ISSUE TITLE
JSP TCK Signature tests fail in standalone mode

### ISSUE THREAD

**Issue by markt-asf** [eclipse-ee4j/jakartaee-tck#48]
There appear to be two issues.

1. sig-test.map defines `javax.servlet.jsp=2.3_se6` whereas it should define `javax.servlet.jsp=2.3_se8`
2. `src/com/sun/ts/tests/signaturetest/siganture-repository` does not exist. It should exist and contain `javax.servlet.jsp.sig_2.3_se8`

The first issue I can fix and can provide a PR. The second I could do with a pointer on where to look / how to get started.

**Comment by edbratt** [comment]
Some things you might look at:

1) Have you reviewed the setup instructions in the stand-alone Servlet 
TCK user guide 
<https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/servlet>? 
If you haven't already, have a look at section 4.2 Configuring Your 
Environment to Repackage and Run the TCK Against the Vendor 
Implementation (it's available in adoc format -- you might want to build 
the HTML for easier reading. See the readme at the link above).

2) have you checked your results with the test runs at 
jenkins.eclipse.org? You might be able to glean something about the 
setup and operation, from the successful test results (e.g. build 81).

  * The report summary
    <https://jenkins.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run/lastSuccessfulBuild/junit-reports-with-handlebars/test-summary/8d780f65-fa1e-48a0-b692-e48b05456632.html>
  * Last successful build
    <https://jenkins.eclipse.org/jakartaee-tck/job/standalonetck-nightly-build-run/lastSuccessfulBuild/>
  * Console output
    <https://jenkins.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/standalonetck-nightly-build-run/runs/81/log/?start=0>

I agree that the console log is pretty opaque. Would be nice if someone 
were interested in improving the Jenkins output.

3) If you haven't already, have a look at the TCK wiki 
<https://github.com/eclipse-ee4j/jakartaee-tck/wiki>. There maybe some 
details there, which will be helpful

4) Finally, if you haven't already, you might try a test run against the 
Jenkins job that is designed to assist Eclipse GlassFish developers and 
can run the suites, according to whatever set of tests you want it to 
run (the caveat is, it wants to run Eclipse GlassFish -- but you might 
be able to get more details about how these tests are setup and run).

Read the description, here 
<https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Project-Specific-JakartaEE-TCK-Run>. 
In general, you'd create a pipeline at jenkins.eclipse.org for Servlet 
to run the TCK -- you'd need a servlet engine in Eclipse GlassFish (to 
start with anyway), configure the test to run -- standalone Servlet TCK 
suite only -- tweak the settings until you can see enough details to see 
how the test runs -- then use that data to determine what you might want 
to change in your PR. Perhaps a bit convoluted, but the advantage being 
you'd leave (if you desired) a stand-alone TCK test for the Servlet project.

I hope something in here is helpful.

-- Ed

**Comment by markt-asf** [comment]
1) This bug is for the JSP spec, not the Servlet spec. I have read the relevant docs for the JSP TCK.

2) I get continual 504s from that Jenkins instance at the moment. I'll come back to it as I am curious how the stand-alone TCKs are being run without hitting this bug.

3) I have read it. It doesn't help.

4) Assuming s/Servlet/JSP/ I don't think that will help as I suspect whatever is allowing 2 to be successful will apply here.

I checked back with the JSP 2.2 TCK that the ASF has access to and what I see there is consistent with my view that there is a packaging problem with the Jakarta EE JSP 2.3 TCK nightly build although it isn't quite as I described above.

1. The current `bin/sig-test.map` is correct but I'd also expect to see `bin/sig-test_se6.map`, `bin/sig-test_se7.map` and `bin/sig-test_se8.map`.

2. `src/com/sun/ts/tests/signaturetest/siganture-repository` should be present (it is missing) and I'd expect it to contain `jaxax.el.sig_2.3_se6`, javax.servlet.jsp.sig_2.3_se6`, `jaxax.el.sig_2.3_se7`, javax.servlet.jsp.sig_2.3_se7`, `jaxax.el.sig_2.3_se8` and javax.servlet.jsp.sig_2.3_se8`

Because none of the history has been imported for any of the Jakarta EE projects I can't look into what might have changed to cause this problem.

**Comment by bhatpmk** [comment]
We will fix the issue as early as possible.

**Comment by alwin-joseph** [comment]
>     1. The current `bin/sig-test.map` is correct but I'd also expect to see `bin/sig-test_se6.map`, `bin/sig-test_se7.map` and `bin/sig-test_se8.map`.
> 
>     2. `src/com/sun/ts/tests/signaturetest/siganture-repository` should be present (it is missing) and I'd expect it to contain `jaxax.el.sig_2.3_se6`, javax.servlet.jsp.sig_2.3_se6`, `jaxax.el.sig_2.3_se7`, javax.servlet.jsp.sig_2.3_se7`, `jaxax.el.sig_2.3_se8` and javax.servlet.jsp.sig_2.3_se8`
> 

src/com/sun/ts/tests/signaturetest/signature-repository directory is present(not sure if the typo "siganture-repository" was causing the trouble) and it contains the latest signature files. We had removed all the unused sig files and map files(se6 & se7) from this directory before donation.

**Comment by markt-asf** [comment]
Just to note, there is a typo in my original report. The name of the missing directory is `src/com/sun/ts/tests/signaturetest/signature-repository`

**Comment by alwin-joseph** [comment]
I have made the change for this issue. Will keep a watch if it reoccurs.

**Comment by markt-asf** [comment]
I've confirmed that the signature test in the standalone TCK now runs correctly under Java 8. Could the fix be back-ported to the EE4J8 branch?

I'll note that the JSP 2.3 TCK requires Java 8 to run although the minimum Java version for that spec is Java 6. Having this running on Java 6 is a nice to have and I suspect there are many more important issues to address. Having this running on Java 6 isn't essential. I won't open an issue for it.

**Comment by alwin-joseph** [comment]
The fix is made to both the branches - EE4J & master.

master - https://github.com/eclipse-ee4j/jakartaee-tck/commit/303da3fd93c9c2912f0d5eaaacba84a2d1490136

EE4J_8 - https://github.com/eclipse-ee4j/jakartaee-tck/commit/423f326a5ea13ead63b4e783c7b858d73f06ff74

**Comment by markt-asf** [comment]
Thanks. I missed that. Just tested the latest EE4J8 nightly JSP TCK build and all looks good. Tx.
