### ISSUE TITLE
Make some tests optional as mentioned in EE 9 release plan

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#491]
As per https://eclipse-ee4j.github.io/jakartaee-platform/jakartaee9/JakartaEE9ReleasePlan (see `Specifications Added to Jakarta EE 9`), the following tests should be considered optional (impacting Platform + JAXWS TCKs):
```
Jakarta XML Web Services (Optional)
Jakarta Web Services Metadata (Optional jakarta.xml.ws)
```

In the Platform TCK we have https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/keyword.properties that could be used to control which tests are optional.

I think we should also consider what it could mean to do the same for the following which are also mentioned in the release plan (impacting Platform + SAAJ TCK):
```
Jakarta SOAP with Attachments (Optional)
Jakarta XML Binding (Optional jakarta.xml.bind)
```

@alwin-joseph @RohitKumarJain @gurunrao 
Any suggestions for how we could best achieve this with keyword.properties changes?  Perhaps via new keywords or reusing existing properties (e.g. webservices)?  

CC @kwsutter @edbratt

**Comment by scottmarlow** [comment]
For reference on use of keywords, see section [7.5.2 Using Keywords to Create Groups and Subsets of Tests](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/jakartaee/src/main/jbake/content/using.adoc)

**Comment by scottmarlow** [comment]
We only have to worry about the platform TCK, as the standalone TCKs can simply be not run if they are for optional technologies.  We will of course still use the keywords setting as well but IMO, if we need to update any test to be marked optional, there is no need to release a new related standalone TCK.

To ensure that the `Jakarta XML Web Services + Jakarta Web Services Metadata` tests are optional, if each test is marked as `webservices` ([see example here](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/keyword.properties#L233)), then these optional tests could be ignored via `ant -Dkeywords="!webservices"  runclient`.  Agreed?  

For ensuring that `Jakarta SOAP with Attachments (SAAJ)` test are optional, we already have keyword `saaj` to use but they not really needed since those tests are only run in the standalone Jakarta SOAP with Attachments (SAAJ) TCK.

For ensuring that `Jakarta XML Binding (JAXB)` tests are optional, I think we have work to do, as I think we need to add a new keyword ('jaxb' or 'xmlbinding'?) to allow the following tests that reference Jakarta XML Binding be optional:
```
ag --ignore .git jakarta.xml.bind -l
signaturetest/signature-repository/jakarta.ws.rs.sig_3.0_se8
signaturetest/signature-repository/jakarta.ws.rs.sig_3.0_se11
signaturetest/signature-repository/jakarta.xml.ws.sig_3.0_se11
signaturetest/signature-repository/jakarta.xml.ws.sig_3.0_se8
webservices12/specialcases/services/w2j/doclit/provider/HelloImpl.java
webservices12/ejb/annotations/WSEjbWebServiceProviderTest/HelloBean.java
jaxrs/jaxrs21/ee/sse/sseeventsource/MediaTypeResource.java
jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java
jaxrs/jaxrs21/ee/sse/sseeventsink/MBWCheckResource.java
jaxrs/api/rs/core/linkjaxbadapter/Model.java
jaxrs/api/rs/core/linkjaxbadapter/JaxbAdapterEx.java
jaxrs/api/rs/core/linkjaxbadapter/JAXRSClient.java
jaxrs/api/rs/core/linkjaxbadapter/JaxbLinkEx.java
jaxrs/spec/filter/interceptor/JAXRSClient.java
jaxrs/spec/filter/interceptor/Resource.java
jaxrs/spec/provider/overridestandard/TckJaxbProvider.java
jaxrs/spec/provider/overridestandard/Resource.java
jaxrs/spec/provider/standardhaspriority/JAXRSClient.java
jaxrs/spec/provider/standardhaspriority/TckJaxbProvider.java
jaxrs/spec/provider/standardhaspriority/ProviderWalker.java
jaxrs/spec/provider/standardnotnull/Resource.java
jaxrs/spec/provider/standardnotnull/JAXRSClient.java
jaxrs/spec/provider/standard/JAXRSClient.java
jaxrs/spec/provider/jaxbcontext/JAXRSClient.java
jaxrs/spec/provider/jaxbcontext/SomeJaxbContext.java
jaxrs/spec/provider/jaxbcontext/TckJaxbProvider.java
jaxrs/spec/provider/jaxbcontext/JaxbContextProvider.java
jaxrs/spec/provider/jaxbcontext/SomeMarshaller.java
jaxrs/spec/provider/jaxbcontext/SomeUnmarshaller.java
jaxrs/spec/provider/standard/Resource.java
jaxrs/spec/provider/jaxbcontext/Resource.java
jaxrs/spec/provider/standardhaspriority/Resource.java
jaxrs/spec/client/typedentities/JAXRSClient.java
jaxrs/common/impl/JaxbKeyValueBean.java
jaxws/wsa/w2j/document/literal/providertest/ProviderTestImpl.java
jaxws/wsa/w2j/document/literal/providertest/Client.java
jaxws/wsa/j2w/document/literal/epr/Client.java
jaxws/wsa/j2w/document/literal/typesubstitution/CarDealerImpl.java
jaxws/wsa/j2w/document/literal/typesubstitution/Car.java
jaxws/wsa/common/MemberSubmissionEndpointReference.java
jaxws/sharedwebservices/dlhelloproviderservice/HelloImpl.java
jaxws/sharedwebservices/xmlbinddlhelloproviderservice/HelloImpl.java
jaxws/sharedwebservices/doclithelloservice/ServerLogicalHandler.java
jaxws/api/jakarta_xml_ws/Dispatch/Client.java
jaxws/api/jakarta_xml_ws/Provider/Client.java
jaxws/api/jakarta_xml_ws/Response/Client.java
jaxws/api/jakarta_xml_ws/Service/Client.java
jaxws/api/jakarta_xml_ws/AsyncHandler/Client.java
jaxws/api/jakarta_xml_ws_http/HTTPBinding/Client.java
jaxws/ee/w2j/document/literal/handlerchaintest/Client.java
jaxws/ee/w2j/document/literal/handlerchaintest/HandlerChainTestImpl.java
jaxws/ee/w2j/document/literal/handlerchaintest/LogicalHandler.java
jaxws/mapping/j2wmapping/rpc/literal/withannotations/MyOtherFaultBean.java
jaxws/mapping/j2wmapping/document/literal/wrapped/MyOtherFaultBean.java
jaxws/mapping/j2wmapping/document/literal/wrapped/MyFault.java
jaxws/mapping/j2wmapping/document/literal/wrapped/JAXBAnnotationsImpl.java
jaxws/mapping/j2wmapping/document/literal/wrapped/Client.java
jaxws/sharedclients/doclithelloclient/ClientLogicalHandler.java
jaxws/common/SOAPHandlerBase2.java
jaxws/common/AnnotationUtils.java
jaxws/common/SOAPHandlerBase.java
```
The work being to update https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/keyword.properties to add whichever keyword we decide on for the above tests.  

Question to be answered is whether we should stage/promote new standalone TCKs with the updated keyword.properties with the new keyword ('jaxb' or 'xmlbinding')?  Perhaps that could justify a new xml-ws-tck-3.0.1.zip + restful-ws-tck-3.0.1.zip release, thoughts?  Perhaps we could decide that after this issue is resolved.

**Comment by scottmarlow** [comment]
Another aspect to consider is that the Full Platform/Web Profile specifications define which technologies are included respectively in each profile.  So, the EE 9 release plan only specifies which technologies are optional (e.g. Jakarta Web Services Metadata (JWS) is not part of the Web Profile spec).

This needs to be taken into account in the plan to update keyword.properties

**Comment by alwin-joseph** [comment]
Except for jaxb, can you confirm if below in the keyword.properties are the same that you were intending to:

com/sun/ts/tests/jws = jws javaee_optional javaee_web_profile_optional
com/sun/ts/tests/jaxws = jaxws jaxws_web_profile javaee_optional  javaee_web_profile_optional
com/sun/ts/tests/saaj = saaj saaj_web_profile javaee_optional javaee_web_profile_optional

**Comment by alwin-joseph** [comment]
I think we would also need to edit install/jakartaee/other/vehicle.properties to have jws, jaxws, saaj

**Comment by gurunrao** [comment]
If all of testsuite is optional then we can stop passing testsuite name in "-Dtest.areas" parameter. Also we can add "javaee_optional javaee_web_profile_optional" in keyword.properties for the testsuite.

If there is combination of optional(jaxb) and required tech(jaxrs), we can introduce a new keyword as suggested by scott.
`com/sun/ts/tests/jaxrs/spec/provider/jaxbcontext= javaee_optional xml_binding javaee_web_profile_optional`

**Comment by alwin-joseph** [comment]
> 
> For ensuring that `Jakarta XML Binding (JAXB)` tests are optional, I think we have work to do, as I think we need to add a new keyword ('jaxb' or 'xmlbinding'?) to allow the following tests that reference Jakarta XML Binding be optional:
> 
> 
> If there is combination of optional(jaxb) and required tech(jaxrs), we can introduce a new keyword as suggested by scott.
> `com/sun/ts/tests/jaxrs/spec/provider/jaxbcontext= javaee_optional xml_binding javaee_web_profile_optional`

I am just thinking are we actually testing jaxb in any of the suites that uses jakarta.xml.bind or just using it for testing other suites. Since we do have a separate jaxb-tck should we try to implement optional parameter for jaxb in platform tck also.

**Comment by gurunrao** [comment]
We are not testing jaxb functionality, but we have dependency on jaxb in tests.Since jaxb will not be part of JDK and made optional in Jakarta EE 9(vendor has liberty on opting out of bundling JAXB jars). The tests which have dependency on jaxb will fail, if not bundled by vendor.

**Comment by alwin-joseph** [comment]
> We are not testing jaxb functionality, but we have dependency on jaxb in tests.Since jaxb will not be part of JDK and made optional in Jakarta EE 9(vendor has liberty on opting out of bundling JAXB jars). The tests which have dependency on jaxb will fail, if not bundled by vendor.

Right, was about to correct myself. I had same question when pruning techs , we removed those tests which were depended on those.

It would be easier to add folder jaxrs/spec/provider/jaxbcontext as javaee_optional but others like below will need to be looked into individually on how to make them optional.
webservices12/specialcases/services/w2j/doclit/provider/HelloImpl.java
webservices12/ejb/annotations/WSEjbWebServiceProviderTest/HelloBean.java
jaxrs/jaxrs21/ee/sse/sseeventsource/MediaTypeResource.java
jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java
jaxrs/jaxrs21/ee/sse/sseeventsink/MBWCheckResource.java

**Comment by gurunrao** [comment]
When optional tech effects test-case, we need to separate out those with optional tech and create a new structure for them.
For Example in case of "jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java" on test "jaxbElementTest" has dependency on optinal tech. We can separate out jaxbElementTest test and mark it optional.

we have achieved similar in JASPIC test cases for web-profile (where SOAP is not supported) - https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaspic/tssv/config/SOAPTSServerAuthConfig.java

**Comment by alwin-joseph** [comment]
> Except for jaxb, can you confirm if below in the keyword.properties are the same that you were intending to:
> 
> com/sun/ts/tests/jws = jws javaee_optional javaee_web_profile_optional
> com/sun/ts/tests/jaxws = jaxws jaxws_web_profile javaee_optional javaee_web_profile_optional
> com/sun/ts/tests/saaj = saaj saaj_web_profile javaee_optional javaee_web_profile_optional

I think I got these wrong. deleting this.

**Comment by gurunrao** [comment]
@scottmarlow - lucas had mentioned "in order to update jaxb, metro is required (and vice-versa); in order to update eclipselink, jaxb and metro are required."
Given above dependency, if JAXB is "optional", should metro and eclipselink tests, also be marked "xml_binding"?

**Comment by alwin-joseph** [comment]
1. Jakarta XML Web Services + Jakarta Web Services Metadata (Specifications Added to Jakarta EE 9): both are tested using jaxws standalone TCK and we won't need to make changes in platform tck unless some other required tech suite is depended on these.
2. Jakarta SOAP with Attachments (Specifications Added to Jakarta EE 9) : similar as above , soap tck will run the tests and not platform tck.
3. Jakarta Enterprise Web Services (Specifications marked Optional in Jakarta EE 9) : The webservices12/13 suites are testing this and they need to be newly marked as optional.

Do you agree.

**Comment by scottmarlow** [comment]
> > For ensuring that `Jakarta XML Binding (JAXB)` tests are optional, I think we have work to do, as I think we need to add a new keyword ('jaxb' or 'xmlbinding'?) to allow the following tests that reference Jakarta XML Binding be optional:
> > If there is combination of optional(jaxb) and required tech(jaxrs), we can introduce a new keyword as suggested by scott.
> > `com/sun/ts/tests/jaxrs/spec/provider/jaxbcontext= javaee_optional xml_binding javaee_web_profile_optional`
> 
> I am just thinking are we actually testing jaxb in any of the suites that uses jakarta.xml.bind or just using it for testing other suites. Since we do have a separate jaxb-tck should we try to implement optional parameter for jaxb in platform tck also.

I'm not sure about using `xml_binding` in standalone TCKs.  Could that work for jaxws + jaxrs tcks?

From the above list of Platform TCK tests that use jaxb, I think the standalone TCKs would be jaxws + jaxrs, both of which seem to include keyword.properties file but only jaxws userguide seems to document use of keywords to limit tests run, however the jaxws tests are commented out in keyword.properties, so we would need to at least update the jaxws tests in keyword.properties file.  In case it is not obvious, I am learning the internals still on keyword.properties (I have used it in the past only for Full Platform TCK).

I agree that we can implement optional parameter for jaxb tests in platform tck also.  I suggest that we create a pull request and setup testing to verify the tests are optional (e.g. by checking that the jaxb using tests don't run by default and that jaxb tests do run when `xml_binding` keyword is specified).

**Comment by scottmarlow** [comment]
> > We are not testing jaxb functionality, but we have dependency on jaxb in tests.Since jaxb will not be part of JDK and made optional in Jakarta EE 9(vendor has liberty on opting out of bundling JAXB jars). The tests which have dependency on jaxb will fail, if not bundled by vendor.
> 
> Right, was about to correct myself. I had same question when pruning techs , we removed those tests which were depended on those.
> 
> It would be easier to add folder jaxrs/spec/provider/jaxbcontext as javaee_optional 

Hmm, so if this was the only jaxrs test using jaxb, I agree since the folder name includes jaxb which is javaee_optional, however, as you point out the ones below couldn't really use javaee_optional as they are non-jaxb tests that happen to use jaxb because it was required to be present before Jakarta EE 9.  

For consistency, if anyone knows of any existing `keywork.properties' patterns used that do mix use of javaee_optional and a technology specific name (e.g. similar to `xml_binding`) for cases like this, please speak up.  Otherwise, I think the best consistency is to use `xml_binding` for `jaxrs/spec/provider/jaxbcontext` + below tests.  If you don't want to run `xml_binding` tests, include "!xml_binding" in keywords.  If you want to run `xml_binding` tests, include `xml_binding` in keywords.  

> but others like below will need to be looked into individually on how to make them optional.
> webservices12/specialcases/services/w2j/doclit/provider/HelloImpl.java

Currently we have:
`com/sun/ts/tests/webservices12/specialcases/services/w2j/doclit/provider = webservices javaee_optional jaxws_web_profile javaee_web_profile_optional`

JAXB is used in this test, so is it enough to add `xml_binding`?
`com/sun/ts/tests/webservices12/specialcases/services/w2j/doclit/provider = webservices javaee_optional jaxws_web_profile javaee_web_profile_optional xml_binding`

I didn't look at the four below entries yet but how about we follow the same pattern of adding keywords for each technology that is now newly optional for Jakarta EE 9?

> webservices12/ejb/annotations/WSEjbWebServiceProviderTest/HelloBean.java
> jaxrs/jaxrs21/ee/sse/sseeventsource/MediaTypeResource.java
> jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java
> jaxrs/jaxrs21/ee/sse/sseeventsink/MBWCheckResource.java

Some possible (Full Platform) settings for running tests that use JAXB:
`ant -Dkeywords=(javaee&xml_binding) runclient`
Some possible settings that disable tests that use JAXB:
`ant -Dkeywords=(javaee&!xml_binding) runclient`

**Comment by scottmarlow** [comment]
> When optional tech effects test-case, we need to separate out those with optional tech and create a new structure for them.
> For Example in case of "jaxrs/jaxrs21/ee/sse/sseeventsource/JAXRSClient.java" one test "jaxbElementTest" has dependency on optinal tech. We can separate out jaxbElementTest test and mark it optional.
> 
> we have achieved similar in JASPIC test cases for web-profile (where SOAP is not supported) - https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaspic/tssv/config/SOAPTSServerAuthConfig.java

https://github.com/eclipse-ee4j/jakartaee-tck/pull/511 contains some possible changes mentioned in previous comment.  I'm not against separating out the JAXB dependent test, but I didn't do that in the draft request.

**Comment by scottmarlow** [comment]
> @scottmarlow - lucas had mentioned "in order to update jaxb, metro is required (and vice-versa); in order to update eclipselink, jaxb and metro are required."
> Given above dependency, if JAXB is "optional", should metro and eclipselink tests, also be marked "xml_binding"?

@gurunrao [Metro](https://projects.eclipse.org/projects/ee4j.metro) and EclipseLink are implementations that have their own tests.  I'm not understanding what exactly in those projects (or associated with those projects) would be marked "xml_binding".  Am I missing something?

**Comment by scottmarlow** [comment]
>     1. Jakarta XML Web Services + Jakarta Web Services Metadata (Specifications Added to Jakarta EE 9): both are tested using jaxws standalone TCK and we won't need to make changes in platform tck unless some other required tech suite is depended on these.

Interesting point, thanks for raising it.  If we were to make the jaxws tests that use jakarta.xml.bind optional in the standalone jaxws TCK, that would allow Jakarta EE 9 implementations that don't implement JAXB to run the jaxws TCK.  So there is some value in that the jaxws TCK could be useful for them.  

> 
>     2. Jakarta SOAP with Attachments (Specifications Added to Jakarta EE 9) : similar as above , soap tck will run the tests and not platform tck.

I don't see any jakarta.xml.ws or jakarta.xml.bind references in the soap tck.  Unless I am missing something, I agree that the soap/saaj tck shouldn't need keyword.properties changes.

> 
>     3. Jakarta Enterprise Web Services (Specifications marked Optional in Jakarta EE 9) : The webservices12/13 suites are testing this and they need to be newly marked as optional.

:+1: I agree, good point!

> 
> 
> Do you agree.

See above comments.  

I think that the https://github.com/eclipse-ee4j/jakartaee-tck/pull/511 gives us some ideas.  Either I made good changes or I'm completely wrong in how I made them.  :-)

**Comment by scottmarlow** [comment]
One additional question for @alwin-joseph + @gurunrao + @RohitKumarJain that I have is how do we update `signaturetest/signature-repository/jakarta.ws.rs.sig_3.0_se8` + `signaturetest/signature-repository/jakarta.xml.ws.sig_3.0_se8` to treat jakarta.xml.bind classes as optional?

**Comment by alwin-joseph** [comment]
> One additional question for @alwin-joseph + @gurunrao + @RohitKumarJain that I have is how do we update `signaturetest/signature-repository/jakarta.ws.rs.sig_3.0_se8` + `signaturetest/signature-repository/jakarta.xml.ws.sig_3.0_se8` to treat jakarta.xml.bind classes as optional?
> 

This looks like a tricky situation here. The jaxrs(non-optional tech) classes are inheriting jaxb(optional) classes.
eg: Nested class Link.JaxbAdapter  in jakarta.ws.rs.core.Link is extending jakarta.xml.bind.annotation.adapters.XmlAdapter in jaxb. I will check if the sig tests execution already has something to skip optional techs.

> Worse case if we cannot make signature the JAXB signature checking optional, we could documentation that JAXB signature failures due to missing API classes are acceptable in TCK results.

**Comment by gurunrao** [comment]
Following property might be of help - https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jakartaee/bin/ts.jte#L1403

**Comment by scottmarlow** [comment]
> 
> This looks like a tricky situation here. The jaxrs(non-optional tech) classes are inheriting jaxb(optional) classes.
> eg: Nested class Link.JaxbAdapter in jakarta.ws.rs.core.Link is extending jakarta.xml.bind.annotation.adapters.XmlAdapter in jaxb. 

I agree https://github.com/eclipse-ee4j/jaxrs-api/blob/master/jaxrs-api/src/main/java/jakarta/ws/rs/core/Link.java#L28 is a concern, not just for the Jakarta EE 9 Platform TCK.  

I'll ask for guidance on what needs to change on the platform mailing list.

**Comment by scottmarlow** [comment]
I'm thinking we should try some test runs of the standalone JAXRS TCK with the JAXB classes not included on the test classpath and `ant -Dkeywords=(!xml_binding) runclient` specified to run the tests that don't reference the Link class directly.

I'll make further changes in keyword.properties next.

I also asked on https://github.com/eclipse-ee4j/jaxrs-api/issues/906 about the classes that indirectly reference Link and what the goal is for such classes.  Perhaps the TCK testing will show that there is no concern about the other JAX-RS classes that reference Link.

**Comment by scottmarlow** [comment]
I pushed keyword.properties updates for jaxrs, note that jaxrs/common/impl didn't need an entry as it is only used from jaxrs21/ee/sse/sseeventsource which is already in keyword.properties.

What is the easiest way to run the build/run standalone jaxrs TCK and run with jaxb/Jakarta XML Binding classes not on the classpath?

It would be helpful if we could run once with:

1.  `ant -Dkeywords=(jaxrs&!xml_binding) runclient` (will likely pass)
1.  `ant -Dkeywords=(jaxrs) runclient` (will likely have some CNFE on jakarta.xml.bind)

**Comment by scottmarlow** [comment]
I'll try following https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Instructions-for-Building-&-Running-Jakarta-EE-Standalone-TCKs :-)

**Comment by scottmarlow** [comment]
The above `ClassNotFoundException: jakarta.activation` + `ClassNotFoundException: com.sun.ts.lib.deliverable.tck.TCKDeliverable` errors must of been environmental due to building on my local machine, as I don't see the same failure in https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/pr%252F511/runs/9/nodes/29/steps/32/log/?start=0

**Comment by alwin-joseph** [comment]
> The above `ClassNotFoundException: jakarta.activation` + `ClassNotFoundException: com.sun.ts.lib.deliverable.tck.TCKDeliverable` errors must of been environmental due to building on my local machine, as I don't see the same failure in https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/pr%252F511/runs/9/nodes/29/steps/32/log/?start=0

https://github.com/eclipse-ee4j/jakartaee-tck/pull/517 should fix this. It seems the "sh build_Standalonetck.sh jaxrs" has this issue but was not detected when multiple tcks were built at a time , eg "sh build_Standalonetck.sh connector jaxrs".

**Comment by scottmarlow** [comment]
> > The above `ClassNotFoundException: jakarta.activation` + `ClassNotFoundException: com.sun.ts.lib.deliverable.tck.TCKDeliverable` errors must of been environmental due to building on my local machine, as I don't see the same failure in https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/pr%252F511/runs/9/nodes/29/steps/32/log/?start=0
> 
> #517 should fix this. It seems the "sh build_Standalonetck.sh jaxrs" has this issue but was not detected when multiple tcks were built at a time , eg "sh build_Standalonetck.sh connector jaxrs".

Thanks for merging that!  

Are there any other changed needed for this issue?

**Comment by alwin-joseph** [comment]
> > > The above `ClassNotFoundException: jakarta.activation` + `ClassNotFoundException: com.sun.ts.lib.deliverable.tck.TCKDeliverable` errors must of been environmental due to building on my local machine, as I don't see the same failure in https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck-alw/branches/pr%252F511/runs/9/nodes/29/steps/32/log/?start=0
> > 
> > 
> > #517 should fix this. It seems the "sh build_Standalonetck.sh jaxrs" has this issue but was not detected when multiple tcks were built at a time , eg "sh build_Standalonetck.sh connector jaxrs".
> 
> Thanks for merging that!
> 
> Are there any other changed needed for this issue?

No. https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/75/ builds and runs jaxrs tck after the fix.

**Comment by alwin-joseph** [comment]
1. Jakarta Enterprise Web Services, JSR 109 which is newly marked as optional in JakartaEE9 is tested using webservices12/13 tests in platform TCK. There is no api jar associated with this spec. https://github.com/eclipse-ee4j/jakartaee-tck/pull/519 is to only mark these tests as optional.
spec PR : https://github.com/jakartaee/specifications/pull/228

2. Jakarta XML Web Services (Optional) + Jakarta Web Services Metadata (Optional) : They are tested using jaxws tck(jakarta-xml-ws-tck-3.0.0.zip). 
api jars :  jakarta.xml.ws-api.jar &  jakarta.jws-api.jar resp. 
spec PRs : https://github.com/jakartaee/specifications/pull/243 & https://github.com/jakartaee/specifications/pull/229 resp.
We would need to check the usage of jakarta.xml.ws-api.jar & jakarta.jws-api jar in the tests and mark those tests as optional too.


Questions :

1. Lukas mentioned webservices12 covers pre-EE8 versions and it could be removed. Is that right?

2. Are the below part of JakartaEE 9 Webprofile ? 
-Jakarta Enterprise Web Services , 
-Jakarta XML binding , 
-Jakarta XML Web Services + Jakarta Web Services Metadata , 
-Jakarta SOAP with Attachments 

https://jakarta.ee/specifications/platform/9/platform-spec-9-SNAPSHOT.html#a2161 suggests they are all part of "Web". https://jakarta.ee/specifications/webprofile/9/webprofile-spec-9-SNAPSHOT.html#web-profile-definition does not include any of them. 


@lukasj @scottmarlow @gurunrao

**Comment by lukasj** [comment]
wrt 2 - I believe the agreement is that these specs are not part of web profile

@smillidge

**Comment by smillidge** [comment]
It's more of a platform project discussion but that is my understanding for Web Services but I'm not sure for XML Binding.

**Comment by smillidge** [comment]
I think we need a definitive statement from the platform project.

**Comment by scottmarlow** [comment]
Jakarta XML Binding is not in EE 9 Web Profile specification (I checked recently and saw that its only in EE 9 Full Platform).

**Comment by scottmarlow** [comment]
> Questions :
> 
>     1. Lukas mentioned webservices12 covers pre-EE8 versions and it could be removed. Is that right?

If you want to consider removing webservices12 tests, we would need to email the webservices team for feedback on that.  IMO, we should keep them unless they are creating a problem that we cannot solve quickly for EE 9.

**Comment by alwin-joseph** [comment]
>     1. Jakarta Enterprise Web Services, JSR 109 which is newly marked as optional in JakartaEE9 is tested using webservices12/13 tests in platform TCK. There is no api jar associated with this spec. #519 is to mark these tests as optional.
>        spec PR : [jakartaee/specifications#228](https://github.com/jakartaee/specifications/pull/228)

^ was done using 
> 
>     2. Jakarta XML Web Services (Optional) + Jakarta Web Services Metadata (Optional) : They are tested using jaxws tck(jakarta-xml-ws-tck-3.0.0.zip).
>        api jars :  jakarta.xml.ws-api.jar &  jakarta.jws-api.jar resp.
>        spec PRs : [jakartaee/specifications#243](https://github.com/jakartaee/specifications/pull/243) & [jakartaee/specifications#229](https://github.com/jakartaee/specifications/pull/229) resp.
>        We would need to check the usage of jakarta.xml.ws-api.jar & jakarta.jws-api jar in the tests and mark those tests as optional too.
> 

I believe this is pending. We need to separate and/or make tests using jakarta.xml.ws-api.jar & jakarta.jws-api.jar optional.

> 
> Questions :
> 
>     1. Lukas mentioned webservices12 covers pre-EE8 versions and it could be removed. Is that right?
> 
>     2. Are the below part of JakartaEE 9 Webprofile ?
>        -Jakarta Enterprise Web Services ,
>        -Jakarta XML binding ,
>        -Jakarta XML Web Services + Jakarta Web Services Metadata ,
>        -Jakarta SOAP with Attachments
> 
> 
> https://jakarta.ee/specifications/platform/9/platform-spec-9-SNAPSHOT.html#a2161 suggests they are all part of "Web". https://jakarta.ee/specifications/webprofile/9/webprofile-spec-9-SNAPSHOT.html#web-profile-definition does not include any of them.
> 

> > It's more of a platform project discussion but that is my understanding for Web Services but I'm not sure for XML Binding.
> 
> Jakarta XML Binding is not in EE 9 Web Profile specification (I checked recently and saw that XML Binding is only in EE 9 Full Platform).

Ok, so none of them are part of the web profile, hence will review the keyword.properties to not have javaee_web_profile or javaee_web_profile_optional for tests in these.
