### ISSUE TITLE
Migrate current Wiki articles to the Github Pages branch

### ISSUE THREAD

**Issue by cesarhernandezgt** [eclipse-ee4j/jakartaee-tck#495]
- Migration from current Wiki articles https://github.com/eclipse-ee4j/jakartaee-tck/wiki into https://github.com/eclipse-ee4j/jakartaee-tck/tree/gh-pages

-After the migration replaces the Wiki content with redirection to the Github pages branch.

**Comment by scottmarlow** [comment]
Now that https://github.com/eclipse-ee4j/jakartaee-tck/pull/496 is merged how do we activate the .github.io page?

**Comment by cesarhernandezgt** [comment]
> Now that #496 is merged how do we activate the .github.io page?

I see the GitHub page is already alive:
https://edbratt.github.io/jakartaee-tck/

By the way, I opened a second PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/498 to fix the reference to the Wiki.

**Comment by scottmarlow** [comment]
closed as I think the pages were copied.  We have not yet see much activity on pages but perhaps that will change after EE 9 goes final.
