### ISSUE TITLE
Make RMIIOP tests configurable to be run or always disabled

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#508]
The [rmiiiop](https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/rmiiiop) tests should be configurable to be run (e.g. via [keyword.properties](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/keyword.properties#L174)) or always disabled.

Note that the keyword.properties already does allow disabling of the rmiiiop tests, so I think they could be skipped via something like `-Dkeywords="!rmiiiop"`

**Comment by gurunrao** [comment]
@scottmarlow  
I will proceed with implementation and testing of following:
"rmiiop" and "corba" keywords will be added to mark tests in keyword.properties
"rmiiop" keyword is used for marking tests with dependency on "javax.rmi" packages.
"corba" keyword is used for marking tests with dependency on "org.omg.CORBA" packages.

For any platform run which has to skip tests with RMI/IIOP/CORBA tech, need to pass keywords "!rmiiop&!corba"

**Comment by alwin-joseph** [comment]
FYI, the current full profile platform tck run (https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/docker/run_jakartaeetck.sh) does not add any Keywords while running tests. I believe it is possible to edit "KEYWORDS" to test any newly added parameters.   eg: https://github.com/eclipse-ee4j/jakartaee-tck/blob/102c6a82161a0e037267ac18a658a6eb863e0e55/docker/run_jakartaeetck.sh#L285

**Comment by gurunrao** [comment]
USER_KEYWORDS passed from jobs are always added to KEYWORDS while running tests.
For convenience of not having to pass "!rmiiop&!corba" as parameters to job, we can edit script run_jakartaeetck.sh

**Comment by alwin-joseph** [comment]
> For convenience of not having to pass "!rmiiop&!corba" as parameters to job, we can edit script run_jakartaeetck.sh

Can you specify how should the run_jakartaeetck.sh be modified if not having to pass "!rmiiop&!corba" as parameter. Did you mean to skip these tests in the current platform run?

All the rmiiop&corba tests will be also marked as javaee_optional( if applicable javaee_web_profile_optional also) correct?

**Comment by gurunrao** [comment]
rmiiiop, corba are optional techs, they need to be marked as optional tech also (javaee_optional.. etc)
more implementation details can be covered as part of PR.

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/521 has been completed, to address the issue.
