### ISSUE TITLE
Update Platform TCK user guide

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#527]
Opening this issue to go with the conversation on https://www.eclipse.org/lists/jakartaee-tck-dev/msg00995.html about updating the Platform TCK user guide doc.

**Comment by scottmarlow** [comment]
- [ ] remove the jakartaee-tck/user_guides/jakartaee/src/main/jbake/content/csiv2logs.adoc as we no longer have interoperability tests.  
- [ ] Remove the client2ejb.png + ejb2ejb.png + web2ejb.png image.
- [ ] Mention that we do not need the ior-security-config references in the deployment descriptors in EE 9.  
- [ ] Confirm that Platform specification and the TCK user guide are both updated/consistent with regard to other items checked off/updated here.

1. [Quoting note/action item from Ed Bratt](https://www.eclipse.org/lists/jakartaee-tck-dev/msg00997.html):
`Presumably, there would be some kind of references to these in the Platform Spec. as well. They may have been removed, but we should try to keep a check-list of issues like this so that we can confirm that both the written specification and the TCK User Guide have been updated and are consistent.`

As a general note, please do update this check list as needed or add a comment asking me to.

**Comment by scottmarlow** [comment]
Tally of votes regarding what to call the TCK in the TCK user guide.  [Suggested names so far from email thread](https://www.eclipse.org/lists/jakartaee-tck-dev/msg01002.html):

1. Keep the current doc reference to `Compatibility Test Suite (CTS)`.
2. Change to `Jakarta EE Compatibility Kit (JEECT or EECT or CK)`.
3. Change to `Jakarta EE Platform TCK`

Vote tally:
1. Keep CTS - 0 votes
2. Switch to `JEECT or EECT or CK` - 0 votes
3. Switch to `Jakarta EE Platform TCK` - 1 vote (Amelia Eiras)

**Comment by aeiras** [comment]
you are wonderful Scott! thanks for formalizing tracing on forum discussions via the git, it ROCKS!

**Comment by scottmarlow** [comment]
Note the [Compatibility certification request for Eclipse GlassFish 6.0 for Full Platform, 9.0](https://github.com/eclipse-ee4j/jakartaee-platform/issues/258) + [Compatibility certification request for Eclipse GlassFish 6, Web Profile for Jakarta EE 9, Web Profile](https://github.com/eclipse-ee4j/jakartaee-platform/issues/259) has links to the [RC1 build of the Platform TCK](http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-jakartaeetck-9.0.0-RC1.zip) that does contain the user guide.

**Comment by scottmarlow** [comment]
Feedback from @edbratt  as mentioned by @alwin-joseph :
```
The list “1.2.1 Jakarta EE 9 Technologies Tested with Jakarta EE 9 Platform TCK” in the Jakarta EE TCK platform user guide is incorrect. For example, it claims that the TCK verifies Debugging Support for Other Languages. It also says it verifies JAXB -- neither of these are listed in the “additional requirements” section. This content was inherited from previous version.
```

Feedback from @alwin-joseph:
```
I see the Authentication spec version mentioned is 1.1 in appendix B “The Jakarta Authentication 1.1 specification” (should be 2.0).
```

**Comment by aeiras** [comment]
Dias Scott, 

The current TCK documentation has a fixed certification of GlassFish as a must. 
That hopefully won't be the case on Jakarta EE 10 as Jakarta EE needs to become a neutral project. How does the documentation prepare us for such a adjustment?

**Comment by gerdogdu** [comment]
Hi
> That hopefully won't be the case on Jakarta EE 10 as Jakarta EE needs to become a neutral project. 
Sorry but not understand the meaning of **neutral project**. What do you mean by that?
Regards.
Gurkan

**Comment by aeiras** [comment]
Hello @gerdogdu, 

There is work being done for the Jakarta EE 9 release that contains exchanges explaining in detail the explanation. Please visit: 

https://github.com/jakartaee/jakarta.ee/pull/923

**Comment by gerdogdu** [comment]
> There is work being done for the Jakarta EE 9 release that contains exchanges explaining in detail the explanation. Please visit: jakartaee/jakarta.ee#923

I cannot say that I understand that this decision is made in PR. Do you mean that you have decided in PR and now want to update the TCK content? Is this the way we are doing to update TCK document?

**Comment by scottmarlow** [comment]
> How does the documentation prepare us for such a adjustment?

Hello @aeiras, it does not currently.  

Are you thinking that we should add some descriptive text to the Platform User Guide documentation to encourage more Jakarta EE implementations to be ready on day-zero of the next EE release (e.g. 9.1), to fulfil the requirement to have at least one compatible implementation that includes all of the optional technologies?

**Comment by aeiras** [comment]
That is a fantastic question that needs to reach on its own thread the TCK forum. 

You know I am +1 on inclusion and on broadening the scope of what currently is. the EFSP requires at least 1 implementation, it doesn't limit the ONE.   The documentation being written must make sure that the Jakarta EE project doesn't replicate the Oracle GlassFish days with being the **only** reference implementation.

**Comment by aeiras** [comment]
By the way @scottmarlow, I miss seeing your smily face on the TCK friday calls. Lets see when there is more demos to bring the Jakartees helping on the TCK back together. :) Stay safe and thanks for sharing the different issues to the TCK mailing list. Your actions are fantastic!

**Comment by scottmarlow** [comment]
> By the way @scottmarlow, I miss seeing your smily face on the TCK friday calls. 
Thanks, I enjoy the friday calls and look forward to resuming them!

> Lets see when there is more demos to bring the Jakartees helping on the TCK back together. :) 
I am very pleased to report that I can run GlassFish 6.0 locally again since the blocking issue was fixed via https://github.com/eclipse-ee4j/glassfish/pull/23264, which I greatly appreciate!  I didn't mind using Podman as a workaround until that stopped working around the issue during the last demo.  In summary, I have more demos in mind and also want to catch up to record the previous demo as well.

> Stay safe and thanks for sharing the different issues to the TCK mailing list. Your actions are fantastic!

Thanks @aeiras and the same to you and others!

**Comment by aeiras** [comment]
Oh wow, how wonderful to hear, Scott!

Then, can you please add the demo item back to the  TCK Friday call agenda?  Could you push that demo next Nov. 13th? :)

**Comment by scottmarlow** [comment]
Regarding use of `CTS` versus `Jakarta EE Platform TCK`, we mostly switched to `Jakarta EE Platform TCK` (in form of `Jakarta EE Platform TCK`).  The remaining (few) references to CTS can also be changed (perhaps for EE 9.1).

**Comment by aeiras** [comment]
Scalable, smart & clean! 

🤗
