### ISSUE TITLE
Review and promote Jakarta Tags 2.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#529]
- [X]  1.  Complete userguide/documentation changes for Jakarta Tags  2.0.0 TCK.
- [x] 2.  Review the jakarta-tags-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-tags-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (TAGS_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
@arjantijms https://github.com/eclipse-ee4j/jakartaee-tck/pull/525 is merged which corrects the version numbers for tools:
- DOM
- Apache Commons HTTP Client
- Apache Commons Logging
- Apache Commons Codec

Would you like us to stage an updated Tags TCK with the updated (tool versions corrected) DOC changes?

**Comment by arjantijms** [comment]
Yes, please do.

**Comment by scottmarlow** [comment]
Thanks @alwin-joseph!  

@arjantijms http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-tags-tck-2.0.0.zip was updated via the https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/80/console job run.

**Comment by arjantijms** [comment]
Jakarta Tags execute against latest TCK: https://ci.eclipse.org/jstl/job/2_jstl_run_tck_against_staged_build/13/artifact/tags-tck/bin/summary.txt

**Comment by arjantijms** [comment]
The review was completed and I received no feedback about missing things. I'll now promote the TCK then.

**Comment by arjantijms** [comment]
Promoting was done, and script updated. Closing this issue.
