### ISSUE TITLE
Review and promote Jakarta Security 2.0.0 TCK for JakartaEE 9 release

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#530]
- [x] 1.  Complete userguide/documentation changes for Jakarta Security 2.0.0 TCK.
- [x] 2.  Review the jakarta-security-tck-2.0.0.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly) to look for any changes missed to be included in JakartaEE 9 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-security-tck-2.0.0.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (SECURITY_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/promote_jakartaee9_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by scottmarlow** [comment]
@arjantijms #525 is merged which corrects the version numbers for tools:

    DOM
    Apache Commons HTTP Client
    Apache Commons Logging
    Apache Commons Codec

Would you like us to stage an Security TCK with the updated (tool versions corrected) DOC changes?

CC @alwin-joseph

**Comment by arjantijms** [comment]
Yes, that would be great, thanks in advance!

**Comment by scottmarlow** [comment]
@alwin-joseph thanks for updating!

@arjantijms http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-security-tck-2.0.0.zip is now updated via https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/80/console.

**Comment by alwin-joseph** [comment]
> @alwin-joseph thanks for updating!
> 
> @arjantijms http://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-security-tck-2.0.0.zip is now updated via https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/80/console.

Small correction, security api tck will be updated by https://ci.eclipse.org/jakartaee-tck/job/eftl-standalonetck-build-run-900/81/ after a quick build fix made in https://github.com/eclipse-ee4j/jakartaee-tck/pull/531.

**Comment by arjantijms** [comment]
I'm going to promote the bundle (step 3) as now more changes are anticipated and the ballot has started.

**Comment by arjantijms** [comment]
Security TCK now promoted: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/jakarta-security-tck-2.0.0.zip

**Comment by arjantijms** [comment]
Closing out issue as all steps have been performed.
