### ISSUE TITLE
Unable to run TCK locally

### ISSUE THREAD

**Issue by felipe-alves-moraes** [eclipse-ee4j/jakartaee-tck#538]
Hi, I was following the instructions found here: 
https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Instructions-for-Building-&-Running-Jakarta-EE-Standalone-TCKs
and here:
https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Instructions-for-building-and-running-JakartaEE-TCK-bundle

And when I run I get the following error:
```
[xjc] /Users/fmoraes/dev/workspace/open-source/jakartaee-tck/src/com/sun/ts/lib/implementation/sun/javaee/runtime/app is not found and thus excluded from the dependency check
      [xjc] parsing a schema...
      [xjc] Exception in thread "main" java.lang.NoClassDefFoundError: jakarta.activation.DataHandler
      [xjc] 	at com.sun.tools.xjc.model.CBuiltinLeafInfo.<clinit>(CBuiltinLeafInfo.java:353)
      [xjc] 	at com.sun.tools.xjc.reader.dtd.TDTDReader.<clinit>(TDTDReader.java:412)
      [xjc] 	at com.sun.tools.xjc.ModelLoader.loadDTD(ModelLoader.java:239)
      [xjc] 	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:113)
      [xjc] 	at com.sun.tools.xjc.ModelLoader.load(ModelLoader.java:76)
      [xjc] 	at com.sun.tools.xjc.Driver.run(Driver.java:324)
      [xjc] 	at com.sun.tools.xjc.Driver.run(Driver.java:191)
      [xjc] 	at com.sun.tools.xjc.Driver._main(Driver.java:114)
      [xjc] 	at com.sun.tools.xjc.Driver.access$000(Driver.java:52)
      [xjc] 	at com.sun.tools.xjc.Driver$1.run(Driver.java:73)
      [xjc] Caused by: java.lang.ClassNotFoundException: jakarta.activation.DataHandler
      [xjc] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:591)
      [xjc] 	at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:953)
      [xjc] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:898)
      [xjc] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
      [xjc] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:881)
```

Tried with both commands:
`$WORKSPACE/docker/build_jakartaeetck.sh` and `docker/build_jakartaeetck.sh <technology>`

Running on:
MacOS Catalina
Java: openjdk8
Ant: 1.10.8
Maven: 3.6.3

**Comment by alwin-joseph** [comment]
The script to build standalone tck is docker/build_standalone-tcks.sh <technology>. The acceptable list of technologies are at https://github.com/eclipse-ee4j/jakartaee-tck/blob/820cdcd9bd83de26bd529715886d08efd1201a47/Jenkinsfile#L195

$WORKSPACE/docker/build_jakartaeetck.sh is to build the platform tck and it doesnt accept/need technology as parameter.

**Comment by felipe-alves-moraes** [comment]
THank @alwin-joseph, I could build and run some standalone tck, but I got the following issues:

```
Creating report file:/Users/fmoraes/dev/workspace/open-source/jakartaee-tck/results/junitreports/jsonp-tck-junit-report.xml
Creating test suite with id=1, component=jsonp-tck, hostname=Felipes-MBP
java.io.FileNotFoundException: /Users/fmoraes/dev/workspace/open-source/jakartaee-tck/jsonp-tckreport/jsonp-tck/html/env.html (No such file or directory)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at org.jsoup.helper.DataUtil.load(DataUtil.java:52)
	at org.jsoup.Jsoup.parse(Jsoup.java:103)
	at org.eclipse.ee4j.jakartaeetck.tools.jtreportparser.JTReportParser.parseProperties(JTReportParser.java:310)
	at org.eclipse.ee4j.jakartaeetck.tools.jtreportparser.JTReportParser.main(JTReportParser.java:411)
```
The xml file it says it was created, is empty.
Before that it was complaining that couldn't find a html folder inside `<technology>-tckreport/<technology>-tck/`

Also, still cannot run the `$WORKSPACE/docker/build_jakartaeetck.sh`, same error as above

**Comment by alwin-joseph** [comment]
> THank @alwin-joseph, I could build and run some standalone tck, but I got the following issues:
> 
> ```
> Creating report file:/Users/fmoraes/dev/workspace/open-source/jakartaee-tck/results/junitreports/jsonp-tck-junit-report.xml
> Creating test suite with id=1, component=jsonp-tck, hostname=Felipes-MBP
> java.io.FileNotFoundException: /Users/fmoraes/dev/workspace/open-source/jakartaee-tck/jsonp-tckreport/jsonp-tck/html/env.html (No such file or directory)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at org.jsoup.helper.DataUtil.load(DataUtil.java:52)
> 	at org.jsoup.Jsoup.parse(Jsoup.java:103)
> 	at org.eclipse.ee4j.jakartaeetck.tools.jtreportparser.JTReportParser.parseProperties(JTReportParser.java:310)
> 	at org.eclipse.ee4j.jakartaeetck.tools.jtreportparser.JTReportParser.main(JTReportParser.java:411)
> ```
> 
> The xml file it says it was created, is empty.
> Before that it was complaining that couldn't find a html folder inside `<technology>-tckreport/<technology>-tck/`
> Also I couldn't find any test reports
> 
> Also, still cannot run the `$WORKSPACE/docker/build_jakartaeetck.sh`, same error as above

I havent seen this exception while building tcks which are being used in the CI jobs . Can you point out which line of the build script leads to this exception.

**Comment by scottmarlow** [comment]
In case it helps, here is how I build the Platform TCK locally (note that ant has to be on the path):
```
wget https://archive.apache.org/dist/ant/binaries/apache-ant-1.10.6-bin.zip
unzip -o apache-ant-1.10.6-bin.zip; rm -f apache-ant-1.10.6-bin.zip
export ANT_HOME=/apache-ant-1.10.6
export PATH=$ANT_HOME/bin:$PATH
export ANT_OPTS="-Djavax.xml.accessExternalStylesheet=all -Djavax.xml.accessExternalSchema=all -Djavax.xml.accessExternalDTD=file,http -Duser.home=$HOME"
export PATH=$JAVA_HOME/bin:$ANT_HOME/bin/:$PATH

cd /tmp
git clone https://github.com/eclipse-ee4j/jakartaee-tck
cd jakartaee-tck
export WORKSPACE=$PWD
export GF_BUNDLE_URL=https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip

bash -x ${WORKSPACE}/docker/build_jakartaeetck.sh 2>&1 | tee ${WORKSPACE}/build_jakartaeetck.log
# . ./docker/build_jakartaeetck.sh
cd ${WORKSPACE}
mkdir -p ${WORKSPACE}/jakartaeetck-bundles
# need to zip release/JAKARTAEE_BUILD/build_09-Sep-2020/bundle/jakartaeetck
cd ${WORKSPACE}/release/JAKARTAEE_BUILD/build*/bundle/
zip -r ${WORKSPACE}/jakartaeetck-bundles/jakartaeetck.zip jakartaeetck
cd ${WORKSPACE}/jakartaeetck-bundles

rm -rf /tmp/run
mkdir /tmp/run
cp jakartaeetck.zip /tmp/run

# run TCK 
cd /tmp/run
export WORKSPACE=`pwd`
unzip jakartaeetck.zip
cd jakartaeetck

export GF_BUNDLE_URL=https://download.eclipse.org/ee4j/glassfish/glassfish-6.0.0-SNAPSHOT-nightly.zip
export PROFILE=FULL
export BUILD_TYPE=CTS
export TCK_BUNDLE_BASE_URL=
export CTS_HOME=$WORKSPACE
export WORKSPACE=`pwd`
bash -x docker/run_jakartaeetck.sh samples/ejb 2>&1 | tee run_cts.log
```

**Comment by scottmarlow** [comment]
closing as out of date.  Please reopen if the issue still is a problem.
