### ISSUE TITLE
Just guessing about JMS version

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/jakartaee-tck#549]
Should these be updated?
https://github.com/eclipse-ee4j/jakartaee-tck/blob/943ded4678cd4fe94f74ca2479f3c6e092f75d36/src/com/sun/ts/tests/jms/common/JmsTool.java#L117-L119

**Comment by arjantijms** [comment]
Very likely. May even be the cause of the 4 failures we saw.

**Comment by pzygielo** [comment]
I roamed to those fields exactly from errors reported by `c.s.t.t.jms.core.queueConnection.QueueConnectionTests.metaDataTests` and companion :smile:

**Comment by scottmarlow** [comment]
Do you have a link for the test failure or more details of what the JMS implementation was that your testing?

**Comment by scottmarlow** [comment]
The metaDataTests tests seem to look for an exact version match which currently passes JMS testing (incuding the [metaDataTests ](https://ci.eclipse.org/jakartaee-tck/job/eftl-jakartaeetck-run-900/51/testReport/com.sun.ts.tests.jms.core.queueConnection/QueueConnectionTests/)).  

I agree this looks wrong.

**Comment by arjantijms** [comment]
The test failures can be seen here: 

https://ci.eclipse.org/openmq/job/2_openmq-run-tck-against-staged-build/7/

**Comment by scottmarlow** [comment]
For comparison, I started https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow/job/jms_3.0/2/ to run the JMS tests with GlassFish and https://github.com/scottmarlow/jakartaee-tck/tree/jms_3.0 updated to use 3.0 for JMS spec version.

**Comment by pzygielo** [comment]
Closed in #552

**Comment by smillidge** [comment]
@scottmarlow the class you reference is not a GlassFish class it is brought into GlassFish through the implementation OpenMQ integrated. I'm assuing https://github.com/eclipse-ee4j/glassfish/pull/23248 will bring the TCK and GlassFish into synch @pzygielo can you confirm?

**Comment by pzygielo** [comment]
@smillidge - yes, it should.

**Comment by alwin-joseph** [comment]
> The test failures can be seen here:
> 
> https://ci.eclipse.org/openmq/job/2_openmq-run-tck-against-staged-build/7/

The staged messaging TCK was updated at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-messaging-tck-3.0.0.zip after merging https://github.com/eclipse-ee4j/jakartaee-tck/pull/552. Can you please retrigger the job.

**Comment by arjantijms** [comment]
@alwin-joseph Thx! I retriggered the job and now all tests pass.

See https://ci.eclipse.org/openmq/job/2_openmq-run-tck-against-staged-build/9/artifact/messaging-tck/bin/summary.txt
