### ISSUE TITLE
TSAuthConfigProviderServlet logger not initialized when used with vendor AuthConfigFactory

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jakartaee-tck#570]
The TCK user guide specifies there is 2 options to set up the TSSV.
1/ use the JVM wide configuration to load the TS AuthConfigFactory.
2/ use the AuthConfigFactory.register methods to register the provider

When using 2/, the TSAuthConfigFactory is not used and won't call the 3 args constructor on TSAuthConfigProviderServlet. See link bellow.

As a result the TSLogger is not initialized correctly because it's static and the handler is not associated with it. 

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaspic/tssv/config/TSAuthConfigProviderServlet.java#L59

Removing eager init here
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaspic/tssv/config/TSAuthConfigProviderServlet.java#L59

Should let the constructor to do the proper init.

The TSAuthConfigProvider is fine but TSAuthConfigProviderStandalone does not seem to be either.

**Comment by scottmarlow** [comment]
Does this impact the running of all jaspic tests?

**Comment by jeanouii** [comment]
Thanks Scott for the quick answer. Trying to capture Slack discussion here so everyone has the same knowledge.

As far as I can see with Tomcat, 6 are failing (62 success)
![image](https://user-images.githubusercontent.com/1233474/98866359-18244f00-246d-11eb-958d-1e454d7cfa26.png)

This is from Jakarta Authentication TCK user guide
With the first approach I get 100% success but I don’t want that because I’m using other tests in a row, securityapi for instance and it creates failures. And I don’t want to use the TSAuthConfigFactory (which I could) for securityapi because them I’m not testing Tomcat implementation but the TCK testing one lol

**Comment by arjantijms** [comment]
Maybe not a direct help for now, but I'd soon like to look into those TCK tests as well. I'm not a terribly big fan of there setup though. We discussed a long time ago with the JASPIC spec lead and TCK engineer to augment these with a set of tests that work just like e.g. the Servlet tests (they only do HTTP requests to the server under test and assert based on that).

**Comment by jeanouii** [comment]
I find the setup very complex compared to other stuff. And when you run other parts of Jakarta EE, then it becomes even harder because it breaks other tests.

**Comment by arjantijms** [comment]
Even worse, the TCK doesn't even "work". It may test a bunch of classes being present, but what is the most important aspect of Jakarta Authentication? That it actually authenticates, right?

And there's no real test that actually tests that :(

**Comment by jeanouii** [comment]
Totally agree @arjantijms 
When EE 9 is out, we should discuss about it and see if we can help.

**Comment by scottmarlow** [comment]
hmm, not sure what the eye emoji thing means really.  +1 for fixing this!

**Comment by jeanouii** [comment]
Closed in order to follow up on the authentication project
https://github.com/eclipse-ee4j/authentication/issues/116
