### ISSUE TITLE
JTA Transactional tests leaking

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jakartaee-tck#573]
Some methods in the Transactional subset of JTA are implemented like this https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jta/ee/transactional/Client.java#L420

Basically a userTransaction.begin() with catch and no finally. No commit()/rollback() seems to happen and therefor the transaction leaks into the ThreadContext and well, if you are lucky next test uses a different thread, all good, if you are not, then a transaction is already associated with the thread and the begin fails. That creates random failures to me.

**Comment by jeanouii** [comment]
Closing this one because I created one in the jta-api project

https://github.com/eclipse-ee4j/jta-api/issues/185

**Comment by scottmarlow** [comment]
Thank you @jeanouii
