### ISSUE TITLE
JPA persistence.xml referencing non existing jar files.

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jakartaee-tck#580]
I’m back into TomEE regarding TCK failures .... Here is one where I’d like some feedback.
The test is com.sun.ts.tests.jpa.ee.packaging.jar.Client --> https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jpa/ee/packaging/jar/Client.java

It’s failing because the JPA provider can’t find the jar-file from the persistence.xml
I opened the EAR file used by the test (see bellow).
![image](https://user-images.githubusercontent.com/1233474/100589870-ee37ad00-32f3-11eb-9d5f-45d7066f70f7.png)

The persistence effectively has 2 jar-file entries. But if you look at the file name on the right side in the persistence.xml and you also look at the left side to the content of the EAR file, you can see that the filename in the persistence.xml file has “_jarfile” before the number 1 or 2.

See https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jpa/ee/packaging/jar/build.xml on how the EAR file with the jar files are created.

What do you think?
How can this even work with Glassfish?

**Comment by hussainnm** [comment]
The relevant logs from the last Glassfish TCK run. Glassfish is just creating a warning saying file not found for given jar filename but continues to process B and C class from the classpath.

[jpa_ee_packaging_jar_vehicles.txt](https://github.com/eclipse-ee4j/jakartaee-tck/files/5615127/jpa_ee_packaging_jar_vehicles.txt) extracted from root/vi/glassfish6/glassfish/domains/domain1/logs/server.log [lines 2558-2753]

> [2020-11-12T05:54:25.937+0000] [glassfish 6.0] [WARNING] [puinfo.referenced_jar_not_found] [javax.org.glassfish.persistence.org.glassfish.persistence.jpa] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160465937] [levelValue: 900] [[
>   PER02000: PersistenceUnitInfoImpl: For pu-root [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/jpa_ee_packaging_jar_pmservlet_vehicle_web_war/WEB-INF/lib/jpa_ee_packaging_jar.jar], a jar-file [jpa_ee_packaging_jar_jarfile1.jar/] specified in persistence.xml is not found. The server also looked for a file called [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/jpa_ee_packaging_jar_pmservlet_vehicle_web_war/WEB-INF/lib/jpa_ee_packaging_jar_jarfile1.jar__]. Please verify your application.]]
> 
> [2020-11-12T05:54:25.938+0000] [glassfish 6.0] [WARNING] [puinfo.referenced_jar_not_found] [javax.org.glassfish.persistence.org.glassfish.persistence.jpa] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160465938] [levelValue: 900] [[
>   PER02000: PersistenceUnitInfoImpl: For pu-root [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/jpa_ee_packaging_jar_pmservlet_vehicle_web_war/WEB-INF/lib/jpa_ee_packaging_jar.jar], a jar-file [jpa_ee_packaging_jar_jarfile2.jar/] specified in persistence.xml is not found. The server also looked for a file called [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/jpa_ee_packaging_jar_pmservlet_vehicle_web_war/WEB-INF/lib/jpa_ee_packaging_jar_jarfile2.jar__]. Please verify your application.]]
> 
> [2020-11-12T05:54:26.064+0000] [glassfish 6.0] [WARNING] [puinfo.referenced_jar_not_found] [javax.org.glassfish.persistence.org.glassfish.persistence.jpa] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466064] [levelValue: 900] [[
>   PER02000: PersistenceUnitInfoImpl: For pu-root [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar.jar], a jar-file [jpa_ee_packaging_jar_jarfile1.jar/] specified in persistence.xml is not found. The server also looked for a file called [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar_jarfile1.jar__]. Please verify your application.]]
> 
> [2020-11-12T05:54:26.065+0000] [glassfish 6.0] [WARNING] [puinfo.referenced_jar_not_found] [javax.org.glassfish.persistence.org.glassfish.persistence.jpa] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466065] [levelValue: 900] [[
>   PER02000: PersistenceUnitInfoImpl: For pu-root [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar.jar], a jar-file [jpa_ee_packaging_jar_jarfile2.jar/] specified in persistence.xml is not found. The server also looked for a file called [/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar_jarfile2.jar__]. Please verify your application.]]
> 
> [2020-11-12T05:54:26.133+0000] [glassfish 6.0] [INFO] [NCLS-COMUTIL-00017] [jakarta.enterprise.system.util] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466133] [levelValue: 800] [[
>   com.sun.ts.tests.jpa.ee.packaging.jar.C actually got transformed]]
> 
> [2020-11-12T05:54:26.150+0000] [glassfish 6.0] [INFO] [NCLS-COMUTIL-00017] [jakarta.enterprise.system.util] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466150] [levelValue: 800] [[
>   com.sun.ts.tests.jpa.ee.packaging.jar.B actually got transformed]]
> 
> [2020-11-12T05:54:26.166+0000] [glassfish 6.0] [INFO] [NCLS-COMUTIL-00017] [jakarta.enterprise.system.util] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466166] [levelValue: 800] [[
>   com.sun.ts.tests.jpa.ee.packaging.jar.A actually got transformed]]
> 
> [2020-11-12T05:54:26.226+0000] [glassfish 6.0] [INFO] [] [org.eclipse.persistence.session./file:/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/jpa_ee_packaging_jar_pmservlet_vehicle_web_war/WEB-INF/lib/jpa_ee_packaging_jar.jar_CTS-EM] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466226] [levelValue: 800] [[
>   EclipseLink, version: Eclipse Persistence Services - 3.0.0.v202009251227]]
> 
> [2020-11-12T05:54:26.288+0000] [glassfish 6.0] [INFO] [] [org.eclipse.persistence.session./file:/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/jpa_ee_packaging_jar_pmservlet_vehicle_web_war/WEB-INF/lib/jpa_ee_packaging_jar.jar_CTS-EM2] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466288] [levelValue: 800] [[
>   EclipseLink, version: Eclipse Persistence Services - 3.0.0.v202009251227]]
> 
> [2020-11-12T05:54:26.292+0000] [glassfish 6.0] [INFO] [] [org.eclipse.persistence.session./file:/root/vi/glassfish6/glassfish/domains/domain1/applications/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar.jar_CTS-EM] [tid: _ThreadID=85 _ThreadName=AutoDeployer] [timeMillis: 1605160466292] [levelValue: 800] [[
>   EclipseLink, version: Eclipse Persistence Services - 3.0.0.v202009251227]]
>

**Comment by jeanouii** [comment]
Thanks for the feedback Hussain.
EclipseLink fails by default with the following
`	Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.4.v20190115-ad5b7c6b2a): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [CTS-EM] failed.
Internal Exception: java.lang.RuntimeException: java.io.FileNotFoundException: /home/.../javaee8tck/dist/com/sun/ts/tests/jpa/ee/packaging/jar/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar_jarfile1.jar (No such file or directory)
		at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2106)
		at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2082)
		at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:350)
		at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:316)`

Not sure what glassfish is doing before delegating to EclipseLink. Maybe it's parsing persistence.xml file to remove bad links instead of failing.

**Comment by jeanouii** [comment]
We should definitely be more clear on what the persistence provider should do or not when the jar-file is not found.
Here is what glassfish is doing ...

`            if (jarFile.exists()) {
                try {
                    jarFiles.add(jarFile.toURI().toURL());
                } catch (MalformedURLException e) {
                    throw new RuntimeException(e);
                }
            } else {
                // Should be a caught by verifier. So, just log a message
                if (logger.isLoggable(Level.WARNING)) {
                    logger.log(Level.WARNING, "puinfo.referenced_jar_not_found", new Object[]{absolutePuRoot, jarFileName, jarFile});
                }
            }
`

**Comment by scottmarlow** [comment]
> Not sure what glassfish is doing before delegating to EclipseLink. Maybe it's parsing persistence.xml file to remove bad links instead of failing.

There aren't any JPA container contract requirements to remove bad links or references to jar files that do not exist, so this is a valid test even though it could be improved by correcting the incorrect jar file name reference.  

https://github.com/wildfly/wildfly/blob/master/jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java#L257 is not failing the deployment either.  

Could you please also attach the failing test .jtr file for this issue and any other (TCK test failure) issue that you create.  Thanks!

**Comment by jeanouii** [comment]
Thanks Scott.
This is rather strange ...

The JPA spec says ....

> One or more JAR files may be specified using the jar-file elements instead of, or in addition to the mapping files specified in the mapping-file elements. If specified, these JAR files will be searched for managed persistence classes, and any mapping metadata annotations found on them will be processed, or they will be mapped using the mapping annotation defaults defined by this specification. Such JAR files are specified relative to the directory or jar file that contains the root of the persistence unit.

As a user I would expect it to fail if jar-file is not found because the JPA provider has to find entities and mappings.
EclipseLink fails by the way which is really what I would expect.

> 	Caused by: javax.persistence.PersistenceException: Exception [EclipseLink-28018] (Eclipse Persistence Services - 2.7.4.v20190115-ad5b7c6b2a): org.eclipse.persistence.exceptions.EntityManagerSetupException
Exception Description: Predeployment of PersistenceUnit [CTS-EM] failed.
Internal Exception: java.lang.RuntimeException: java.io.FileNotFoundException: /Users/<path>/jakartaeetck-prebuilt-8.0.2/release/jakartaeetck-prebuilt-8.0.2/dist/com/sun/ts/tests/jpa/ee/packaging/jar/jpa_ee_packaging_jar_vehicles/lib/jpa_ee_packaging_jar_jarfile1.jar (No such file or directory)
		at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.createPredeployFailedPersistenceException(EntityManagerSetupImpl.java:2106)
		at org.eclipse.persistence.internal.jpa.EntityManagerSetupImpl.predeploy(EntityManagerSetupImpl.java:2082)
		at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactoryImpl(PersistenceProvider.java:350)
		at org.eclipse.persistence.jpa.PersistenceProvider.createContainerEntityManagerFactory(PersistenceProvider.java:316)


Again that's what I was expecting.


> https://github.com/wildfly/wildfly/blob/master/jpa/subsystem/src/main/java/org/jboss/as/jpa/processor/PersistenceUnitParseProcessor.java#L257 is not failing the deployment either.

TomEE essentially does the same. Reads the file and passes in anything it reads from the persistence.xml file. Then it's up to OpenJPA, Hibernate, EclipseLink to work with it.

Glassfish on the other hand yanks the jar-file if it does not exist so EclipseLink does not fail anymore after that.
If the tests are passing even with that warning, does it mean Glassfish is doing some magic to find the jar files in the EAR and search for entities and mapping?

**Comment by scottmarlow** [comment]
> The JPA spec says ....
> 
> > One or more JAR files may be specified using the jar-file elements instead of, or in addition to the mapping files specified in the mapping-file elements. If specified, these JAR files will be searched for managed persistence classes, and any mapping metadata annotations found on them will be processed, or they will be mapped using the mapping annotation defaults defined by this specification. Such JAR files are specified relative to the directory or jar file that contains the root of the persistence unit.
> 
> As a user I would expect it to fail if jar-file is not found because the JPA provider has to find entities and mappings.
> EclipseLink fails by the way which is really what I would expect.

IMO, there may be many applications (in the world) that contain invalid things that could cause application deployment failures but don't as they go unchecked.  Some of those applications may be in binary form only as the ability to build from source is not possible.  

> Glassfish on the other hand yanks the jar-file if it does not exist so EclipseLink does not fail anymore after that.
> If the tests are passing even with that warning, does it mean Glassfish is doing some magic to find the jar files in the EAR and search for entities and mapping?
> 

I'm not sure of what GlassFish is doing but the JPA specification does not rule against performing some magic with regard to yanking the invalid jar-file reference.

**Comment by dblevins** [comment]
We should be filing these TCK challenges in the actual specification project.  Let's move this conversation over to Jakarta Persistence.

**Comment by scottmarlow** [comment]
I do not yet see a  tck.challenge but sure if others do, please do create a Jakarta Persistence tck challenge.

**Comment by dblevins** [comment]
Here's how I identify a "lost" or "misdirected" challenge.

 - identifying potentially flawed tests by name
 - quoting spec requirements (or lack thereof)
 - pointing out what other implementations do and don't do

If they hit this trifecta or get close we should encourage them to file a challenge in the spec project and, if accepted, come back with PR reflecting consensus.

Most people will come straight here as this is where the source lives, so we'll likely have to say that a lot.  I suspect that will uncover some important and tricky "who should own this test" questions.

**Comment by scottmarlow** [comment]
@jeanouii you should continue this discussion on https://github.com/eclipse-ee4j/jpa-api/issues/new, however, I don't see any labels when creating a new jpa-api issue which also needs to be addressed.  

As per https://jakarta.ee/committees/specification/tckprocess the 'challenge' label needs to be used for TCK challenges.

**Comment by jeanouii** [comment]
Closing this one because I opened one in the project https://github.com/eclipse-ee4j/jpa-api/issues/299
