### ISSUE TITLE
Remove dependency on implementations for building TCKs

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#583]
Currently we use glassfish server downloaded for building the platform and some of the standalone TCKs mostly to resolve the spec classes. This dependency should be removed so that the TCKs can be built without dependency on any specific implementation - GlassFish, Metro, JAXB etc. The jars could be separately downloaded from maven central repository if required.

Platform TCK : 
-rw-r-----. 1 1000270000 1000270000    47669 Aug  4 09:42 jakarta.activation.jar
-rw-r-----. 1 1000270000 1000270000    25414 Nov  1 17:00 jakarta.annotation-api.jar
-rw-r-----. 1 1000270000 1000270000    43826 Nov  1 17:00 jakarta.authentication-api.jar
-rw-r-----. 1 1000270000 1000270000    44860 Nov  1 17:00 jakarta.authorization-api.jar
-rw-r-----. 1 1000270000 1000270000    44920 Nov  1 17:00 jakarta.batch-api.jar
-rw-r-----. 1 1000270000 1000270000    59998 Nov  1 17:00 jakarta.ejb-api.jar
-rw-r-----. 1 1000270000 1000270000    80563 Nov  1 17:00 jakarta.el-api.jar
-rw-r-----. 1 1000270000 1000270000   119330 Nov  1 17:00 jakarta.enterprise.cdi-api.jar
-rw-r-----. 1 1000270000 1000270000    26569 Nov  1 17:00 jakarta.enterprise.concurrent-api.jar
-rw-r-----. 1 1000270000 1000270000  3505221 Nov  1 17:00 jakarta.faces.jar
-rw-r-----. 1 1000270000 1000270000    10128 Nov  1 17:00 jakarta.inject-api.jar
-rw-r-----. 1 1000270000 1000270000    24599 Nov  1 17:00 jakarta.interceptor-api.jar
-rw-r-----. 1 1000270000 1000270000    56270 Nov  1 17:00 jakarta.jms-api.jar
-rw-r-----. 1 1000270000 1000270000    35689 Nov  1 17:00 jakarta.json.bind-api.jar
-rw-r-----. 1 1000270000 1000270000   142417 Nov  1 17:00 jakarta.json.jar
-rw-r-----. 1 1000270000 1000270000   681767 Nov  1 17:00 jakarta.mail.jar
-rw-r-----. 1 1000270000 1000270000   156487 Nov  1 17:00 jakarta.persistence-api.jar
-rw-r-----. 1 1000270000 1000270000    68470 Nov  1 17:00 jakarta.resource-api.jar
-rw-r-----. 1 1000270000 1000270000    45372 Nov  1 17:00 jakarta.security.enterprise-api.jar
-rw-r-----. 1 1000270000 1000270000   307850 Nov  1 17:00 jakarta.servlet-api.jar
-rw-r-----. 1 1000270000 1000270000    66885 Nov  1 17:00 jakarta.servlet.jsp-api.jar
-rw-r-----. 1 1000270000 1000270000    46024 Nov  1 17:00 jakarta.servlet.jsp.jstl-api.jar
-rw-r-----. 1 1000270000 1000270000    27927 Nov  1 17:00 jakarta.transaction-api.jar
-rw-r-----. 1 1000270000 1000270000    92678 Nov  1 17:00 jakarta.validation-api.jar
-rw-r-----. 1 1000270000 1000270000    49349 Nov  1 17:00 jakarta.websocket-api.jar
-rw-r-----. 1 1000270000 1000270000   138761 Nov  1 17:00 jakarta.ws.rs-api.jar
-rw-r-----. 1 1000270000 1000270000   129000 Sep 23 11:14 jakarta.xml.bind-api.jar
-rw-r-----. 1 1000270000 1000270000  3528977 Nov 18 17:40 jaxb-osgi.jar
-rw-r-----. 1 1000270000 1000270000   444597 Nov  1 17:00 security.jar (used to resolve com.sun.enterprise.security.auth.login)
-rw-r--r--. 1 1000270000 1000270000   296979 Nov 18 19:00 webservices-api.jar
-rw-r--r--. 1 1000270000 1000270000    97367 Nov 18 18:59 webservices-api-osgi.jar
-rw-r--r--. 1 1000270000 1000270000 10435770 Nov 18 18:59 webservices-osgi.jar
-rw-r--r--. 1 1000270000 1000270000  2842138 Nov 18 18:59 webservices-tools.jar

**Comment by scottmarlow** [comment]
Should we use Maven to download the jars based on a pom.xml?

**Comment by alwin-joseph** [comment]
> Should we use Maven to download the jars based on a pom.xml?

I think pom.xml is better but I dont know yet , how it can be integrated with the current build setup which uses ant commands for build. Can we separate the download part alone into maven pom.xml.

**Comment by edbratt** [comment]
Please see https://github.com/eclipse-ee4j/jaxrs-api/issues/924
We need to be sure that new features that are added to any TCK are imported to the Platform TCK.
Also, if the Platform has other requirements (i.e. run in different modes, and/or containers) those are achievable.
We may want to try and coalesce these discussions to come up with a combined strategy everyone can adopt.

**Comment by scottmarlow** [comment]
> Please see [eclipse-ee4j/jaxrs-api#924](https://github.com/eclipse-ee4j/jaxrs-api/issues/924)

Thanks, I didn't see this issue before.

> We need to be sure that new features that are added to any TCK are imported to the Platform TCK.
> Also, if the Platform has other requirements (i.e. run in different modes, and/or containers) those are achievable.
> We may want to try and coalesce these discussions to come up with a combined strategy everyone can adopt.

+1 for coming up with a combined strategy that everyone can adopt.  I mentioned some ideas on the Platform TCK mailing list today for discussing over email.  The difficult thing is that not everyone is on the same mailing list.  I suggested that we cross post on all of the SPEC API mailing lists and some others but thinking more about that, perhaps we could start with cross posting on all SPEC API mailing lists to ask which SPEC API teams would like their own SPEC API level TCK.  Then, we can have a discussion with that subset of SPEC API teams.

Other ideas?

**Comment by alwin-joseph** [comment]
Latest Update : 

The list of jars currently used to build the platform TCK are available at docker/pom.xml

PRs made for this issue 
-https://github.com/eclipse-ee4j/jakartaee-tck/pull/595
-https://github.com/eclipse-ee4j/jakartaee-tck/pull/602 (bring back security.jar from glassfish to compile SunRILoginContext.java)

Pending : 
The usage of security.jar from https://repo1.maven.org/maven2/org/glassfish/security/security/3.1.1/security-3.1.1.jar as per the current changes(https://github.com/eclipse-ee4j/jakartaee-tck/pull/602) is not expected.  
This is done because below methods from com.sun.enterprise.security.auth.login package (available in security.jar) is used in SunRILoginContext.java.
-LoginContextDriver.doClientLogin()
-LoginContextDriver.logout()

SunRILoginContext.java is used for ejb, ejb30/sec tests. Any thoughts on how we can remove this usage or replace the current methods?

**Comment by scottmarlow** [comment]
Pasting my feedback here from the Platform TCK mailing list discussion:
```
In the Platform TCK source for ts.jte, I see SunRILoginContext referenced for:

"
@porting.ts.login.class.1  VI of com.sun.ts.lib.porting.TSLoginContextInterface

@porting.ts.login.class.2  RI of com.sun.ts.lib.porting.TSLoginContextInterface
"

When non-GlassFish implementations deploy tests to their EE implementation, I think that any of the reverse/forward tests that also run a second EE server will need porting.ts.login.class.2 to be set to their second implementation that they are testing against.  If they use GlassFish as the second server, that would indeed use the "porting.ts.login.class.2=com.sun.ts.lib.implementation.sun.javaee.SunRILoginContext" setting.  However, if the SunRILoginContext class is only actually used for the ejb, ejb30/sec tests, I think that means the "porting.ts.login.class.2" is no longer needed since we removed the interop tests which were probably the only use (EJB) case of "porting.ts.login.class.2".  If removing "porting.ts.login.class.2" works (e.g. GlassFish 6 still passes Java SE 8 TCK), then I think only the GlassFish EE 9.1 implementation needs the com.sun.ts.lib.implementation.sun.javaee.SunRILoginContext class.

Some possible options for eliminating the Platform TCK on the GlassFish security.jar:

1.  Compile com.sun.ts.lib.implementation.sun.javaee.SunRILoginContext and create a jar that contains the class, check that jar into the Platform TCK as a convenience for GlassFish testing to then use that jar when testing against EE 9.1.  Also rename
SunRILoginContext.java to SunRILoginContext.java.src or something like that to stop compiling SunRILoginContext.java when building the TCK. 
2.  Move the SunRILoginContext.java to a GlassFish TCK porting (git) repository.
```

**Comment by scottmarlow** [comment]
@alwin-joseph do either of the options mentioned in previous comment make sense to you for eliminating the security.jar dependency?

**Comment by scottmarlow** [comment]
@smillidge do you have any suggestions for removing the GlassFish security.jar dependencies from https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/implementation/sun/javaee/SunRILoginContext.java?

FYI the SunRILoginContext class also depends on the Platform TCK TSLoginContextInterface class.

**Comment by alwin-joseph** [comment]
> @alwin-joseph do either of the options mentioned in previous comment make sense to you for eliminating the security.jar dependency?

@scottmarlow  Thanks for the suggestion. I think option 1 can help along with reference to the new jar in the CP. I am yet to try this. If I understand correctly Option 2 will create new dependency outside the tck repo.

**Comment by scottmarlow** [comment]
@alwin-joseph I added Option 3 as well.

> Thanks for the suggestion. I think option 1 can help along with reference to the new jar in the CP. I am yet to try this. If I understand correctly Option 2 will create new dependency outside the tck repo.

After 9.1, I think we will want to build the GlassFish-porting-kit classes via a separate job.  So whatever we do for 9.1, is short term I think.  The longer term goal for this year is for the TCK to not directly depend on GlassFish but that is a lot of change to make at once.  

My preference for 2021 is to at least move SunRILoginContext out of the TCKs build.

**Comment by alwin-joseph** [comment]
The dependency on glassfish was removed for platform TCK using below PRs.
https://github.com/eclipse-ee4j/jakartaee-tck/pull/595
https://github.com/eclipse-ee4j/jakartaee-tck/pull/602
https://github.com/eclipse-ee4j/jakartaee-tck/pull/622 

The same can be done for the standalone TCKs hence keeping the issue open.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/761 removes most of the GlassFish references for building Standalone TCKS.

**Comment by gurunrao** [comment]
@scottmarlow @alwin-joseph - since PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/761 remove glassfish references for Standalone TCK, shall we close the issue?
