### ISSUE TITLE
javax_shttpServletMappingDispatchTest() incorrectly expects the original mapping

### ISSUE THREAD

**Issue by gregw** [eclipse-ee4j/jakartaee-tck#585]
The TCK test https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest40/Client.java#L210 does a Async dispatch 
from https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest40/DispatchServlet.java#L33
to https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/api/jakarta_servlet_http/httpservletrequest40/TestServlet.java#L29 which prints out the `HttpServletMapping`
The tests expects the mapping to be `matchValue=DispatchServlet, pattern=/DispatchServlet, servletName=DispatchServlet, mappingMatch=EXACT`

The correctness of this test has been questioned in https://github.com/eclipse-ee4j/servlet-api/issues/309 and that the mapping should be for the target of the async dispatch.
It is also apparent that most containers are implemented to not pass this test.

Note the EE8 test is at https://github.com/eclipse-ee4j/jakartaee-tck/blob/8.0.2/src/com/sun/ts/tests/servlet/api/javax_servlet_http/httpservletrequest40/Client.java#L210

**Comment by scottmarlow** [comment]
Hi @gregw are you asking for these tests to be excluded from a particular EE release?  In which case a TCK challenge issue would needed for the Servlet API project.

Or are you just looking for the tests to be improved in the next EE release?

I just added some templates for new issues to https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/.github/ISSUE_TEMPLATE which will hopefully make it clearer where TCK challenges should be created.

CC @stuartwdouglas @markt-asf

**Comment by gregw** [comment]
@scottmarlow Well actually the TCK is correct for how the specification is currently written.  So I guess I need to get better agreement on updating the spec... and then challenge the TCK.  Closing for now.

**Comment by gregw** [comment]
Correction.... we have already updated the spec in https://github.com/eclipse-ee4j/servlet-api/pull/313, so I will file a challenge and leave this one closed.

**Comment by gregw** [comment]
https://github.com/eclipse-ee4j/servlet-api/issues/385
