### ISSUE TITLE
javamail/ee/fetchprofile/fetchprofile_Test.java doesn't clean up resources

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-tck#586]
We experience follow-on problems (and have for quite some time) when we run the javamail bucket in its entirety.  This never has prevented us from certifying because the tests pass in isolation from each other, so this is a bug, not a challenge.

The problem is that fetchprofile_Test.java sets up some resources in its setup() method:
>       store = mailTestUtil.connect2host(protocol, host, imapPort, user,
>           password);
> 
>       // Get a Folder object
>       Folder root = getRootFolder(store);
>       folder = root.getFolder(mailbox);
> 
>       ...
>       folder.open(Folder.READ_ONLY);

But these resources are only properly cleaned up in the implementation of test2:
>       folder.close(false);
>       store.close();

When other tests in the class are run that don't clean up these resources, we get ugly exceptions in the setup() method for the following test, like:
> [javatest.batch] [err] jakarta.mail.MessagingException: Connection dropped by server?;
> [javatest.batch]   nested exception is:
> [javatest.batch] 	java.io.IOException: Connection dropped by server?
> [javatest.batch] [err] 	at com.sun.mail.imap.IMAPStore.protocolConnect(IMAPStore.java:718)
> [javatest.batch] [err] 	at [internal classes]
> [javatest.batch] [err] 	at com.sun.ts.tests.javamail.ee.common.MailTestUtil.connect2host(MailTestUtil.java:319)
> [javatest.batch] [err] 	at com.sun.ts.tests.javamail.ee.fetchprofile.fetchprofile_Test.setup(fetchprofile_Test.java:77)

If those two lines are moved from test2 to the cleanup() method instead, all of these problems go away.

**Comment by scottmarlow** [comment]
Hi @brideck I am assuming this is strictly a test improvement issue and is not a challenge.  Agreed?

**Comment by brideck** [comment]
Correct, not a challenge.  We have a way to get these tests to pass currently, we just shouldn't have to run them that way.

**Comment by gurunrao** [comment]
@brideck - I have made change for clean up resources here - https://github.com/gurunrao/jakartaee-tck/commit/d1953a8f4369dc865fb7cddb915c99b776308706
If the above changes are fine, I will raise a PR for the same.

**Comment by brideck** [comment]
@gurunrao Do those same lines need to be removed from test2?  Not sure if calling close on already closed resources of these types would throw any unnecessary conditions.

**Comment by scottmarlow** [comment]
I have seen some intermittent test2 test failures also.  Thanks for improving that test!

**Comment by gurunrao** [comment]
> @gurunrao Do those same lines need to be removed from test2? Not sure if calling close on already closed resources of these types would throw any unnecessary conditions.

Done. Have raised PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/613/files for fix.

**Comment by scottmarlow** [comment]
Closing since the pull request is merged!  Thanks @gurunrao for fixing this!  Thanks @brideck for reporting the issue!
