### ISSUE TITLE
Intermittent Failures in WebSocket getOpenSessions tests

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-tck#598]
In our Open Liberty testing, we experience a frequent intermittent failure in com/sun/ts/tests/websocket/spec/servercontainer/addendpoint/WSClient.java#getOpenSessionsTest

When it fails, it looks something like this:
```
[javatest.batch] open session=1
[javatest.batch] java.lang.StringIndexOutOfBoundsException: String index out of range: -198
[javatest.batch] 	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:935)
[javatest.batch] 	at java.lang.StringBuffer.substring(StringBuffer.java:480)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.addendpoint.WSClient.getOpenSessions(WSClient.java:1968)
[javatest.batch] 	at com.sun.ts.tests.websocket.spec.servercontainer.addendpoint.WSClient.getOpenSessionsTest(WSClient.java:1688)
[javatest.batch] ========TCKTestServer opened========session from Server is open=TRUE========TCKTestServer received String Message: testName=getOpenSessionsTest========getOpenSessions=1========TCKTestServer responded========TCKTestServer opened========session from Server is open=TRUE========TCKTestServer received String Message: testName=getOpenSessionsTest========getOpenSessions=2
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[javatest.batch] 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[javatest.batch] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[javatest.batch] 	at java.lang.reflect.Method.invoke(Method.java:498)
[javatest.batch] 01-06-2021 14:07:10:  ERROR: Incorrect response received
```

There appears to be a race between the code adding the last expected message of "========TCKTestServer responded" and the code in getOpenSessions that is reading those messages for verification.  It looks like CountDownLatches were added at some point to try to mitigate this, but not successfully.

I would propose that constructions in the test like this:
```
          messageLatch.countDown();
          receivedMessageString.append(message);
```

Need to be reordered to this instead, so the message will be appended prior to any attempt made to read by the awaiting thread:
```
          receivedMessageString.append(message);
          messageLatch.countDown();
```

There is a virtually identical test in com/sun/ts/tests/websocket/ee/jakarta/websocket/session/WSClient.java that already has the correct construction in place for each of its countDown() calls.  Accordingly, we never see this failure there.

**Comment by scottmarlow** [comment]
@markt-asf @joakime do you agree that the countDown() shouldn't be called until after the receivedMessageString is updated?

**Comment by markt-asf** [comment]
Yes, I agree all of the *Endpoint inner classes need to be updated so that in the various on[Open|Close|MessageError] methods countDown() must always be called after receivedMessageString has been updated. There are additional places where the same issue occurs (all in the WebSocket TCK). I'll put together a PR to address them all.

**Comment by scottmarlow** [comment]
Thank you for addressing this issue @markt-asf!  

Thank you for reporting this issue @brideck!
