### ISSUE TITLE
Old Java EE persistence namespace still there

### ISSUE THREAD

**Issue by jeanouii** [eclipse-ee4j/jakartaee-tck#609]
**Describe the bug**
The master branch of the TCK seems to still have the old Java EE namespace for persistence.xml files

**To Reproduce**
At the root of the repo, run the following command `find src -name "*.xml" |xargs grep "http://java.sun.com/xml/ns/persistence"`

**Expected behavior**
I would for the moment assume to not leave any old namespaces
If we want to still support old namespace for backward compatibility reasons which is a smart and relevant reason, we should create dedicated tests.

**Comment by jeanouii** [comment]
Running the command gives you 

```
$ find src -name "*.xml" |xargs grep "http://java.sun.com/xml/ns/persistence"
src/com/sun/ts/tests/ejb30/lite/tx/cm/common/persistence.xml:<persistence version="2.0" xmlns="http://java.sun.com/xml/ns/persistence">
src/com/sun/ts/tests/ejb30/assembly/appres/appclientejb/persistence.xml:<persistence xmlns="http://java.sun.com/xml/ns/persistence" version="1.0">
src/com/sun/ts/tests/ejb30/timer/basic/xa/persistence.xml:<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence">
src/com/sun/ts/tests/appclient/deploy/metadatacomplete/testapp/persistence.xml:<persistence xmlns="http://java.sun.com/xml/ns/persistence" version="1.0">
src/com/sun/ts/tests/ejb32/lite/timer/basic/xa/persistence.xml:<persistence version="1.0" xmlns="http://java.sun.com/xml/ns/persistence">
```

**Comment by scottmarlow** [comment]
change is merged, thanks @jeanouii

**Comment by arjantijms** [comment]
Thanks @jeanouii great find!

**Comment by scottmarlow** [comment]
Closing since the pull request is merged!
