### ISSUE TITLE
Java 11: JVM options for javac, wsImport, wsGen

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-tck#617]
While working through the optional webservices12 bucket in our efforts to bring up Open Liberty's TCK testing with Java 11, I ran into some problems with some of the JVM options provided for Java 9+.

----

The ts.javac task uses the jdk11.compiler.arg specified in ts.common.props.xml.

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/bin/xml/ts.common.props.xml#L452

Using it as-is results in this warning:

>  [ts.javac] warning: [options] module name in --add-exports option not found: java.xml.ws.annotation

It's not entirely clear to me if any of these options are strictly necessary, but that might depend on what jars are in each vendor's javaee.classes property.  (This gets pulled into ts.classpath via ts.run.classpath.)  For OL, I'm able to remove the jdk11.compiler.arg altogether and still have everything work for me.

----

The values specified for do.wsimport.jvmarg and do.wsgen.jvmarg appear to be incorrect in the Java 11 case.

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxws/common/xml/common.xml#L661
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxws/common/xml/common.xml#L769
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/jaxws/common/xml/common.xml#L879

Using them as-is results in failures like this:

>  [wsimport] Unrecognized option: -XaddExports:java.xml/com.sun.org.apache.xerces.internal.dom=ALL-UNNAMED,java.xml/com.sun.org.apache.xerces.internal.jaxp=ALL-UNNAMED,java.xml/com.sun.org.apache.xerces.internal.util=ALL-UNNAMED,java.xml/com.sun.org.apache.xml.internal.resolver=ALL-UNNAMED,java.xml/com.sun.org.apache.xml.internal.resolver.tools=ALL-UNNAMED,java.xml/com.sun.xml.internal.stream.writers=ALL-UNNAMED,java.base/sun.reflect.misc=ALL-UNNAMED
>  [wsimport] Error: Could not create the Java Virtual Machine.
>  [wsimport] Error: A fatal exception has occurred. Program will exit.
 
Again, I found that (at least for OL) nothing was needed here.  Removing this option completely allowed the wsgen/wsimport tools to run and the subsequent webservices12 tests passed.

----

Since these are all Ant properties, I'm able to run these targets and pass in -D parameters to override them with values that work for me, but we should probably make some updates to be more universally compatible.  As a start, some investigation with Glassfish needs to happen to see what the right answers are there.

**Comment by scottmarlow** [comment]
@alwin-joseph I think that some of the common/xml/common.xml properties linked above look vendor implementation specific.  Where should they be moved to?

**Comment by brideck** [comment]
@alwin-joseph @scottmarlow

It sure looks like Glassfish is failing with these same sorts of problems.
ex: https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-alw/job/RemoveJdk9SigTestDriver/11/testReport/junit/com.sun.ts.tests.signaturetest.jaxws/JAXWSSigTest/standalone_tck_run___jaxws___signatureTest_from_standalone/

**Comment by alwin-joseph** [comment]
> @alwin-joseph @scottmarlow
> 
> It sure looks like Glassfish is failing with these same sorts of problems.
> ex: https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-alw/job/RemoveJdk9SigTestDriver/11/testReport/junit/com.sun.ts.tests.signaturetest.jaxws/JAXWSSigTest/standalone_tck_run___jaxws___signatureTest_from_standalone/

I would like to try adding " -XX:+IgnoreUnrecognizedVMOptions  " for this.

**Comment by lukasj** [comment]
current property value definition is wrong and apparently has not been updated from JDK 9/10 to JDK 11. It uses JDK 9/10 stuff - ie there are no `java.xml.bind`, `java.annotation` etc modules available in JDK 11; there is also nothing like `-XaddExports` now (JDK 11 calls that `--add-exports`)

**Comment by gurunrao** [comment]
WIP PR - https://github.com/eclipse-ee4j/jakartaee-tck/pull/650

**Comment by scottmarlow** [comment]
I'll build the Platform TCK with this change for the next run
