### ISSUE TITLE
Java 11: IllegalStateException running Signature Tests

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-tck#618]
Attempting to run the signature tests with Java 11 results in the following error:

> [javatest.batch] 02-09-2021 13:50:27:  ERROR: Unexpected exception Unaccounted Tech Packages not implemented
> [javatest.batch] 02-09-2021 13:50:27:  ERROR: Test case throws exception: signatureTest failed with an unexpected exception
> [javatest.batch] 02-09-2021 13:50:27:  ERROR: Exception at:  
> [javatest.batch] 02-09-2021 13:50:27:  ERROR: java.lang.IllegalStateException: Unaccounted Tech Packages not implemented
> [javatest.batch] 	at com.sun.ts.tests.signaturetest.Jdk9SigTestDriver.executeSigTest(Jdk9SigTestDriver.java:202)
> [javatest.batch] 	at com.sun.ts.tests.signaturetest.SigTestEE.signatureTest(SigTestEE.java:246)
> [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> [javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
> [javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
> [javatest.batch] 	at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:41)
> [javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
> [javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
> [javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
> [javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
> [javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:37)
> [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> [javatest.batch] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> [javatest.batch] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> [javatest.batch] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> [javatest.batch] 	at com.ibm.ws.clientcontainer.internal.ClientRunnerImpl.run(ClientRunnerImpl.java:95)
> [javatest.batch] 	at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchClient(FrameworkManager.java:360)
> [javatest.batch] 	at com.ibm.ws.kernel.launch.internal.FrameworkManager.launchFramework(FrameworkManager.java:299)
> [javatest.batch] 	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.doFrameworkLaunch(LauncherDelegateImpl.java:114)
> [javatest.batch] 	at com.ibm.ws.kernel.launch.internal.LauncherDelegateImpl.launchFramework(LauncherDelegateImpl.java:100)
> [javatest.batch] 	at com.ibm.ws.kernel.boot.internal.KernelBootstrap.go(KernelBootstrap.java:214)
> [javatest.batch] 	at com.ibm.ws.appclient.boot.ClientLauncher.handleActions(ClientLauncher.java:64)
> [javatest.batch] 	at com.ibm.ws.kernel.boot.Launcher.createPlatform(Launcher.java:117)
> [javatest.batch] 	at com.ibm.ws.kernel.boot.cmdline.EnvCheck.main(EnvCheck.java:59)
> [javatest.batch] 	at com.ibm.ws.appclient.boot.cmdline.ClientEnvCheck.main(ClientEnvCheck.java:26)

Looking at the code, it looks like support for unaccountedTechPkgs (and classesUnderTest) was never implemented in Jdk9SigTestDriver.  I'm not sure if more needs to be done in this space than just copying over the similar code blocks from SignatureTestDriver, but I will be experimenting with that in the near future.

Unimplemented code blocks:
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/Jdk9SigTestDriver.java#L201
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/Jdk9SigTestDriver.java#L197

Potential donor code:
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/SignatureTestDriver.java#L354
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/SignatureTestDriver.java#L289

Note that there will be more work needed elsewhere to get the signature tests to actually pass with Java 11.  This issue is intended to focus on just getting all of the tests executing for now.

**Comment by scottmarlow** [comment]
Thanks for opening this @brideck!

CC @alwin-joseph

**Comment by scottmarlow** [comment]
We should at least change from:
```
    if (unaccountedTechPkgs != null) {
```
To:
```
    if (unaccountedTechPkgs != null && unaccountedTechPkgs.size() > 0) {
```
Since unaccountedTechPkgs is an empty list (not null) currently.

**Comment by scottmarlow** [comment]
Or remove the check and throw would be the other option.

**Comment by brideck** [comment]
I've verified that either of Scott's proposed changes are good enough to eliminate the error in the short term.

In doing so, I've also noticed that the loop that iterates through the different packages has been commented out in the Jdk9 driver class for some reason.
https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/signaturetest/Jdk9SigTestDriver.java#L138

**Comment by brideck** [comment]
I'm also not sure what this piece of output is supposed to mean:

> TestUtil.logMsg("Extracting jimage, it can take several minutes....");

From what I can see, the Jdk9 driver class isn't doing anything particularly different from the normal SigTest driver class here.

**Comment by alwin-joseph** [comment]
> I'm also not sure what this piece of output is supposed to mean:
> 
> > TestUtil.logMsg("Extracting jimage, it can take several minutes....");
> 
> From what I can see, the Jdk9 driver class isn't doing anything particularly different from the normal SigTest driver class here.

The  Jdk9 driver class adds two more parameters for the command passed 
https://github.com/eclipse-ee4j/jakartaee-tck/blob/18af3cfa4d09aa9ad9719850f32729c58063db3e/src/com/sun/ts/tests/signaturetest/Jdk9SigTestDriver.java#L114

This is for taking care of the java modules for jdk9+ . The same command is treated differently in the sigtest jars with and without these parameters.

**Comment by brideck** [comment]
Ah, well that's an interesting tidbit.  I can see that the jimage parameter is not being added to my command at all.

> [javatest.batch] 02-22-2021 19:33:31:  TRACE:    Param[9]: -Package
> [javatest.batch] 02-22-2021 19:33:31:  TRACE:    Param[10]: jakarta.mail.event
> [javatest.batch] 02-22-2021 19:33:31:  TRACE:    Param[11]: -ApiVersion
> [javatest.batch] 02-22-2021 19:33:31:  TRACE:    Param[12]: 2.0_se11
> [javatest.batch] 02-22-2021 19:33:31:  TRACE: ------------------ END SIG PARAM DUMP ------------------

Despite the comments protesting to the contrary, it must really be calling the createTestArguments method from the parent class?  I can't think of anything else that would explain that.  Gives me something to tinker with.

**Comment by brideck** [comment]
I fixed the issue from my last comment so that the -xjimage argument is being appended to the command, but... it doesn't seem to really do anything.

That's when I noticed this old issue: https://github.com/eclipse-ee4j/jakartaee-tck/issues/275

Per the advice there, I decided to run `jimage extract $JAVA_HOME/lib/modules` by hand ahead of time and then added the generated directories for java.base, java.rmi, java.sql, and java.naming to the sigTestClasspath in my ts.jte.  After that, I was able to run and pass the signature tests with Java 11 with no trouble.

Is there a reason that this can't/shouldn't be the approach that we use to run the signature tests for EE 9.1?  The Jdk9 driver class is unnecessarily complicating things by trying (and failing) to handle all of this itself.  If we go this route, I don't think the Jdk9SigTestDriver class is needed at all as it doesn't add anything useful and is currently broken with unimplemented functions.

If there's some way to actually make the -xjimage argument do what's promised in the comments that I'm somehow missing, I'm all for exploring that direction, too.

**Comment by alwin-joseph** [comment]
In https://github.com/eclipse-ee4j/jakartaee-tck/pull/619 the $JAVA_HOME/lib/modules was added to sigTestClasspath for platform & standalone TCKs. If the tests pass with this then that should be enough IMO. 
Can you mention which signature tests are you trying now. 

I see few of standalone TCKs and platform TCK use Jdk9SigTestDriver as the driver eg : https://github.com/eclipse-ee4j/jakartaee-tck/blob/1af09572461df6075178999b888da4204bcb3293/src/com/sun/ts/tests/signaturetest/el/ELSigTest.java#L117.
others like https://github.com/eclipse-ee4j/jakartaee-tck/blob/1af09572461df6075178999b888da4204bcb3293/src/com/sun/ts/tests/signaturetest/concurrency/CONCURRENCYSigTest.java#L124 uses common sigtest driver.

**Comment by brideck** [comment]
@alwin-joseph @scottmarlow 

I am running the full platform signature test (javaee/JavaEESigTest).  Using $JAVA_HOME/lib/modules on the classpath does not work and just results in the normal issues with being unable to load classes (java.lang.Object, etc.) for the Static tests.  I'm surprised you're not seeing the IllegalStateException in your runs.  If it's trying to use the Jdk9 driver class it should fail, unless you somehow have a null unaccountedTechPkgs.  Is there a public link to the logs/results from those runs?

Either way, I still think the Jdk9 driver class is not providing any benefit and could be safely removed.  The references in the various SigTest classes would likewise need to be removed, and they would just use the standard SigTestDriver classes instead.

**Comment by alwin-joseph** [comment]
> @alwin-joseph @scottmarlow
> 
> I am running the full platform signature test (javaee/JavaEESigTest). Using $JAVA_HOME/lib/modules on the classpath does not work and just results in the normal issues with being unable to load classes (java.lang.Object, etc.) for the Static tests. I'm surprised you're not seeing the IllegalStateException in your runs. If it's trying to use the Jdk9 driver class it should fail, unless you somehow have a null unaccountedTechPkgs. Is there a public link to the logs/results from those runs?
> 
> Either way, I still think the Jdk9 driver class is not providing any benefit and could be safely removed. The references in the various SigTest classes would likewise need to be removed, and they would just use the standard SigTestDriver classes instead.

Platform TCK sig tests : 
https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/14/ is the latest job that ran platform sig tests
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1242/ has the test run logs. Currently it says deployment errors in glassfish as we are running against latest gf bundle. I think we haven't reached the exception you are getting.  If you were able to get these tests passing without Jdk9 driver then that should be good enough.

Standalone tck tests : 
https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-build-run-910/5/ is the latest job that ran the standalone TCKs. 
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1243/ has the run logs. As per the result, some of the standalone TCK results have signature tests passing and some failing. 
https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/1243/pipeline. 
Some of the passing TCKs like EL-TCK uses Jdk9 driver and hence I think we can keep using them.

I agree if Jdk9 driver is not providing any benefit for any particular set of tests, they need not use them.

**Comment by brideck** [comment]
Thanks for those links, Alwin.

I agree that it looks like those Platform TCK runs haven't gotten to the point of running into the problems I've been documenting.

The standalone results are more interesting to me.  You can see the sigTestClasspath problems that I'm talking about here:
https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1243/testReport/junit/com.sun.ts.tests.signaturetest.caj/CAJSigTest/standalone_tck_run___caj___signatureTest/
> 
> Missing Superclasses or Superinterfaces
> ---------------------------------------
> 
> java.lang.annotation.Annotation:        jakarta.annotation.Generated

That run is using the JAVA_HOME/lib/modules entry that you spoke of in your last comment, so that corroborates that it is insufficient as a solution.

I can see from the output that the ELSigTest is indeed using the Jdk9 driver, but since it doesn't pass any arguments and is only testing one package it gets lucky and works okay.  Other classes like JSONPSigTest and JAXWSSigTest would find that only the first package in the list is getting tested.  You can see this phenomenon here: https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1243/nodes/76/steps/292/log/?start=0

Given all of the above, how do we proceed?  I would still advocate for removing the Jdk9 driver all together and amending all of the affected classes, which is easy enough to do.  Harder would be what to do about the sigTestClasspath in ts.jte.  My solution definitely works, but it requires (a) running the jimage tool before executing the tests and (b) setting sigTestClasspath to include locations relative to the destination of the jimage command.

We would probably need to make some sort of update to the sigTestClasspath section of https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/jakartaee/src/main/jbake/content/config.adoc to help users understand what's needed to run these successfully with Java 11.

**Comment by alwin-joseph** [comment]
> Thanks for those links, Alwin.
> 
> I agree that it looks like those Platform TCK runs haven't gotten to the point of running into the problems I've been documenting.
> 
> The standalone results are more interesting to me. You can see the sigTestClasspath problems that I'm talking about here:
> https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1243/testReport/junit/com.sun.ts.tests.signaturetest.caj/CAJSigTest/standalone_tck_run___caj___signatureTest/
> 
> > ## Missing Superclasses or Superinterfaces
> > java.lang.annotation.Annotation:        jakarta.annotation.Generated
> 
> That run is using the JAVA_HOME/lib/modules entry that you spoke of in your previous comment, so that corroborates that it is insufficient as a solution.
> 
> I can see from the output that the ELSigTest is indeed using the Jdk9 driver, but since it doesn't pass any arguments and is only testing one package it gets lucky and works okay. Other classes like JSONPSigTest and JAXWSSigTest would find that only the first package in the list is getting tested. You can see this phenomenon here in the JSONPSigTest results: https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1243/nodes/76/steps/292/log/?start=0
> 
> Given all of the above, how do we proceed? I would still advocate for removing the Jdk9 driver all together and amending all of the affected classes, which is easy enough to do. Harder would be what to do about the sigTestClasspath in ts.jte. My solution definitely works, but it requires (a) running the jimage tool before executing the tests and (b) setting sigTestClasspath to include locations relative to the destination of the jimage command.
> 
Yes this solution would work but apparently the jimage extract will cause more running time and space(within the container only for the CI). 
IMHO It would be great if we can get the Jdk9 driver working, if not we can fall back to this solution. 

> We would probably need to make some sort of update to the sigTestClasspath section of https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/jakartaee/src/main/jbake/content/config.adoc to help users understand what's needed to run these successfully with Java 11.

**Comment by brideck** [comment]
> Yes this solution would work but apparently the jimage extract will cause more running time and space(within the container only for the CI).

I can say from experience that it took about 10 seconds to run the jimage extract command the one time, so I'm not sure I completely buy the comments in the Jdk9 driver class.  I can understand the desire to not want to do it in every iteration of the package for loop, but doing it ahead of time once circumvents that entirely.

> IMHO It would be great if we can get the Jdk9 driver working...

The problem is that I have no idea what this means.  Does the -xjimage argument even work?  What is it supposed to do exactly?  How is the whole concept of passing a massive list of packages and running them all in a single iteration of the loop supposed to work?  There's barely the framework of a handful of thoughts in that class, and none of them are implemented.

**Comment by alwin-joseph** [comment]
> > Yes this solution would work but apparently the jimage extract will cause more running time and space(within the container only for the CI).
> 
> I can say from experience that it took about 10 seconds to run the jimage extract command the one time, so I'm not sure I completely buy the comments in the Jdk9 driver class. I can understand the desire to not want to do it in every iteration of the package for loop, but doing it ahead of time once circumvents that entirely.
> 
> > IMHO It would be great if we can get the Jdk9 driver working...
> 
> The problem is that I have no idea what this means. Does the -xjimage argument even work? What is it supposed to do exactly? How is the whole concept of passing a massive list of packages and running them all in a single iteration of the loop supposed to work? There's barely the framework of a handful of thoughts in that class, and none of them are implemented.
> 
> The two problems I raised around running jimage and updating the sigTestClasspath are pretty easily solved by any given user. I've already put an implementation into our Open Liberty automation that does this. I just don't know the right way to do it for the default/Glassfish version of the TCK.

If we are doing the same here, the sigTestClasspath in ts.jte.jdk11 for platform & standalone TCKs need to be appended the list of java module paths . Would it be better if the jimage extract happen within the sigtest source code so user does not need to explicitly do it ?

**Comment by brideck** [comment]
> Would it be better if the jimage extract happen within the sigtest source code so user does not need to explicitly do it ?

I can get behind this idea.  Not exactly sure how/where in the code to do it precisely...  I think we would need a new property in ts.jte (something like `jimage.destination`) to use both when invoking the jimage tool and to use in the sigTestClasspath value itself.

**Comment by brideck** [comment]
@alwin-joseph @scottmarlow 
I've got a prospective change pushed at #623 

It works for me, but could use some reviews and/or advice.  Please see the PR for details.

**Comment by brideck** [comment]
This issue is resolved for me in OL now that the above PR has been merged and built.  If Glassfish is seeing similar improvements in their latest runs, this can be closed out.

**Comment by scottmarlow** [comment]
@brideck looks like GlassFish is failing some signature tck tests:

https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1275/testReport/com.sun.ts.tests.signaturetest.javaee/JavaEESigTest/jakartaeetck_run___signaturetest_javaee___signatureTest_from_servlet has `Security constraints does not allow to read from signature file
java.security.AccessControlException: access denied ("java.lang.RuntimePermission" "accessClassInPackage.jdk.internal")` which seems to be a different problem than this issue is for.

Should we close this issue and open a GlassFish issue for resolving the security manager failures?  I'm asking in case anyone has a fix in mind already for this issue that might help with the security manager failure (seems unlikely but asking anyway).

**Comment by brideck** [comment]
Curious.  There are two things going on in those results.

The JImage invocation failed:
> 03-09-2021 04:12:12:  SVR: /opt/jdk-11.0.7/bin/jimage extract --dir=/root/jakartaeetck/bin/xml/../../tmp/jdk-bundles /opt/jdk-11.0.7/lib/modules
> 03-09-2021 04:12:12:  SVR: Exception while executing JImage!  Some tests may fail.

Looking in the JUnit report, I can see that the stack trace for this was also an ACE:
> java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/jdk-11.0.7/bin/jimage" "execute")
>  at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
>  at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
>  at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
>  at java.base/java.lang.SecurityManager.checkExec(SecurityManager.java:569)
>  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1096)
>  at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
>  at com.sun.ts.tests.signaturetest.SigTestEE.signatureTest(SigTestEE.java:260)
>  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>  at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>  at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>  at java.base/java.lang.reflect.Method.invoke(Method.java:566)
>  at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
>  at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
>  at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:41)

No JImage means that all of the STATIC mode tests are going to fail with missing stuff.

The error you cited happened in the REFLECTION mode tests, which are not affected at all by any of the changes covered in this issue/PR.

We didn't see either of these problems in the extensive pre-I testing for the PR, so it seems to be unique to how the execution of the platform sig tests with GF are handled.

**Comment by gurunrao** [comment]
> Curious. There are two things going on in those results.
> 
> The JImage invocation failed:
> 
> > 03-09-2021 04:12:12:  SVR: /opt/jdk-11.0.7/bin/jimage extract --dir=/root/jakartaeetck/bin/xml/../../tmp/jdk-bundles /opt/jdk-11.0.7/lib/modules
> > 03-09-2021 04:12:12:  SVR: Exception while executing JImage!  Some tests may fail.
> 
> Looking in the JUnit report, I can see that the stack trace for this was also an ACE:
> 
> > java.security.AccessControlException: access denied ("java.io.FilePermission" "/opt/jdk-11.0.7/bin/jimage" "execute")
> > at java.base/java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
> > at java.base/java.security.AccessController.checkPermission(AccessController.java:897)
> > at java.base/java.lang.SecurityManager.checkPermission(SecurityManager.java:322)
> > at java.base/java.lang.SecurityManager.checkExec(SecurityManager.java:569)
> > at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1096)
> > at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
> > at com.sun.ts.tests.signaturetest.SigTestEE.signatureTest(SigTestEE.java:260)
> > at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> > at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> > at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> > at java.base/java.lang.reflect.Method.invoke(Method.java:566)
> > at com.sun.ts.lib.harness.EETest.run(EETest.java:596)
> > at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:115)
> > at com.sun.ts.tests.common.vehicle.EmptyVehicleRunner.run(EmptyVehicleRunner.java:41)
> 
> No JImage means that all of the STATIC mode tests are going to fail with missing stuff.
> 
> The error you cited happened in the REFLECTION mode tests, which are not affected at all by any of the changes covered in this issue/PR.
> 
> We didn't see either of these problems in the extensive pre-I testing for the PR, so it seems to be unique to how the execution of the platform sig tests with GF are handled.

I have added additional permission for the failures, Pr - https://github.com/eclipse-ee4j/jakartaee-tck/pull/669
