### ISSUE TITLE
java.io.IOException: Server returned HTTP response code: 500 for URL (connector, concurrency tcks in jdk11)

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#629]
**Describe the bug**
We are facing below exception for connector & concurrency standalone TCKs when run in jdk11.
"java.io.IOException: Server returned HTTP response code: 500 for URL"

eg: 
[javatest.batch] 02-25-2021 07:48:34:  TRACE: wrote objects to the connectorservlet vehicle
[javatest.batch] java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8080/xa_workmgt_connectorservlet_vehicle_web/connectorservlet_vehicle
[javatest.batch] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1919)
[javatest.batch] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1515)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.connectorservlet.ConnectorVehicleRunner.runWebVehicleTest(ConnectorVehicleRunner.java:123)
[javatest.batch] 02-25-2021 07:48:34:  Test: returning from running in a connectorservlet vehicle
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.connectorservlet.ConnectorServletVehicleRunner.run(ConnectorServletVehicleRunner.java:29)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.connectorservlet.ConnectorVehicleRunner.run(ConnectorVehicleRunner.java:75)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:105)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.getPropsReady(EETest.java:486)
[javatest.batch] 	at com.sun.ts.lib.harness.ServiceEETest.run(ServiceEETest.java:209)
[javatest.batch] 	at com.sun.ts.lib.harness.EETest.run(EETest.java:285)
[javatest.batch] 	at com.sun.ts.tests.common.vehicle.VehicleClient.main(VehicleClient.java:37)

complete test run logs :
- https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1243/nodes/65/steps/297/log/?start=0
- https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1243/nodes/64/steps/276/log/?start=0

**To Reproduce**
1. Download TCKs 
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-concurrency-tck-2.0.0.zip
https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-connectors-tck-2.0.0.zip
2. Use scripts at docker/concurrencytck.sh & docker/connectortck.sh for running the TCKs
3. Use glassfish https://ci.eclipse.org/jakartaee-tck/job/build-glassfish/lastSuccessfulBuild/artifact/appserver/distributions/glassfish/target/glassfish.zip

**Additional context**

**Comment by gurunrao** [comment]
glassfish 6.1 is not loading classes with jars copied to "<glassfish_home>/glassfish/domains/domain1/lib/ext/" folder, which is causing failures with standalone tcks(concurrency, connector, jaxrs, jaxws, jms, jsonb, saaj, websocket).I am able to copy TCK jars to "<glassfish_home>/glassfish//domains/domain1/lib/" folder (https://github.com/gurunrao/jakartaee-tck/commit/1fb1c803d7614c5a8af808c6ddd7b60ab66e09b2) and many of the failures are not seen(For connector, concurency, websocket, SAAJ, JSONB,  JMS tck - there are 1 signature failure each, post changes. Run link can be found here - https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-guru/job/glassfish-ext-fix/4/#showFailuresLink).

Post glassfish-dev confirms that glassfish loading classes from <glassfish_home>/glassfish//domains/domain1/lib/ext/" folder needs to be fixed at glassfish, or TCKs scripts need to copy jars to "<glassfish_home>/glassfish//domains/domain1/lib/", I will raise a PR for fix.

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/634 has been merged to master.
CI https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-build-run-910/23/ run confirms fix.

- concurrency results archive - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-build-run-910/23/artifact/concurrency-tck-results.tar.gz

- connector results archive - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-standalonetck-build-run-910/23/artifact/connectors-tck-results.tar.gz
