### ISSUE TITLE
Bump standalone TCK versions for JakartaEE 9.1.0

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#633]
**Describe the bug**
The standalone TCKs need to have an appended version for JakartaEE 9.1.0

The platform TCK version is updated to 9.1.0 to match the platform spec.

Similarly the standalone TCK versions will need to be updated wrt the specifications. I presume the right version upgrade is to bump 0.0.1 for all tcks , eg jakarta-annotations-tck-2.0.1.zip . 
We already have new releases of TCKs eg Servelt 5.0.1 TCK .

Is there a single source of truth to get the right spec versions to match with TCKs ? If not we can look at the bundles at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ and append 0.0.1 for the current latest TCKs. 

@scottmarlow @gurunrao @RohitKumarJain

**Comment by scottmarlow** [comment]
> Is there a single source of truth to get the right spec versions to match with TCKs ?
The single source of truth is currently the version numbers used in https://github.com/eclipse-ee4j/jakartaee-tck/tree/9.0.x + master branches.  

We can also reference https://download.eclipse.org/jakartaee in addition to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted.

In summary, the Jakarta EE 9.0 + 9.1 SPEC API versions are exactly the same, therefore the TCKs will be based on those same SPEC API versions and we need to be careful that we don't reuse the same version (we should catch that mistake when actually doing the release to https://download.eclipse.org/jakartaee).

**Comment by RohitKumarJain** [comment]
@scottmarlow, In order to proceed further with the version upgrade for the standalone tck's, Could you please help us with the right spec version which needs to be updated? Looking forward to your inputs.

cc'ed: @gurunrao

**Comment by scottmarlow** [comment]
@RohitKumarJain IMO, we need a https://github.com/eclipse-ee4j/jakartaee-tck/wiki page that lists the standalone tck's links under grouping {EE 9, EE 9.1} so that we can know which EE version each TCK is for.  Something like the following assuming we just increment each TCK version number by 0.0.1:
```
Jakarta EE 9.0:
Servlet [jakarta-servlet-tck-5.0.0.zip](https://download.eclipse.org/jakartaee/servlet/5.0/jakarta-servlet-tck-5.0.0.zip), [jakarta-servlet-tck-5.0.1.zip](https://download.eclipse.org/jakartaee/servlet/5.0/jakarta-servlet-tck-5.0.1.zip), 

Jakarta EE 9.1:
Servlet [jakarta-servlet-tck-5.0.2.zip](https://download.eclipse.org/jakartaee/servlet/5.0/jakarta-servlet-tck-5.0.2.zip)
```

The above table will explain which Servlet 5.0 TCK version is for which EE release which otherwise wouldn't be known from the information in https://download.eclipse.org/jakartaee/servlet/5.0

If it is easier, we could start with only documenting the entries for `Jakarta EE 9.1` and assume that the other TCKs are respectfully for EE 9.0.

Thoughts?

**Comment by RohitKumarJain** [comment]
@scottmarlow, I'll be starting working on version upgrade for standalone tck's (with appending 0.1) while referring there current version present @ https://download.eclipse.org/jakartaee/.

Also, I'll create a wiki page that will contain information on the old version and a new version for individual standalone tck's.

cc'ed: @gurunrao

**Comment by RohitKumarJain** [comment]
@scottmarlow, I have raised PR for https://github.com/eclipse-ee4j/jakartaee-tck/pull/673 to address these changes. Once it gets merged and once new bundles available @ https://download.eclipse.org/jakartaee/ location, I'll be publishing the wiki for the same. (As you suggested wiki will contain information regarding the version information release wise.)

cc'ed: @gurunrao
