### ISSUE TITLE
How to handle new ts.jte.jdk11 for 9.1 ?

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#636]
**Describe the bug**
We have created new ts.jte.jdk11 file for convenience to run the tests in JDK11 for JakartaEE 9.1 release. 

This change need to be documented in the userguides to copy ts.jte.jdk11 to ts.jte. 

Other options :
-Rename ts.jte.jdk11 to ts.jte and rename current ts.jte to ts.jte.jdk8. This will require edits in current run scripts to remove copy ts.jte.jdk11 to ts.jte if jdk11
-Combine ts.jte.jdk11 & ts.jte to have the right configs for both jdk8 & jdk11 (ideal situation but complicated to implement as the there are difference in configs for several tcks)

**Additional context**

**Comment by gurunrao** [comment]
> **Describe the bug**
> We have created new ts.jte.jdk11 file for convenience to run the tests in JDK11 for JakartaEE 9.1 release.
> 
> This change need to be documented in the userguides to copy ts.jte.jdk11 to ts.jte.
> 
> Other options :
> -Rename ts.jte.jdk11 to ts.jte and rename current ts.jte to ts.jte.jdk8. This will require edits in current run scripts to remove copy ts.jte.jdk11 to ts.jte if jdk11
> -Combine ts.jte.jdk11 & ts.jte to have the right configs for both jdk8 & jdk11 (ideal situation but complicated to implement as the there are difference in configs for several tcks)
> 
> **Additional context**
> Add any other context about the problem here.

In 'Other Options' #2 is the best approach - since it helps in maintenance and avoids confusion for TCK users.
If thats too difficult to implement or if we cannot meet the release timeline with that approach, we can proceed with documentation in user-guides.

**Comment by scottmarlow** [comment]
1. JakartaEE 9.1 release is for both JDK8 + JDK11
2. The ts.jte* files are defaulting to the GlassFish settings but other implementations really need a base for their jdk8 settings + jdk11 settings.  

Another option could be rename ts.jte to ts.jte.jdk8 and document that ts.jte.jdk8 or ts.jte.jdk11 should be copied to ts.jte.  This might be clearer for the other implementations to understand the purpose of each file.

**Comment by alwin-joseph** [comment]
I will make the documentation change to mention that ts.jte.jdk11 needs to be copied as ts.jte for jdk11 runs.

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/712 fixes the issue.
