### ISSUE TITLE
JAXRS, Servlet, Webservices Platform TCK FULL Profile failures with GF 6.0 and JDK 8, GF 6.1 and JDK11

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/jakartaee-tck#653]
there are new JAXRS, Servlet, Webservices failures with GF 6.0 and JDK 8 CI run combination.
Details of the individual  test failures can be found here - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1281/testReport/junit/

- servlet junit report can be found here - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/25/artifact/results/junitreports/servlet-junit-report.xml

- webservices12 report can be found here - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/25/artifact/results/junitreports/webservices12-junit-report.xml

- jaxrs report can be found here - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/25/artifact/results/junitreports/jaxrs-junit-report.xml

**Comment by gurunrao** [comment]
We are seeing same tests failing with GF 6.1 + JDK 11 combo, details can be found at CI run - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/30/testReport/junit/

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/663 fixes the issue with JAXRS failure

**Comment by gurunrao** [comment]
CI run for JAXRS FULL Platform JDK 8 + GF 6 - https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck/job/master/1304/

**Comment by gurunrao** [comment]
Currently 1 Failures is present with FULL Platform JDK 8 + GF 6 run - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/40/testReport/

**Comment by hussainnm** [comment]
> Currently 1 Failures is present with FULL Platform JDK 8 + GF 6 run - https://ci.eclipse.org/jakartaee-tck/job/9.1/job/eftl-jakartaeetck-run-910/40/testReport/

This is fixed with #674
