### ISSUE TITLE
Review and promote Jakarta EL 4.0.1 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#685]
- [x] 1.  Complete userguide/documentation changes for Jakarta EL 4.0.1 TCK.
- [x] 2.  Review the jakarta-expression-language-tck-4.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-expression-language-tck-4.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (EL_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by markt-asf** [comment]
I've reviewed the staged 4.0.1 EL TCK and don't see any issues. I ran it against the latest Tomcat 10.0.x and all the tests pass.

**Comment by markt-asf** [comment]
FTR, I've only checked the PDF user guide very superficially. I didn't see any reason not to consider box 1 complete. From my PoV, box 2 is complete.

**Comment by arjantijms** [comment]
I checked GF 6.1.0-RC1, and it passed as well. Just as sanity check.
