### ISSUE TITLE
Review and promote Jakarta Restful-WS 3.0.2 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#688]
- [x] 1.  Complete userguide/documentation changes for Jakarta Restful-WS 3.0.2 TCK.
- [x] 2.  Review the jakarta-restful-ws-tck-3.0.2.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-restful-ws-tck-3.0.2.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (RESTFUL_WS_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by jansupol** [comment]
Should the tck bundle contain #616?

**Comment by scottmarlow** [comment]
I commented directly on #616 that testing with different implementations is needed for any further changes made.

**Comment by jansupol** [comment]
Maybe pedant notes for the TCK `docs/JAXRSTCK3.0-ReleaseNotes.html`:
- Section `Platform Notes`: JDK 11 support is not mentioned. 
> The Jakarta EE RESTful Web Services 3.0 TCK tests and the Jakarta EE RESTful Web Services 3.0 Compatible Implementation (CI) can be run with Java Platform, Standard Edition version 8.0 (Java SE 8)` 

should continue with or `Java Platform, Standard Edition version 11.0 (Java SE 11)`.

- Section `Compatible Runtime for Jakarta EE RESTful Web Services 3.0`: 
> Java SE 8 or Java SE 11 which must be used with a Jakarta EE profile/application server, such as the GlassFish 6.0 or 6.1

Should GF 6.0 be mentioned for Jakarta EE 9.1 at all? If so, Java SE 11 does not work with GF 6.0 and it should better be: Java SE 8 which must be used with a Jakarta EE profile/application server, such as the GlassFish 6.0 or 6.1, or Java SE 11 which must be used with a Jakarta EE 9.1 profile/application server such as the GlassFish 6.1.

**Comment by jansupol** [comment]
Another notes for the user guide:
- Section 4.1.2.5: `jaxrs_impl.`classes (should be `jaxrs_impl.classes`): 
   -  `${web.home}/modules/jakarta.inject.jar` should be `${web.home}/modules/jakarta.inject-api.jar`
   - `${web.home}/modules/endorsed/jakarta.annotation-api.jar` should be `${web.home}/modules/jakarta.annotation-api.jar` (GF 6.1)
   Other jars are missing:
  - `${web.home}/modules/jakarta.xml.bind-api.jar:${web.home}/modules/jaxb-osgi.jar` for JAX-B related tests (optional?)
  - `${web.home}/modules/jakarta.activation.jar` for activation DataSource related tests (mandatory)
  - `${web.home}/modules/javassist.jar` for bug https://github.com/eclipse-ee4j/glassfish/issues/23122
- Section 4.1.2.13: The passwords are set by config.vi, the passwords section should be moved to list in Section 4.1.6
- Section 4.2.1.1: JDK 11 should be mentioned similarly to 4.1.1.1
- Section 4.2.2.5, same as 4.1.2.5
- Appendix B: Jersey 1 class is mentioned:
  -  A Eclipse Jersey 3.0-specific deployment descriptor also comes with the Jakarta REST TCK, and has the values for the `com.sun.jersey.spi.container.servlet.ServletContainer` should replace ServletContainer with `org.glassfish.jersey.servlet.ServletContainer.class`

**Comment by edbratt** [comment]
@jansupol Thank you for your detailed review. This is really helpful.
Could you submit a PR with the proposed changes. 

- User Guide section 4.1 - 4.3 are written in [config.inc](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/jaxrs/src/main/jbake/content/config.inc)
- User Guide Appendix B is written in [rebuild.inc](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/jaxrs/src/main/jbake/content/rebuild.inc)
- Jakarta REST Release TCK Notes are in [JAXRSTCK3.0-ReleaseNotes.html](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/install/jaxrs/docs/JAXRSTCK3.0-ReleaseNotes.html)

GlassFish 6.0 is tested and known to pass the 3.0.2 TCK with Java 8. GlassFish 6.1 passes the TCK with Java 11. As I understand it, GF 6 won't run on JDK 11 and GlassFish 6.1 won't run on JDK 8. I was relying on the GlassFish user to know which runs, on which JDK. Please correct the language to suit. If you would prefer to list Eclipse Jersey instead and it passes for both JDK 8 and 11, that would be fine also.

**Comment by jansupol** [comment]
Sure, I will create the PR before Friday.
