### ISSUE TITLE
Review and promote Jakarta Pages 3.0.1 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#691]
- [x] 1.  Complete userguide/documentation changes for Jakarta Pages 3.0.1 TCK.
- [x] 2.  Review the jakarta-pages-tck-3.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-pages-tck-3.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (PAGES_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by markt-asf** [comment]
Tomcat 10.0.x passes the staged 3.0.1 TCK without any issues. LGTM.

**Comment by edbratt** [comment]
@markt-asf May we consider check-box items 1 and 2 (above) completed then?

**Comment by markt-asf** [comment]
I've only checked the PDF user guide very superficially. I didn't see any reason not to consider box 1 complete. From my PoV, box 2 is complete.

**Comment by edbratt** [comment]
Thank you for your review. I've checked the first to boxes and note that this TCK is ready to promote.
