### ISSUE TITLE
Review and promote Jakarta Persistence 3.0.1 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#692]
- [x] 1.  Complete userguide/documentation changes for Jakarta Persistence 3.0.1 TCK.
- [x] 2.  Review the jakarta-persistence-tck-3.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-persistence-tck-3.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (PERSISTENCE_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by rfelcman** [comment]
Hello,
   I verified points 1. 2.
In case of point No 1. I discovered small mistake in userguide. I created PR #715 to fix it.
Point No 2. is OK

What I can't do due a missing permissions are steps 3. and 4.
Could You please do it?

**Comment by gurunrao** [comment]
> Hello,
> I verified points 1. 2.
> In case of point No 1. I discovered small mistake in userguide. I created PR #715 to fix it.
> Point No 2. is OK
> 
> What I can't do due a missing permissions are steps 3. and 4.
> Could You please do it?

@rfelcman  - Please mark points 1 & 2 complete(in the issue description here - https://github.com/eclipse-ee4j/jakartaee-tck/issues/692#issue-848343630), we will promote the bundle and complete certification.

**Comment by rfelcman** [comment]
Sorry but,
Please mark points 1 & 2 complete doesn't work to me. If You mean just click to the checkbox fields I tried it, but nothing happens. Maybe something wrong with permissions.
Is it following response enough?

- [x]  1. Complete userguide/documentation changes for Jakarta Persistence 3.0.1 TCK.

- [x] 2. Review the jakarta-persistence-tck-3.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.

**Comment by gurunrao** [comment]
> Sorry but,
> Please mark points 1 & 2 complete doesn't work to me. If You mean just click to the checkbox fields I tried it, but nothing happens. Maybe something wrong with permissions.
> Is it following response enough?
> 
> * [x]   1. Complete userguide/documentation changes for Jakarta Persistence 3.0.1 TCK.
> * [x]  2. Review the jakarta-persistence-tck-3.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.

Thanks for review, response is sufficient, We will start on step 3 &4.

**Comment by edbratt** [comment]
@rfelcman I think only project committers can edit the description -- and then, only if the filer has allowed other committers to edit. I believe that the latter is allowed, but the former prevented you from updating the checklist. All good now. Thank you for your review.
