### ISSUE TITLE
Review and promote Jakarta JSONB 2.0.1 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#694]
- [x] 1.  Complete userguide/documentation changes for Jakarta JSONB 2.0.1 TCK.
- [x] 2.  Review the jakarta-jsonb-tck-2.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-jsonb-tck-2.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (JSONB_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by Verdent** [comment]
* In chapters 4.1 and 4.2 is not Java 11 explicitly mentioned.
> JAVA_HOME to the directory in which Java SE 8 is installed

* In both previously mentioned chapters is also incorrect example of jsonb.classes property
> For example, if you were using the Jakarta JSON Binding 2.0 RI, you would set this property to jsonb.classes=jakarta.json.bind-{TechnologyVersion}.jar.

This is not how JSONB-API RI is called. Should this be changed for example like this?
> For example, if you were using the Jakarta JSON Binding 2.0 RI, you would set this property to jsonb.classes=yasson-{TechnologyVersion}.jar.

Also in case of jsonb.classes, it is a bit misleading and not explicitely mentioned, that there should not be the path only to the implementation, but also to all of its dependencies.

**Comment by Verdent** [comment]
I was also capable to set up and pass all of the TCK tests on JDK 8 and also 11, using this user guide.

**Comment by Verdent** [comment]
Hi @gurunrao , could you please mark 1. and also probably 2. as done please?

The PR with changes is merged but I as far as I could see, there was no release since that so I am not sure if I should wait for that to verify that the changes we successful or not :-) Other then that, I am the one who should also do 3. and 4.?

**Comment by gurunrao** [comment]
> Hi @gurunrao , could you please mark 1. and also probably 2. as done please?
> 
> The PR with changes is merged but I as far as I could see, there was no release since that, so I am not sure if I should wait for that to verify the changes were successful or not :-) (That's why I am not sure about marking 2. also) Other then that, I am the one who should also do 3. and 4.?
Sorry @Verdent - I have triggered the build, will take ~5 hrs to complete.

**Comment by edbratt** [comment]
Once the build is completed, this should be ready to promote. I've check items 1 and 2 from the list.
