### ISSUE TITLE
Review and promote Jakarta JSONP 2.0.1  TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#695]
- [x] 1.  Complete userguide/documentation changes for Jakarta JSONP 2.0.1 TCK.
- [x] 2.  Review the jakarta-jsonp-tck-2.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-jsonp-tck-2.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (JSONP_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by aserkes** [comment]
Points 3 and 4 cannot be done by me because I am not a TCK committer.

**Comment by edbratt** [comment]
#719 is merged. Once the kit is rebuilt, this is ready for promotion.
