### ISSUE TITLE
Review and promote Jakarta Tags 2.0.1 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#696]
- [x] 1.  Complete userguide/documentation changes for Jakarta Tags 2.0.1 TCK.
- [x] 2.  Review the jakarta-tags-tck-2.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-tags-tck-2.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (TAGS_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by gurunrao** [comment]
`-Djava.locale.providers=COMPAT` needs to be added to documentation, further details can be found in issue https://github.com/eclipse-ee4j/jakartaee-tck/issues/631

**Comment by gurunrao** [comment]
PR for COMPAT option documentation - https://github.com/eclipse-ee4j/jakartaee-tck/pull/714

**Comment by pnicolucci** [comment]
Hi, are the only changes that I need to review here the comments above about the JVM option `-Djava.locale.providers=COMPAT` and the documentation update?

**Comment by pnicolucci** [comment]
If the above is true then I'm fine with these changes for the Jakarta Tags TCK updates for the JakartaEE 9.1 release.

**Comment by scottmarlow** [comment]
> Hi, are the only changes that I need to review here the comments above about the JVM option `-Djava.locale.providers=COMPAT` and the documentation update?

@pnicolucci I opened https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/jstl which shows that the only userguide modfication was describing `-Djava.locale.providers=COMPAT` for JDK11.

**Comment by pnicolucci** [comment]
Looks good to me!
