### ISSUE TITLE
Review and promote Jakarta Servlet 5.0.2 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#698]
- [x] 1.  Complete userguide/documentation changes for Jakarta Servlet 5.0.2 TCK.
- [x] 2.  Review the jakarta-servlet-tck-5.0.2.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-servlet-tck-5.0.2.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [x] 4.  Remove the boolean parameter (SERVLET_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by markt-asf** [comment]
I may have found an issue here. I am still investigating. I'm seeing a failure of the signature test with Tomcat 10.0.x and Java 11. I'm not sure of the root cause at this point. I'll update the issue when I have more information.

**Comment by markt-asf** [comment]
User error on my part. I had a typo in the class path for the signature tests. Sorry for the noise.

Tomcat 10.0.x passes the staged 5.0.2 TCK with on expected failure (Tomcat always overrides any configured default context path so that test fails).
I've only checked the PDF user guide very superficially. I didn't see any reason not to consider box 1 complete. From my PoV, box 2 is complete.

**Comment by edbratt** [comment]
Thanks for the feedback. Once the final build is completed, this is ready to promote. I've checked the first two items on the list.

**Comment by olamy** [comment]
Tested with Jetty 11 and all test are passing.
