### ISSUE TITLE
Review and promote Jakarta Websocket 2.0.1 TCK for JakartaEE 9.1 release

### ISSUE THREAD

**Issue by RohitKumarJain** [eclipse-ee4j/jakartaee-tck#701]
- [x] 1.  Complete userguide/documentation changes for Jakarta Websocket 2.0.1 TCK.
- [x] 2.  Review the jakarta-websocket-tck-2.0.1.zip bundle at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/ (or at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9/nightly-910/) to look for any changes missed to be included in JakartaEE 9.1 release.
- [x] 3.  Promote the bundle https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-910/jakarta-websocket-tck-2.0.1.zip to https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/promoted/ by using the job https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/.
- [ ] 4.  Remove the boolean parameter (WEBSOCKET_TCK) and comment out the respective wget + if condition in https://ci.eclipse.org/jakartaee-tck/job/9.1/job/promote_jakartaee9.1_eftl_bundles/configure so that the same bundle is not promoted again.

**Comment by joakime** [comment]
Why was there a bump in the version to 2.0.1? 
There's no correlated websocket-api release 2.0.1.

**Comment by edbratt** [comment]
The TCK needed to be revised to run on JDK 11 (Signature tests). The 
Spec. is not changed. So, Spec. is same. TCK is micro-revised.

**Comment by joakime** [comment]
Ah.
Thanks.

**Comment by markt-asf** [comment]
The TCK runs and passes with the latest Tomcat 10.0.x so looks good to me.

**Comment by edbratt** [comment]
@markt-asf would it be correct, as you are concerned then, that we may count the top two check-boxes in this issue completed?

**Comment by markt-asf** [comment]
I've only checked the PDF user guide very superficially. I didn't see any reason not to consider box 1 complete. From my PoV, box 2 is complete.

**Comment by jansupol** [comment]
The following could be updated:
- websocket-tck/docs/index.html has 2 links to PDF documentation, and it does not lead to an HTML user guide (under the link The Jakarta EE WebSocket Technology Compatibility Kit, Version 2.0 User's Guide).
- Section 4.1.2.5 is missing `${web.home}/modules/tyrus-container-grizzly-client.jar`
- Section 4.1 does not instruct to execute `ant config.vi` which sets policies and users
- Section 4.2 is missing almost completely (the steps for vendors implementation)

**Comment by edbratt** [comment]
I've corrected the first point. Could you submit a PR to address the user guide points you've raised? The relevant file should be [config.inc](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/user_guides/websocket/src/main/jbake/content/config.inc)

**Comment by edbratt** [comment]
Based on #727 being merged, I will presume we can now promote this TCK, once it is rebuilt. Thank you.
