### ISSUE TITLE
tests removed due to CORBA references should be documented in UG

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/jakartaee-tck#728]
We need to document tests removed due to CORBA references, documentation should be added to Platform TCK Userguide.

ejb/bb tests removed(in 9.1) due to CORBA references are:

- appclientInjectionCompleteInPostConstruct (package -com.sun.ts.tests.ejb30.bb.session.stateless.callback.method.descriptor.Client)

- appclientInjectionCompleteInPostConstruct (package - com.sun.ts.tests.ejb30.bb.session.stateless.callback.method.annotated.Client)

- isInterceptorInjectionDoneForSingleDefaultInterceptorJar (package -com.sun.ts.tests.ejb30.bb.session.stateless.callback.defaultinterceptor.descriptor.Client)

- isInterceptorInjectionDoneForCallbackBean2 (package - com.sun.ts.tests.ejb30.bb.session.stateless.callback.defaultinterceptor.descriptor.Client)

- isInterceptorInjectionDoneForCallbackBean1 (package -com.sun.ts.tests.ejb30.bb.session.stateless.callback.defaultinterceptor.descriptor.Client)

- orbTest (package -com.sun.ts.tests.ejb30.bb.session.stateless.annotation.resource.Client)

- clientOrbTest (package -com.sun.ts.tests.ejb30.bb.session.stateless.annotation.resource.Client)

PR for removal of CORBA reference - https://github.com/eclipse-ee4j/jakartaee-tck/pull/651
JDK 11 doesn't support CORBA, hence reference to CORBA were removed(along with dependant tests).

**Comment by scottmarlow** [comment]
My preference is to start a wiki page for `Jakarta EE 9.1 User Guide` that contains extra details such as ^ about tests removed due to CORBA refererences for this issue.  Thanks @gurunrao for raising this issue.

**Comment by scottmarlow** [comment]
@gurunrao please review https://github.com/eclipse-ee4j/jakartaee-tck/wiki/Jakarta-EE-9.1-TCK-User-Guide-addendum and improve if you like or comment here on what you would like to see changed.

Thanks!

**Comment by gurunrao** [comment]
Thanks for wiki @scottmarlow. We can additionally document that tests will not run for JDK 8 too(since users should not expect these test to run when 9.1 TCK is run against JDK 8).
