### ISSUE TITLE
Remove set.ext.dirs for Jakarta EE 10+ / JDK 11

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#733]
With Jakarta EE 10 supporting JDK 11 as a minimal, it's probably time to let go of the "set.ext.dirs" targets.

These are mainly used in https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/bin/xml/impl/glassfish/s1as.xml

**Comment by scottmarlow** [comment]
As mentioned on the https://twitter.com/scottmarlow/status/1499396910020366339 thread, I'll take a look at making the change for this.
