### ISSUE TITLE
Use the standard HttpClient instead of the incubator version

### ISSUE THREAD

**Issue by Thihup** [eclipse-ee4j/jakartaee-tck#736]
**Is your feature request related to a problem? Please describe.**
The Servlet TCK uses the incubator version of the Http Client, that became available in JDK 11.

**Describe the solution you'd like**
Use the standard Http Client instead of relying on an old implementation, and requiring tweaks to work in the current version.

**Describe alternatives you've considered**
Add `--add-exports java.base/sun.net=ALL-UNNAMED`

**Additional context**
Running the Incubator HttpClient with JDK 16 throws the following exception:
```
ERROR: java.lang.IllegalAccessError: class jdk.incubator.http.internal.common.Utils (in unnamed module @0x2064d52f) cannot access class sun.net.NetProperties (in module java.base) because module java.base does not export sun.net to unnamed module @0x2064d52f
``` 

https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/spec/serverpush/README.md

**Comment by Thihup** [comment]
This JEP keeps track of the changes between the incubator and the final release: https://openjdk.java.net/jeps/321

**Comment by scottmarlow** [comment]
@Thihup is the appropriate action to take for EE 10 to remove the incubator [lib/http.jar](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/lib/http.jar) and [switch to use the `java.net.http` package instead](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/servlet/spec/serverpush/Client.java#L25)?

**Comment by Thihup** [comment]
@scottmarlow I think so. Currently, we have all the server push tests failing related to the exception that happens (IllegalAccessError) because we're using JDK 17 to run the Servlet TCK.
I don't remember if the scope of Jakarta EE 10 is to only enable implementations to certify with JDK 11. If the scope is to allow with JDK 17 too, these tests may need some look.

**Comment by arjantijms** [comment]
@Thihup It was stated that certification with both the current version (JDK 17) and the previous (JDK 11) should be possible. 

So yes, JDK 17 is surely in scope. We had the vote for the minimum version perhaps a little too early. Perhaps if we had the vote again, JDK 17 would be the minimum instead.
