### ISSUE TITLE
Compile TCKs at the Java SE 11 level

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#740]
This issue will be addressed after the Platform TCK CI can build the Standalone/Platform TCKs with Java SE 11.

The EE 10 build jobs should be located inside of https://ci.eclipse.org/jakartaee-tck/job/10/

**Comment by gurunrao** [comment]
> @gurunrao is this issue ready to be closed?

I am closing the issue, since PR has been merged.
