### ISSUE TITLE
[soap30] remove tests covering JAXM

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#747]
`jakarta.xml.soap. SOAPConnection.call()` no longer requires supporting `javax.xml.messaging.URLEndpoint`, tests should be removed, see https://github.com/eclipse-ee4j/saaj-api/issues/104

**Comment by gurunrao** [comment]
There is single documentation reference of javax.xml.messaging.URLEndpoint at jakartaee-tck repository.

`$egrep -R "javax.xml.messaging.URLEndpoint" .
./internal/docs/saaj/saaj-api.xml:                                <comment>an Object that identifies          where the message should be sent. It is required to          support Objects of type          java.lang.String,          java.net.URL, and when JAXM is present          javax.xml.messaging.URLEndpoint</comment>
`

**Comment by scottmarlow** [comment]
Closing as the linked pull request is merged.
