### ISSUE TITLE
[xmlws40] merge jws tests into jaxws

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#748]
with xmlws 4.0, ws metadata is part of it. Should there be tests for ws metadata, they need to be merged into xmlws; should there be references to jws-api jar, they should be removed as the content is now part of xml.ws-api jar; see https://github.com/eclipse-ee4j/jax-ws-api/issues/169

**Comment by gurunrao** [comment]
Found one reference of jakarta.jws-api.jar at  jakartaee-tck/user_guides/jaxws/src/main/jbake/content/config.adoc [documentation update needs to be done]

**Comment by gurunrao** [comment]
@lukasj  - We are facing 4 jws test failure [ https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-build-run/job/jaxws-jws-tck/12/testReport)/ ]  with:
`java.lang.IllegalArgumentException: com.sun.ts.tests.jws.oneway.server.OnewayWebService is not an interface" error`. 
Further details of error can be found at https://ci.eclipse.org/jakartaee-tck/job/guru/job/jakartaee-tck-build-run/job/jaxws-jws-tck/12/testReport/junit/com.sun.ts.tests.jws.oneway.client/Client/testPingRPC_from_standalone/

Shall we make https://github.com/eclipse-ee4j/jakartaee-tck/blob/da6a34066dd04a78e6b1656c923c9c5de97af182/src/com/sun/ts/tests/jws/oneway/server/OnewayWebService.java#L30 an abstract class?
