### ISSUE TITLE
[Add a TCK Contributor to TRIAGE TCK Repo]  Request

### ISSUE THREAD

**Issue by aeiras** [eclipse-ee4j/jakartaee-tck#768]
Hola @scottmarlow, 

Can you please add me to this repo via Triage feature add? 
Please see https://github.com/microprofile/microprofile-wg/wiki/Contributors-GitHub-“Triage”-access  to learn how. 

Thank you,

**Comment by scottmarlow** [comment]
Hola @aeiras,

Thanks, I was not aware of the `triage` role, very interesting!

For general background, I copied a list of what `triage` contributors can do below. Thanks for kicking off the process to consider the `triage` role for Jakarta EE projects as well!  

From https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization, contributors with `triage` can:
- Apply/dismiss labels
- Close, reopen, and assign all issues and pull requests
- Apply milestones
- Mark duplicate issues and pull requests
- Request pull request reviews
- Lock and unlock discussions
- Individually convert issues to discussions

**Comment by scottmarlow** [comment]
@aeiras would the jakarta.ee-wg@eclipse.org mailing list be the right place to ask if the `triage` role is approved for Jakarta EE projects and what the process for assigning someone to that role is.  Perhaps following the same process as the MicroProfile Working Group.

**Comment by aeiras** [comment]
Correct about using the WG forum Scott. 
Ed sent the original draft of the MPWG documentation to the WG forums a long time ago. 

I also sent to the WG the Call to Action to start the Triage Contributor access consideration on Oct 27th https://www.eclipse.org/lists/jakarta.ee-wg/msg00761.html. There are no follow-ups yet. 

You can choose to own the follow-up via Ed's thread, my thread, or a new thread, Scott. 
Pick your method and see you there!

**Comment by edbratt** [comment]
Triage access is available to all Eclipse projects -- it enables additional functionality at GitHub. There should be nothing to request of the Eclipse Web Admins.
So far as I know, designation of a Triage user is at the discretion of the project committer team.

**Comment by aeiras** [comment]
@edbratt, 

Today the documentation we wrote got really good feedback from Scott S on using the Triage guidelines.  I have updated the wiki section to clarify stuff "Contributors Obtaining Triage Access in MPWG" with a direct copy/paste of your explanation above. You are amazing, Ed!

**Comment by scottmarlow** [comment]
We discussed the idea of adding contributors in the fourth TCK call yesterday and no one was against the idea.  I look forward to @aeiras continuing to contribute to the Platform TCK project and now as `Triage user`!

**Comment by aeiras** [comment]
Thank you for the trust, lets continue the fun! :)
