### ISSUE TITLE
[Website Correction]  Wrong name

### ISSUE THREAD

**Issue by aeiras** [eclipse-ee4j/jakartaee-tck#769]
Please remove Eclipse from Jakarta EE TCK. 

https://projects.eclipse.org/projects/ee4j.jakartaee-tck/governance

I am not a committer so I cannot adjust the error. Thanks! 

![image](https://user-images.githubusercontent.com/10731224/141355182-f9c3b947-7a26-4de3-b6aa-3f182b51d760.png)

**Comment by scottmarlow** [comment]
Just to be clear, the requested change does not change the actual meaning of scope of the project, so IMO, a restructuring review is not required. If it were, I would need to contact our PMC/EMO.

**Comment by scottmarlow** [comment]
Completed, thanks @aeiras

**Comment by aeiras** [comment]
Hola Scott, 

I don't understand you. 
Do you mean, you cannot drop the Eclipse from the Jakarta paid trademark?

Not doing so directly violates the Jakarta EE filed and Registered marks. There is nothing to discussed with the PMC & EMO. I filed a budzilla exactly about the error on adding the Eclipse on the project's name last year. It was resolved and even discussed in the steering cmtee. 

Thank you for allowing this follow up,

**Comment by scottmarlow** [comment]
Hola Amelia,

Sorry to not be clear, I should of mentioned that I made the requested change.  My comment was just a note to myself or others that might be curious as to why I just changed the wording without contacting PMC/EMO.  I think that I can make the change you requested as I didn't change the actual meaning of the scope of the project.

All good, thanks!

**Comment by aeiras** [comment]
Gotcha, Scott. 

Thank you so much for explaining. I understand you. 

 If you wish, I could provide documentation on this as well. It deals with infringing the project Trademark, it is that simple. :)  Now, I understand why you closed the ticket.  Super fun stuff!
