### ISSUE TITLE
Mail samples tests should not be run for javaee_webprofile

### ISSUE THREAD

**Issue by brideck** [eclipse-ee4j/jakartaee-tck#791]
Jakarta Mail is not a required component of the [WebProfile specification](https://jakarta.ee/specifications/webprofile/9.1/jakarta-webprofile-spec-9.1.html#a43), so the tests in `samples/javamail` should not be run when the `javaee_webprofile` keyword is specified.

The keywords should be updated to match the ones used for the `javamail` bucket which uses `javaee_webprofile_optional` instead.

**Comment by gurunrao** [comment]
@brideck - thanks for raising the issue, Please feel free to raise a PR with modification to https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/harness/keyword.properties

**Comment by scottmarlow** [comment]
I agree with @gurunrao.  This has likely been ignored in the past due to the `samples` just being an optional way to verify that a TCK installation works at all.  :+1:  for fixing it!

**Comment by brideck** [comment]
@scottmarlow @gurunrao I was trying to test my change locally, and it didn't seem sufficient to just update the keyword.properties file in my install.  Do changes to that file require a rebuild of some sort in order to be honored in a test run?

**Comment by scottmarlow** [comment]
@brideck what change did you make to your keyword.properties?

**Comment by brideck** [comment]
@scottmarlow Linked a PR with the change.  It's dead simple, but I've also had trouble in the past when tinkering with this file to get everything to work the way it feels like it should.

**Comment by scottmarlow** [comment]
I'm not sure from reading the https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/lib/util/ConfigUtil.java#L85 source that deals with loading the keyword.properties.  

If you push your branch to github, myself (via https://ci.eclipse.org/jakartaee-tck/job/jakartaee-tck-scottmarlow) or @gurunrao  or @alwin-joseph can build your branch for you.  Once the TCK is built, then you can download it and run it.

**Comment by scottmarlow** [comment]
@brideck the TCK is building still, takes a while.

Are you specifying !javamail when running the samples?

I think it would be something like the following with your keyword.properties change:
```
ant -Dkeywords="\!javamail" runclient
```

**Comment by brideck** [comment]
I'm specifying javaee_web_profile in a run and expecting that the samples/javamail subset will not be run as part of that after making the updates for this issue.  I would not think that I need to explicitly gate on a javamail-related keyword if everything is set up correctly.

Running samples with the javaee_web_profile keyword specified currently only excludes the samples/ejb tests.

**Comment by brideck** [comment]
Thanks for the build, @scottmarlow .  I tried it out and it ran the expected tests for me (just the jdbc sample), so rebuilding must incorporate the contents of keyword.properties somewhere that I'm not able to find.

**Comment by scottmarlow** [comment]
Closing as the linked pull request is merged.  Please reopen if needed.
