### ISSUE TITLE
jacc standalone TCK build failure with 2.1.0-RC1 jacc API jar

### ISSUE THREAD

**Issue by gurunrao** [eclipse-ee4j/jakartaee-tck#795]
jacc standalone TCK build fails with 2.1.0-RC1 jacc API jar:
`
tslib.compile:
 [ts.javac] Compiling 12 source files to /home/guru/oracle/jakartaee-tck/classes
 [ts.javac] /home/guru/oracle/jakartaee-tck/src/com/sun/ts/tests/jacc/provider/TSPolicy.java:225: warning: [deprecation] newInstance() in Class has been deprecated
 [ts.javac]         Object obj = (Object) clazz.newInstance();
 [ts.javac]                                    ^
 [ts.javac]   where T is a type-variable:
 [ts.javac]     T extends Object declared in class Class
 [ts.javac] /home/guru/oracle/jakartaee-tck/src/com/sun/ts/tests/jacc/provider/TSPolicyConfigurationFactoryImpl.java:38: error: TSPolicyConfigurationFactoryImpl is not abstract and does not override abstract method getPolicyConfiguration() in PolicyConfigurationFactory
 [ts.javac] public class TSPolicyConfigurationFactoryImpl
 [ts.javac]        ^
 [ts.javac] /home/guru/oracle/jakartaee-tck/src/com/sun/ts/tests/jacc/provider/TSPolicyConfigurationFactoryImpl.java:173: warning: [deprecation] newInstance() in Class has been deprecated
 [ts.javac]       pcFactory = (PolicyConfigurationFactory) clazz.newInstance();
 [ts.javac]                                                     ^
 [ts.javac]   where T is a type-variable:
 [ts.javac]     T extends Object declared in class Class
 [ts.javac] /home/guru/oracle/jakartaee-tck/src/com/sun/ts/tests/jacc/provider/TSPolicyConfigurationImpl.java:46: error: TSPolicyConfigurationImpl is not abstract and does not override abstract method getExcludedPermissions() in PolicyConfiguration
 [ts.javac] public class TSPolicyConfigurationImpl implements PolicyConfiguration {
 [ts.javac]        ^
 [ts.javac] /home/guru/oracle/jakartaee-tck/src/com/sun/ts/tests/jacc/provider/TSPolicyConfigurationImpl.java:924: warning: [deprecation] Character(char) in Character has been deprecated
 [ts.javac]       int a = (new Character(str[i])).getNumericValue(str[i]);
 [ts.javac]                ^
 [ts.javac] Note: Some input files use unchecked or unsafe operations.
 [ts.javac] Note: Recompile with -Xlint:unchecked for details.
 [ts.javac] 2 errors
 [ts.javac] 3 warnings

BUILD FAILED
`

**Comment by gurunrao** [comment]
@arjantijms  - above failure are related to newly added methods for JACC API at https://github.com/jakartaee/authorization/commit/3f5227a639112ece73f3189ec7312a1b6bd78cd2 ?

**Comment by gurunrao** [comment]
this issue is blocker for JACC TCK and Platform TCK builds.

**Comment by arjantijms** [comment]
Those are new methods indeed. They either have to be implemented by the test code, or maybe we should implement a default in the class returning null or so (and stage a new milestone)

**Comment by gurunrao** [comment]
> Those are new methods indeed. They either have to be implemented by the test code, or maybe we should implement a default in the class returning null or so (and stage a new milestone)

we can raise a PR with default class, provided non of the existing tests are broken. Please let us know, if we can proceed.

**Comment by gurunrao** [comment]
> Ps the name JACC is not longer used, the API is now named Jakarta Authorization.

We are referring JACC on code basis,  doc and bundle name will be `Jakarta Authorization` TCK.

**Comment by arjantijms** [comment]
> we can raise a PR with default class, provided none of the existing tests are broken. Please let us know, if we can proceed.

You mean a PR against the spec/api repo, or the TCK repo?

Either one would be fine by me, though maybe spec/api repo is preferred.

**Comment by gurunrao** [comment]
> > we can raise a PR with default class, provided none of the existing tests are broken. Please let us know, if we can proceed.
> 
> You mean a PR against the spec/api repo, or the TCK repo?
> 
> Either one would be fine by me, though maybe spec/api repo is preferred.

I will make changes initial PR to unblock Platform TCK builds.

**Comment by scottmarlow** [comment]
Starting https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/32 build to see if we get compile failures still.
