### ISSUE TITLE
Pages TCK failures with Glassfish 7 , TCK userguide update pending for jsp 3.1

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#832]
**Describe the bug**

9 test failures in Jakarta Pages TCK when run with Glassfish 7

com/sun/ts/tests/jsp/spec/core_syntax/directives/page/URLClient.java#errorOnELNotFoundFalseTest
com/sun/ts/tests/jsp/spec/core_syntax/directives/page/URLClient.java#positiveDuplicateIsThreadSafeTest
com/sun/ts/tests/jsp/spec/core_syntax/scripting/el/URLClient.java#elAttributeSearchTest
com/sun/ts/tests/jsp/spec/core_syntax/scripting/el/URLClient.java#elRelationalOperators1Test
com/sun/ts/tests/jsp/spec/el/jsp/URLClient.java#implicitImportTest
com/sun/ts/tests/jsp/spec/tagfiles/directives/general/URLClient.java#errorOnELNotFoundFalseTest
com/sun/ts/tests/jsp/spec/tagfiles/directives/variable/URLClient.java#syncRemoveAtBeginTest
com/sun/ts/tests/jsp/spec/tagfiles/directives/variable/URLClient.java#syncRemoveAtEndTest
com/sun/ts/tests/jsp/spec/tagfiles/directives/variable/URLClient.java#syncRemoveNestedTest

Also the pages TCK user guide need to be updated https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/jsp .

**To Reproduce the test failures**
1. cd /tmp
2. wget https://ci.eclipse.org/jakartaee-tck/job/build-glassfish/lastSuccessfulBuild/artifact/appserver/distributions/glassfish/target/glassfish.zip
3. unzip glassfish.zip
4. Download latest Jakarta Pages TCK from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0.zip
5. unzip jakarta-pages-tck-3.1.0.zip
6. export TS_HOME=/tmp/pages-tck
7. export WORKSPACE=/tmp ; export TCK_HOME=/tmp ;
8. Follow from https://github.com/eclipse-ee4j/jakartaee-tck/blob/a194effb5306b20a0f2ccbca7ecc0ee21143a436/docker/jsptck.sh#L66 onwards to  run the tck

**Expected behavior**
All the Pages TCK tests should be passing with Glassfish 7.

Test run logs with exception at https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1615/nodes/45/steps/56/log/?start=0

**Comment by markt-asf** [comment]
The version changes I'll try and look at this week.

The TCK failures look like issues for Glassfish.

Glassfish bug as it does not support the new attribute:
 - com/sun/ts/tests/jsp/spec/core_syntax/directives/page/URLClient.java#errorOnELNotFoundFalseTest
 - com/sun/ts/tests/jsp/spec/tagfiles/directives/general/URLClient.java#errorOnELNotFoundFalseTest

Glassfish bug as it still generates code using jakarta.servlet.SingleThreadModel which has been removed from the API
 - com/sun/ts/tests/jsp/spec/core_syntax/directives/page/URLClient.java#positiveDuplicateIsThreadSafeTest

Looks like a Glassfish bug not obviously related to spec/TCK changes (same bug for all)
- com/sun/ts/tests/jsp/spec/core_syntax/scripting/el/URLClient.java#elAttributeSearchTest
- com/sun/ts/tests/jsp/spec/core_syntax/scripting/el/URLClient.java#elRelationalOperators1Test
- com/sun/ts/tests/jsp/spec/el/jsp/URLClient.java#implicitImportTest
- com/sun/ts/tests/jsp/spec/tagfiles/directives/variable/URLClient.java#syncRemoveAtBeginTest
- com/sun/ts/tests/jsp/spec/tagfiles/directives/variable/URLClient.java#syncRemoveAtEndTest
- com/sun/ts/tests/jsp/spec/tagfiles/directives/variable/URLClient.java#syncRemoveNestedTest

**Comment by markt-asf** [comment]
PR for version changes in #859

**Comment by alwin-joseph** [comment]
Pages standalone tests are now passing after resolving https://github.com/eclipse-ee4j/wasp/issues/43 by PR https://github.com/eclipse-ee4j/wasp/pull/45 . 

CI job : https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100/96 
Implementation bundle : glassfish nightly (Apr  7 04:57) https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip
latest TCK bundle : https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0.zip
