### ISSUE TITLE
Remove timestamp from zip file names

### ISSUE THREAD

**Issue by bshannon** [eclipse-ee4j/jakartaee-tck#85]
The timestamp or "latest" should be removed from the zip file names.
The version number should remain, and should include a micro version number
to allow for future micro version release to (e.g.) update the exclude list.
The major and minor version numbers need to match the corresponding spec.

So, the name should be of the form <spec>tck-<version>.zip, e.g.,
connectortck-1.7.0.zip.

**Comment by alwin-joseph** [comment]
We have already made this change as it was conveyed earlier. Can you please check the filenames at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8/nightly/ & https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee8-eftl/staged/ to check if any more changes required. 

* We have not made this change to CDI, DI & BV.

**Comment by bshannon** [comment]
This looks good, although thinking about it a bit more I think it would be better
to put a dash before "tck" in the name, as is done for a few of them.  Eventually
we need to change the names to use the official "short names" for the technologies
so you can defer this additional change until then if you want.

The naming of the CDI, DI, and BV porting kits is less important, but it would make
sense to use the same naming scheme there as well.

**Comment by alwin-joseph** [comment]
This issue was resolved using https://github.com/eclipse-ee4j/jakartaee-tck/pull/90. Hence closing.
The naming of the CDI, DI, and BV porting kits were also done in the respective repos.
