### ISSUE TITLE
Update CDI bean usage for change in default bean-discovery-mode

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#876]
**Describe the bug**
In CDI 4.0 the default for the beans.xml `bean-discovery-mode` attribute has changed to `annotated` from the previous default of `all`. This is an incompatible change that either requires a beans.xml with bean-discovery-mode=all, or introduce bean defining annotations to beans in the deployment.

Any empty beans.xml test deployment should be validated for whether the injected beans contain bean defining annotations, or simply updated to include bean-discovery-mode=all to restore the previous behavior.

**Comment by scottmarlow** [comment]
https://github.com/eclipse-ee4j/jakartaee-tck/pull/879 is merged so the `set.ext.dirs` related build failures should be resolved now.

**Comment by scottmarlow** [comment]
did a quick change of others tests via https://github.com/scottmarlow/jakartaee-tck/tree/cdi-beans.xml which I will build the tck for and run some tests.
