### ISSUE TITLE
former JWS tests fail to run on Tomcat as part of xml-ws tck

### ISSUE THREAD

**Issue by lukasj** [eclipse-ee4j/jakartaee-tck#881]
**To Reproduce**
run xml-ws-4.0.0-tck against latest tomcat 10.1.x (latest one currently is 10.1.0-M11)

see [results](https://ci.eclipse.org/metro/job/JAXWS_jakarta_TCK_10_run/18/artifact/SUMMARY.TXT/*view*/)

symptom found in the server log is:

```
08-Mar-2022 17:21:55.855 SEVERE [Catalina-utility-2] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [com.sun.ts.tests.jws.oneway.server.OnewayWebService] in web application [/WSOnewayWebServiceApp_web] threw load() exception
	java.lang.ClassCastException: class com.sun.ts.tests.jws.oneway.server.OnewayWebService cannot be cast to class jakarta.servlet.Servlet (com.sun.ts.tests.jws.oneway.server.OnewayWebService is in unnamed module of loader org.apache.catalina.loader.ParallelWebappClassLoader @e9424dd; jakarta.servlet.Servlet is in unnamed module of loader java.net.URLClassLoader @4973813a)
		at org.apache.catalina.core.StandardWrapper.loadServlet(StandardWrapper.java:908)
...
```

**Expected behavior**
tests pass :-)

Cause of the problem is that former JWS tests rely on Jakarta Enterprise Web Services like deployment which is available on GF (or any other full-profile EE compliant application server) but not in Tomcat (or any other web-profile EE compliant web server).

I can see two options to fix this:
1. extend JWS tests to be able to run against web-profile only servers (requires updates to web.xml and sun-jaxws.xml - see jaxws tests for how it's done there)
2. exclude JWS tests for web-profile only servers

**Comment by gurunrao** [comment]
@lukasj - one option to run  jws tests for webprofile only servers is:
we need to change our directory to `cd $TS_HOME/src/com/sun/ts/tests/jaxws` and `ant -Dkeywords=all runclient`

- `cd $TS_HOME/src/com/sun/ts/tests/jaxws`
- `ant -Dkeywords=all runclient`

**Comment by gurunrao** [comment]
apart from the ^ option, we can add keywords to mark jws tests as webprofile only.

**Comment by lukasj** [comment]
you mean  `mark jws tests as fullprofile only` (they don't work on webprofile)

**Comment by gurunrao** [comment]
changes with updates to web.xml and sun-jaxws.xml is in-progress.

**Comment by gurunrao** [comment]
Fix PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/883 has been merged.
