### ISSUE TITLE
JSTL TCK Failures for EE10 (JDK 11 / GlassFish 7)

### ISSUE THREAD

**Issue by volosied** [eclipse-ee4j/jakartaee-tck#882]
Now that the JSTL 3.0.0 jars are staged, the latest TCK results show numbers failures (74 under JDK 11). Totals below don't really add up, but this is the majority of the errors.

- **~39** Relate to EL: 
   - `jakarta.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier ‘reTest’` 
   - `jakarta.el.PropertyNotFoundException: ELResolver cannot handle a null base Object with identifier ‘ex2’`   
   - ... and so on
   -  Affects most of the reported failures 
   - The JSP TCK reported similar PropertyNotFoundExceptions for the small number of its failures. Can anyone confirm if these are related (I assume so)? 
   - Example : jstl_core_gen_set_web.war - positiveSetNullValueTest.jsp 
   
- **~12** Relate to Date Parsing:
   - I see numerous occurrences of this ParseException: `java.text.ParseException: Unparseable date: “Nov 21, 2000, 3:45:02 AM”`. 
   - Similar issue occurred before with the EE9 Java 11 TCK:  #631  The solution was run the tests with `-Djava.locale.providers=COMPAT` and add a comma.  I wouldn't expect this ParseException to reoccur then?  
   - Server logs show: `GlassFishConfigBean.com.sun.enterprise.config.serverbeans.JavaConfig}, reason = Addition of: ‘-Djava.locale.providers=COMPAT’ cannot take effect without server restart, when = 1646682092825]]`  Was the property not used when the tests ran? 
   - Example : jstl_fmt_psdate_web.war - positivePDBodyValueTest.jsp 
   
- **~5** Relate to the Javac Compilation of JSPs
   -  `PWC6197: An error occurred at line: 39 in the jsp file: /positiveForTokensDeferredValueTest.jsp
PWC6199: Generated servlet error:
reference to print is ambiguous
  both method print(char[]) in jakarta.servlet.jsp.JspWriter and method print(java.lang.String) in jakarta.servlet.jsp.JspWriter match`
  -  The error says this line is the problem: `<%= ve.getValue(pageContext.getELContext()) %>`. The generated java file uses this line:  `out.print( ve.getValue(pageContext.getELContext()) );`.  
  - Should this be looked at from the JSP perspective? I didn't see any changes to JspWriter, so I'm not sure why it's failing. 
  - Example : jstl_core_iter_fortok_web.war - positiveForTokensDeferredValueTest.jsp
  
- **1** Relates to XML 
   - `java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class org.w3c.dom.Node (java.lang.Boolean is in module java.base of loader ‘bootstrap’; org.w3c.dom.Node is in module java.xml of loader ‘bootstrap’)`
   - https://github.com/eclipse-ee4j/jstl-api/issues/223
   - Only valid issue I see so far within Jakarta Tags  
   - jstl_xml_types_web.war - positiveXPathToJavaTypesTest
   
I've attached the mentions apps here : 
[Apps.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/8219879/Apps.zip)

Glasshfish server log (contains stack traces): 
[server.log.zip](https://github.com/eclipse-ee4j/jakartaee-tck/files/8219919/server.log.zip)

**Comment by markt-asf** [comment]
The 39 EL `PropertyNotFoundException` issues suggest that the JSP implementation isn't providing the `NotFoundELResolver` which will always return `null` rather than throwing an exception.

The 5 JSP errors look like consequences of the EL API using generics. The test JSPs now need to use `<%= (Object) ve.getValue(pageContext.getELContext()) %>`

**Comment by volosied** [comment]
It wouldn't hurt. I'll update the specification in https://github.com/jakartaee/specifications/pull/457

**Comment by volosied** [comment]
Mark was right about the resolvers.  I've created a PR here in glassfish: https://github.com/eclipse-ee4j/wasp/pull/44 

This should get more TCK test passing.

**Comment by volosied** [comment]
@scottmarlow I'm rethinking about listing that compatibility issue (your March 10th comment). I think it would be better listed under JSP or EL.  It's not caused by any change to a JSTL api implementation.
