### ISSUE TITLE
Usage of sed -i is less portable than it could be

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#887]
**Describe the bug**
The current sed -i -e ... usage does not work on BSD based systems like OSX.

**To Reproduce**
✏️ [starksm@Scotts-iMacPro#10922]-(jakartaeetck)
└> cat /tmp/test.txt
Hello=Scott
✏️ [starksm@Scotts-iMacPro#10923]-(jakartaeetck)
└> sed -i 's/Scott/World/g' /tmp/test.txt
sed: 1: "/tmp/test.txt": undefined label 'est.txt'
✏️ [starksm@Scotts-iMacPro#10924]-(jakartaeetck)
└> 

**Expected behavior**
What does work on both BSD and GNU versions of sed is to pass in a backup file extension 

✏️ [starksm@Scotts-iMacPro#10924]-(jakartaeetck)
└> sed -i.bak 's/Scott/World/g' /tmp/test.txt
✏️ [starksm@Scotts-iMacPro#10926]-(jakartaeetck)
└> cat /tmp/test.txt
Hello=World

**Additional context**

**Comment by gurunrao** [comment]
PR is merged, hence closing issue.
