### ISSUE TITLE
Correct Authorization SPEC version from `3.0` to `2.1` in various forms

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#896]
Instead of staging https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authorization-tck-3.0.0.zip, we should be staging https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authorization-tck-2.1.0.zip.  

The https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authorization-tck-3.0.0.zip file should be deleted to avoid confusion.

Platform TCK needs updates to:
- https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/release/tools/jacc.xml#L20 needs to be updated.
- https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/user_guides/jacc
- https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/install/jacc/docs

CC @tjwatson @arjantijms @alwin-joseph @gurunrao @brideck

**Comment by gurunrao** [comment]
PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/897 has been raised to update Auth Spec version.
Also https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-authorization-tck-3.0.0.zip has been deleted.
