### ISSUE TITLE
Remove Faces tests from Platform TCK that are duplicated by the Faces TCK

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#908]
**Describe the bug**
Remove Faces tests from the Platform TCK that are duplicated by the Faces TCK.

The Platform TCK only has Web container tests under https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/jsf which is is mostly Servlet  but also some Server Pages tests (e.g. [test UIComponentELTag](https://jakarta.ee/specifications/faces/3.0/jakarta-faces-3.0.html#a923).

The Faces TCK only has Web container tests under https://github.com/jakartaee/faces/tree/master/tck that are only using Servlet but not Server Pages.

The [EE 9.1 requirements for Faces 3.0 (EE 10 requirements will likely be similar)](https://jakarta.ee/specifications/platform/9.1/jakarta-platform-spec-9.1.html#server-faces-3-0-requirements) state:
> Jakarta Server Faces technology simplifies building user interfaces for Jakarta applications. Developers of various skill levels can quickly build web applications by: assembling reusable UI components in a page; connecting these components to an application data source; and wiring client-generated events to server-side event handlers. In a full Jakarta EE product, all Jakarta EE web containers are required to support applications that use the Jakarta Server Faces technology.

The question to answer first is as to what the Platform requirements are for validating the EE 10 Faces implementation as working correctly.  

The second question to answer is which Faces tests under https://github.com/eclipse-ee4j/jakartaee-tck/tree/master/src/com/sun/ts/tests/jsf are considered duplicate of the new https://github.com/jakartaee/faces/tree/master/tck tests:
- [ ] All of the existing Platform TCK Faces tests are duplicates of https://github.com/jakartaee/faces/tree/master/tck tests.
- [ ] Some of the existing Platform TCK Faces tests are duplicates of https://github.com/jakartaee/faces/tree/master/tck tests (e.g. Servlet tests are duplicated but not the Server Pages tests in Platform TCK since new Faces TCK doesn't test Server Pages).

**Comment by scottmarlow** [comment]
FYI https://github.com/jakartaee/faces/issues/1600 is expected to deliver the new Faces Standalone TCK.

**Comment by alwin-joseph** [comment]
https://github.com/jakartaee/faces/pull/1649 is to migrate all the faces tests from Platform TCK to [Faces](https://github.com/jakartaee/faces).  If this is approved and merged I guess the issue description can be changed. 

Shall we consider the goal as to remove all the faces tests from jakartaee-tck now? Also we would have to integrate the new faces tck from https://github.com/jakartaee/faces/tree/master/tck/faces-tck. Will it be required to run the new faces tests from https://github.com/jakartaee/faces/tree/master/tck to be run for platform requirements

**Comment by scottmarlow** [comment]
Closing as all Faces tests are moved out of jakartaee-tck now.
