### ISSUE TITLE
67 Test Failures in Security TCK 

### ISSUE THREAD

**Issue by alwin-joseph** [eclipse-ee4j/jakartaee-tck#927]
**Describe the bug**
There are 67 test failures in Security TCK when run with glassfish, that are expected to be resolved for JakartaEE 10.

CI pipeline job : https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/1741/pipeline/64 
TCK run logs : https://ci.eclipse.org/jakartaee-tck/blue/rest/organizations/jenkins/pipelines/jakartaee-tck/branches/master/runs/1741/nodes/64/steps/176/log/?start=0

server logs from local run : 
[server.log](https://github.com/eclipse-ee4j/jakartaee-tck/files/8479881/server.log)

To Reproduce the test failures

 - cd /tmp
 - wget https://download.eclipse.org/ee4j/glassfish/glassfish-7.0.0-SNAPSHOT-nightly.zip
 - unzip glassfish-7.0.0-SNAPSHOT-nightly.zip
 - Download latest Jakarta Security TCK from https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-security-tck-3.0.0.zip
 - unzip jakarta-security-tck-3.0.0.zip
 - export TS_HOME=/tmp/security-tck
 - export WORKSPACE=/tmp ; export TCK_HOME=/tmp ;
 - Follow from https://github.com/eclipse-ee4j/jakartaee-tck/blob/e2d17ec7dd6bf40284a82ff730de92a339bdc281/docker/securityapitck.sh#L72 to run the TCK.

@arjantijms  @rdebusscher @OndroMih If you happen to know the cause of these failures please do suggest.

cc @scottmarlow @markt-asf @gurunrao

**Comment by alwin-joseph** [comment]
Several of the failures are due to 

1. `web username: null` 

From server logs : 

```
     [echo] Caused by: javax.security.auth.login.LoginException: Failed file login for tom.
     [echo] 	at com.sun.enterprise.security.auth.login.FileLoginModule.authenticate(FileLoginModule.java:55)
     [echo] 	at com.sun.enterprise.security.auth.login.PasswordLoginModule.authenticateUser(PasswordLoginModule.java:80)
     [echo] 	at com.sun.enterprise.security.BasePasswordLoginModule.login(BasePasswordLoginModule.java:114)
```

From tck run log : 

```
     [echo]   WEB9102: Web Login Failed
     [echo] com.sun.enterprise.security.auth.login.common.LoginException: Login failed: Failed file login for tom.
     [echo] 	at com.sun.enterprise.security.auth.login.LoginContextDriver.doPasswordLogin(LoginContextDriver.java:339)
     [echo] 	at com.sun.enterprise.security.auth.login.LoginContextDriver.login(LoginContextDriver.java:199)
     [echo] 	at com.sun.enterprise.security.auth.login.LoginContextDriver.login(LoginContextDriver.java:124)
```


2. NPE issue : 

From server logs : 
```
     [echo] java.lang.NullPointerException
     [echo] 	at com.sun.ts.tests.securityapi.securitycontext.ejb.Servlet.doGet(Servlet.java:62)
     [echo] 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:527)
     [echo] 	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:614)

```
From tck run log : 

```
The server encountered an internal error that prevented it from fulfilling this request.</p><p><b>exception</b> <pre>java.lang.NullPointerException: Cannot invoke &quot;jakarta.security.enterprise.AuthenticationStatus.name&#40;&#41;&quot; because &quot;status&quot; is null
```

**Comment by arjantijms** [comment]
@alwin-joseph as a very quick guess, this could be yet another victim of CDI having changed the meaning of beans.xml again. 

You see native (GlassFish specific) authentication being attempted here, which means the CDI based Jakarta Security Authentication Mechanism wasn't found. When CDI doesn't scan beans, due to the changed meaning of an empty beans.xml, that would be expected.

**Comment by OndroMih** [comment]
CDI 4.0 did change the meaning of an empty beans.xml - now only annotated beans are discovered in that case. To keep the previous behavior, beans.xml needs to explicitly set `bean-discovery-mode="all"`.

There's also one signature test failing for `identitystore`. It says that 

```
LinkageError does not allow to track definition in
--------------------------------------------------

jakarta.security.enterprise.identitystore.openid.OpenIdContext:                 thrown java.lang.NoClassDefFoundError: jakarta/json/JsonObject
 --- affected jakarta.security.enterprise.identitystore.openid.OpenIdContext not linked
```
But I don't know what's the reason of this. It looks to me that GlassFish (and Soteria impl included in it) is up to date according to the source code but I haven't checked thoroughly.

**Comment by alwin-joseph** [comment]
> 



> There's also one signature test failing for `identitystore`. It says that
> 
> ```
> LinkageError does not allow to track definition in
> --------------------------------------------------
> 
> jakarta.security.enterprise.identitystore.openid.OpenIdContext:                 thrown java.lang.NoClassDefFoundError: jakarta/json/JsonObject
>  --- affected jakarta.security.enterprise.identitystore.openid.OpenIdContext not linked
> ```
> 
> But I don't know what's the reason of this. It looks to me that GlassFish (and Soteria impl included in it) is up to date according to the source code but I haven't checked thoroughly.

The signature test is being migrated to security repo via https://github.com/jakartaee/security/pull/226. The PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/920 that would have fixed this in jakartaee-tck was closed since it is being migrated.

**Comment by alwin-joseph** [comment]
Created https://github.com/jakartaee/security/pull/232 , all tests were tested in local and were passing with this change.  Thanks @arjantijms & @OndroMih !

**Comment by arjantijms** [comment]
> Thanks @arjantijms & @OndroMih !

Thanks @alwin-joseph for bringing this up and validating it. Much appreciated!
