### ISSUE TITLE
New Expression Language tests don't setup ElContext for invoke

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#932]
Some of the new tests for the Jakarta Expression Language 5.0.0 TCK, like e.g.

`com/sun/ts/tests/el/api/jakarta_el/methodexpression/ELClient.java#methodExpressionMatchingCoercionBeatsExactVarArgsTest` contain code such as the following:

```
        StringBuffer buf = new StringBuffer();
        String exprStr = "#{bean.targetD('1','1')}";

        ExpressionFactory expFactory = ExpressionFactory.newInstance();
        ELContext context = (new VarMapperELContext(props)).getELContext();

        MethodsBean bean = new MethodsBean();
        ValueExpression ve = expFactory.createValueExpression(bean, MethodsBean.class);
        context.getVariableMapper().setVariable("bean", ve);

        MethodExpression me = expFactory.createMethodExpression(context, exprStr, String.class, null);
        me.invoke(...);
```

It seems this form of method expressions with provided parameters (the '1' and '1' here)) have never been tested before, and so the custom `ELContext` hasn't been set up to take this into account.

Expressly (the former GlassFish RI) use an ELResolver for the `me.invoke(...)` part. That's where it goes wrong, as the test sets up its own custom ELContext (VarMapperELContext) which provides custom ELResolvers that are not suitable for method invocation.

I think besides the custom `VariableELResolver()`, the standard `jakarta.el.BeanELResolver()` should be in the list of resolvers.

cc @markt-asf @alwin-joseph

**Comment by scottmarlow** [comment]
Is this issue resolved now via https://github.com/eclipse-ee4j/jakartaee-tck/pull/933?

**Comment by markt-asf** [comment]
Yes.
