### ISSUE TITLE
Need new staging of Jakarta Pages TCK

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#941]
The latest pages tck is from 18 April:

https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0-tckinfo.txt

There was however an update to the TCK on 21 April:

https://github.com/eclipse-ee4j/jakartaee-tck/pull/940

CC @alwin-joseph @markt-asf

**Comment by alwin-joseph** [comment]
The latest TCK is now available at https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-pages-tck-3.1.0.zip.
