### ISSUE TITLE
Make sure servlet TCK is not copied to promoted anymore

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#949]
The ballot for Servlet TCK has started. If there's any job that automatically copies the servlet 6 TCK to promoted, that job must be stopped.

cc @alwin-joseph

**Comment by scottmarlow** [comment]
Thanks, I will update the job that does that.

**Comment by scottmarlow** [comment]
Just updated https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-standalonetck-build-run-100 by moving `servlet` to list of TCKs to not build/run.

**Comment by gurunrao** [comment]
@arjantijms  - We wanted to merge PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/934/files , do u want to hold the merge?
CC @scottmarlow @markt-asf

**Comment by scottmarlow** [comment]
Reopening as we can still merge https://github.com/eclipse-ee4j/jakartaee-tck/pull/934 and build the Servlet TCK once more.

**Comment by scottmarlow** [comment]
We will only merge https://github.com/eclipse-ee4j/jakartaee-tck/pull/934 if @arjantijms has time to verify yet one more new (yet to be staged) Servlet TCK, so merge is pending Arjan comment...

**Comment by arjantijms** [comment]
If it's process wise allowed, I can run the TCK yet again. The ballot has already started though.

**Comment by scottmarlow** [comment]
> If it's process wise allowed, I can run the TCK yet again. The ballot has already started though.

I commented on the ballot issue that I think we should continue the ballot as doing otherwise would delay EE 10.

**Comment by arjantijms** [comment]
Okay, let's continue the ballot. The test is a nice-to-have but absolutely not critical. It just missed the train, but there well be a next train soon anyway with EE 11.
