### ISSUE TITLE
Remove MaxPermSize from various .j2e files

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#951]
Various .j2e files still contain the `MaxPermSize` option. This is not supported anymore and fails on the JDK in later versions.

**Comment by scottmarlow** [comment]
```
grep -rli MaxPermSize
install/jaspic/bin/ts.jte
install/connector/bin/ts.jte
install/jacc/bin/ts.jte
install/jakartaee/bin/ts.jte
user_guides/jaspic/src/main/jbake/content/config.inc
```

**Comment by scottmarlow** [comment]
We have already released TCKs with MaxPermSize but still good to clean up the various references in all files.
