### ISSUE TITLE
Update Jakarta Authorization / JACC user guide for 2.1

### ISSUE THREAD

**Issue by arjantijms** [eclipse-ee4j/jakartaee-tck#954]
The user guide for Jakarta Authorization hasn't been updated for 2.1 yet.

See https://github.com/jakartaee/specifications/pull/461#issuecomment-1114905469

**Comment by arjantijms** [comment]
cc @alwin-joseph @scottmarlow @starksm64

**Comment by scottmarlow** [comment]
Addressed via https://github.com/eclipse-ee4j/jakartaee-tck/pull/955

**Comment by scottmarlow** [comment]
Addressed via https://github.com/eclipse-ee4j/jakartaee-tck/pull/956 + https://github.com/eclipse-ee4j/jakartaee-tck/pull/955
