### ISSUE TITLE
Remove HttpUtils use in jsp

### ISSUE THREAD

**Issue by scottmarlow** [eclipse-ee4j/jakartaee-tck#960]
As per https://www.eclipse.org/lists/jsp-dev/msg00303.html, resolve failure `Cannot find symbol HttpUtils` in [basicSSL.jsp](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/com/sun/ts/tests/integration/sec/secbasicssl/basicSSL.jsp#L53) as HttpUtils is removed in Servlet 6.0.

Also remove comment reference to HttpUtils in 
[implicitImportHttp.jsp](https://github.com/eclipse-ee4j/jakartaee-tck/blob/master/src/web/jsp/spec/tagfiles/directives/tag20/implicitImportHttp.jsp.

**Comment by scottmarlow** [comment]
@markt-asf what does `String requestURL = HttpUtils.getRequestURL( request ).toString();` need to change to?

**Comment by markt-asf** [comment]
You can use `HttpServletRequest.getRequestURL()` but looking at the test it could just use getScheme() and achieve the same result. I'll do a quick PR but note that I can't test this as I'm not set up to run the platform tests, just the individual specs.
