### ISSUE TITLE
Task for addressing ejblitejsf vehicle failures

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#968]
We need to follow the approach in the #962 PR for every set of tests that have the ejblitejsf vehicle mapping in the install/jakartaee/other/vehicle.properties file. This looks to be every test package under:

- [com/sun/ts/tests/jta/ee/transactional](https://github.com/eclipse-ee4j/jakartaee-tck/issues/977)
- com/sun/ts/tests/ejb30/lite except
  - com/sun/ts/tests/ejb30/lite/packaging/embed
  - com/sun/ts/tests/ejb30/lite/stateful/timeout
  - com/sun/ts/tests/ejb30/bb/session/stateful/timeout
- com/sun/ts/tests/ejb30/bb/async (Covered in https://github.com/eclipse-ee4j/jakartaee-tck/pull/1005 )
- com/sun/ts/tests/ejb30/bb/session/stateful/concurrency
- [com/sun/ts/tests/ejb32/lite](https://github.com/eclipse-ee4j/jakartaee-tck/issues/968) (done via https://github.com/eclipse-ee4j/jakartaee-tck/pull/971 and https://github.com/eclipse-ee4j/jakartaee-tck/pull/1008 )

I'll create sub issues for each package so we can track who is doing the work.

**Comment by alwin-joseph** [comment]
Status of ejb test failures related to migration of  ejblitejsf vehicle : 

CI job : https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/68/ 
Pipeline job : https://ci.eclipse.org/jakartaee-tck/blue/organizations/jenkins/jakartaee-tck/detail/master/1824/pipeline 


1. ejb30/lite/async : 

From failures logs   - 

```
   [runcts] OUT => [javatest.batch] 05-19-2022 09:50:49:  Harness - TSScript:  No vehicle ear found in : "/root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/ejb30/lite/async/singleton/annotated".  If this is a test that requires test clients to be built before executing the tests, please refer to the TCK documentation for further instructions.
   [runcts] OUT => [javatest.batch] Failed. TSScript: No vehicle ear found in : "/root/jakartaeetck/bin/xml/../../dist/com/sun/ts/tests/ejb30/lite/async/singleton/annotated". If this is a test that requires test clients to be built before executing the tests, please refer to the TCK documentation for further instructions.
```

When I checked the tck bundle it does not have the archive corresponding to ejblitejsf vehicle where it is supposed to exist. 
In platform TCK build this vehicle is skipped while packaging the archive for some reason . 

Looking at mainly below files - 
src/com/sun/ts/tests/ejb30/lite/async/singleton/annotated/build.xml (property : ejblite.vehicles)
src/com/sun/ts/tests/ejb30/common/import.xml ()
bin/xml/ts.vehicles.xml (property : vehiclestobuild)


2. ejb30/lite/packaging 

will update when job is completed

**Comment by alwin-joseph** [comment]
Current Status of ejb test failures related to migration of ejblitejsf vehicle :

CI job : https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/71/testReport/

Pending failures

1. ejb30/lite/packaging (25 failures) : WIP (draft PR https://github.com/eclipse-ee4j/jakartaee-tck/pull/1020 )

2. ejb30/lite/stateful/concurrency/metadata/descriptor (12 failures) : Yet to find the root cause.


PS: There are 44 failures below unrelated to ejblitejsf vehicle update. This can be tracked separately. 
 ejb30/lite/stateful/timeout (44 failures) : vehicles failing ejblitejsp and ejbembed - Yet to find the root cause.
 
 @starksm64 @scottmarlow @gurunrao
