### ISSUE TITLE
Migrate com/sun/ts/tests/ejb30/lite/basic/* ejblitejsf vehicle tests

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#970]
As per #968, migrate the com/sun/ts/tests/ejb30/lite/basic/* tests

**Comment by gurunrao** [comment]
issue is resolved as per build https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/lastCompletedBuild/testReport/
