### ISSUE TITLE
migrate the com/sun/ts/tests/ejb30/lite/enventry/* ejblitejsf vehicle tests

### ISSUE THREAD

**Issue by starksm64** [eclipse-ee4j/jakartaee-tck#979]
As per https://github.com/eclipse-ee4j/jakartaee-tck/issues/968, migrate the com/sun/ts/tests/ejb30/lite/enventry/* tests

**Comment by gurunrao** [comment]
issue is resolved as per build https://ci.eclipse.org/jakartaee-tck/job/10/job/eftl-jakartaeetck-run-100/lastCompletedBuild/testReport/
